### ISSUE TITLE
Parallelizable differential expression

### ISSUE THREAD

**Issue by Munfred** [scverse/scvi-tools#1083]
I find myself frequently doing pairwise differential expression for all clusters in the data, and sometimes I end up running it as an overnight job. 

It would be very handy if the DE could be parallelizable on the CPUs available, since DE is fairly fast on CPU already (in my experience doing DE on CPU only is about half as fast as when a GPU is available).

**Comment by martinkim0** [comment]
For anyone visiting this thread - we recommend doing one vs. all comparisons for differential expression since there's fewer computations. And you can do pairwise comparisons for close cell types, but not for all of them.
