### ISSUE TITLE
MuData integration

### ISSUE THREAD

**Issue by watiss** [scverse/scvi-tools#1137]
Consider adding support for the [muon](https://muon.readthedocs.io/en/latest/) data type in scvi-tools

**Comment by adamgayoso** [comment]
I see we have #1286 -- now that v0.15 is released, can we mock this up again?

**Comment by adamgayoso** [comment]
I think we should get this in, but we will first need to add future warnings in 0.16.0 and break it in 0.17.0, specifically for totalVI and multiVI

**Comment by adamgayoso** [comment]
For totalVI, I think we can add `setup_mudata` with a mudata-tuned signature. If `setup_mudata` is used, anndatas cannot be used with that model instance. Then in `BaseModelClass.load` we figure out how to make it detect that it should use `setup_mudata` during load.

**Comment by jjhong922** [comment]
I'm comfortable with that idea. The registry can just additionally store `setup_mudata` vs `setup_anndata` in the `setup_method_args` to accomplish this. I can definitely mock up an implementation from this.

**Comment by jjhong922** [comment]
Fixed by https://github.com/scverse/scvi-tools/pull/1474
