### ISSUE TITLE
Lightning Tutorials

### ISSUE THREAD

**Issue by tchaton** [scverse/scvi-tools#1147]
Dear scvi-tools Team,

My name is Thomas Chaton and I am part of the PyTorch Lightning Team.

I dived into this framework while investigating speed drop (here is the tracking issue: https://github.com/PyTorchLightning/pytorch-lightning/issues/9304). We apologise for this.

We are planning a Community Sprint for building high quality tutorial: https://github.com/PyTorchLightning/lightning-tutorials.
Currently, Deep Learning Course of University of Ámsterdam is been added.

We would like to invite your team to contribute a course / notebook on probabilistic model from scratch and then with scvi-tools library. We will heavily promote this notebook within the Lightning documentation.

Would anyone interested to make this contribution ?

Best,
T.C

**Comment by adamgayoso** [comment]
Hi @tchaton thank you for helping with the pytorch lightning issues. We would be interested in contributing here, maybe we can show latent dirichlet allocation three ways:

1. Pure lightning
2. Scvi-tools
3. Scvi-tools with Pyro backend (still trained with lightning)

**Comment by tchaton** [comment]
Sounds great ! Any chance it could be slightly faster ?

**Comment by adamgayoso** [comment]
we can try :)
