### ISSUE TITLE
Jupyter Notebooks need to be run/tested locally or during CI

### ISSUE THREAD

**Issue by watiss** [scverse/scvi-tools#1160]
We need to write a script that runs all the notebooks. At the very least so it can be done locally, but ideally on github (perhaps with paying AWS or using UCB clusters etc)

There are some pointers out there ([here](https://github.com/ReviewNB/support/issues/19), [here](https://github.com/mcullan/jupyter-actions)).

**Comment by martinkim0** [comment]
https://sionwilliams.com/posts/2020-02-04_jupyter_ci/

**Comment by martinkim0** [comment]
Addressed in scvi-tutorials
