### ISSUE TITLE
LDA Incremental Updates

### ISSUE THREAD

**Issue by justjhong** [scverse/scvi-tools#1167]
WIth the addition of AmortizedLDA, we would like to make incremental updates to improve the model. This issue will serve as the parent issue for a bunch of small features we would like add to the LDA model.

- [x] Tutorial for LDA #1195
- [x] User Guide for Amortized LDA #1178 
- [ ] Automated selection of n_topics
- [ ] Non-amortized LDA model
- [ ] prodLDA flavor of LDA
- [ ] correlated topic model
- [ ] Integrate with enrichR or expose an API for enrichment analysis of LDA topics

**Comment by adamgayoso** [comment]
Also if the normal prior has a full covariance matrix it becomes the correlated topic model...
