### ISSUE TITLE
Implement Prescient

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scvi-tools#1184]
Proposal to implement Prescient.

1. Code: https://github.com/gifford-lab/prescient
2. Paper: https://www.nature.com/articles/s41467-021-23518-w

Level of difficulty: Intermediate, the model is already written with PyTorch. A custom training plan is probably necessary.

**Comment by PierreBoyeau** [comment]
In addition to having the model, I think this is an opportunity to use cases of exotic data handling approaches.
Do you think we should get in touch with their lab?

**Comment by adamgayoso** [comment]
Yes I think it's a good stress test. Would be great if you contacted them.

**Comment by PierreBoyeau** [comment]
Ok let me contact them, I'll cc-you!
