### ISSUE TITLE
`_validate_anndata` should deal with AnnData

### ISSUE THREAD

**Issue by jjhong922** [scverse/scvi-tools#1409]
If somebody subsets an anndata and makes a copy, it will grab the wrong AnnDataManager. Validate_anndata should handle this by copying in place and attempting transfer.

To copy in place: https://github.com/scverse/scvi-tools/blob/a5a7c596d1057a9fcd46dafd2a935b8ebbfbbc8d/scvi/model/base/_base_model.py#L358

Where to address: https://github.com/scverse/scvi-tools/blob/2472b76572672fb9c98755522fa3c7326a946444/scvi/model/base/_base_model.py#L209-L213

**Comment by adamgayoso** [comment]
https://github.com/scverse/scvi-tools/blob/2472b76572672fb9c98755522fa3c7326a946444/scvi/model/base/_base_model.py#L257-L261
