### ISSUE TITLE
Nan in Categorical obs leads to runtime error

### ISSUE THREAD

**Issue by sohitmiglani** [scverse/scvi-tools#1410]
I'm training an scvi model on my AnnData matrix and it gives me a long Runtime error associated with the one-hot encoding

```python
model.train()
```

There's a much bigger error above this. The last part is the following:

```pytb
File ~/miniconda3/envs/singlecell/lib/python3.9/site-packages/scvi/nn/_utils.py:7, in one_hot(index, n_cat)
      5 """One hot a tensor of categories."""
      6 onehot = torch.zeros(index.size(0), n_cat, device=index.device)
----> 7 onehot.scatter_(1, index.type(torch.long), 1)
      8 return onehot.type(torch.float32)

RuntimeError: index -1 is out of bounds for dimension 1 with size 9
```

#### Versions:

> '0.15.0'

**Comment by adamgayoso** [comment]
Can you describe what model you're using, how you ran setup anndata, what your anndata contains, and the output of `model.view_anndata_setup()`?

**Comment by adamgayoso** [comment]
Also if you could provide a script of how you initialize and train the model, that would be super helpful.

**Comment by sohitmiglani** [comment]
Actually - I found the problem. One of the categorical covariates that I specified in my model had 'Nan' in anndata.obs . When I removed them, the training went smoothly. 

This is my code for training the model:

```python
scvi.model.SCVI.setup_anndata(all_matrices_hg38 , layer="counts",
    categorical_covariate_keys=[ "sample", "phase", "run"],
    continuous_covariate_keys=["pct_counts_mt", "pct_counts_ribo"] )
```

In my data, the variable 'sample' had some Nan's in there that I hadn't removed by mistake. Maybe this could be a data check method we could build into scvi? like a piece of a code that makes sure that the input AnnData doesn't have any such missing data that would throw errors in the TensorFlow code?

**Comment by adamgayoso** [comment]
Yes that is a very good thing we should add, I'll leave this issue open until we add this.

**Comment by sohitmiglani** [comment]
I am also happy to take care of this and make a pull request if you'd like.

**Comment by adamgayoso** [comment]
If you'd like! We need to refactor a bit this part

https://github.com/scverse/scvi-tools/blob/a5a7c596d1057a9fcd46dafd2a935b8ebbfbbc8d/scvi/data/fields/_obsm_field.py#L309-L318

to use the checks found here:

https://github.com/scverse/scvi-tools/blob/a5a7c596d1057a9fcd46dafd2a935b8ebbfbbc8d/scvi/data/_utils.py#L123

Basically what happened is nan results in -1 in the categorical object codes, which this util picks up, but is not used for `categorical_covariate_keys`. I think we can lightly refactor the util a bit.... @jjhong922 might have a better idea.

**Comment by sohitmiglani** [comment]
Thanks for sending this! I will run this code line by line on my AnnData object with the nan's to see where the -1 appears. I will probably do this tomorrow and will follow up then.

**Comment by adamgayoso** [comment]
@sohitmiglani we are on a sprint for the next patch release, @jjhong922 will take care of this and we will have a new release tomorrow or the next day. I would hope you can contribute something in the future!!
