### ISSUE TITLE
 scvi.model.SCANVI.load_query_data requires same cell_type key to be present in query data

### ISSUE THREAD

**Issue by saketkc** [scverse/scvi-tools#1449]
For the SCANVI-scarches [example](https://docs.scvi-tools.org/en/0.14.0/tutorials/notebooks/scarches_scvi_tools.html), the query is expected to have the "celltype" column. Am I missing something?

```python

# delete the cell_type key

adata_query.obs = adata_query.obs.drop(columns="celltype")

vae_q = scvi.model.SCANVI.load_query_data(
    adata_query,
    dir_path_scan,
)
vae_q._unlabeled_indices = np.arange(adata_query.n_obs)
vae_q._labeled_indices = []
vae_q.train(
    max_epochs=100,
    plan_kwargs=dict(weight_decay=0.0),
    check_val_every_n_epoch=10,
)


```

```pytb
    128 super().validate_field(adata)
    129 if self._original_attr_key not in adata.obs:
--> 130     raise KeyError(f"{self._original_attr_key} not found in adata.obs.")

KeyError: 'celltype not found in adata.obs.'


```

#### Versions:

> 0.15.2

**Comment by adamgayoso** [comment]
this is currently the intended behavior, but I think we can address this

**Comment by adamgayoso** [comment]
For reference, you can use [this](https://docs.scvi-tools.org/en/stable/api/reference/scvi.model.SCANVI.html#view-setup-args) method to see what key you would need to use on a saved model.

**Comment by adamgayoso** [comment]
@jjhong922 upstream of setup_anndata internally in `load_query_data` we need to detect if the labels key is present, if it's not, populate it with the unlabeled category of scanvi (also make sure cls is scanvi) and send a warning about it

**Comment by saketkc** [comment]
Thanks, I think it would be wonderful to handle this internally - it is counterintuitive to think that one would have labels to start off with for the query. I will close this.

**Comment by adamgayoso** [comment]
Reopening so we can track that we improve this aspect. @saketkc btw the tutorial you linked is for version 14, the version 15 tutorial uses a slightly different version of pancreas
