### ISSUE TITLE
Model load does not pass in train parameters for pyro module

### ISSUE THREAD

**Issue by chaichontat** [scverse/scvi-tools#1483]
Hi, I was loading a previously trained model with a small batch size. In the `load` function, attempts to train the model by one step. This fails as there is not enough memory.

https://github.com/scverse/scvi-tools/blob/6e734bc828521d58d92265548c0fdc338ecb22cf/scvi/model/base/_base_model.py#L632-L636

The `train` function that I'm using accepts other keyword arguments including batch size and passing that in resolves this issue. Would it be possible to add keyword arguments to the `load` function that would be forwarded into the `train` function? I could make a PR if that is ok.

**Comment by adamgayoso** [comment]
thanks for the issue, what kwargs exactly would you want to pass? If it's just batch size we can probably do that internally. Also it's important to consider not all pyro models will train with minibatches. @vitkl any ideas?

**Comment by chaichontat** [comment]
Like you said, since this is an abstract class, I'm thinking in terms of 
```python
  @classmethod
  def load(
      cls,
      dir_path: str,
      adata: Optional[AnnData] = None,
      use_gpu: Optional[Union[str, int, bool]] = None,
      prefix: Optional[str] = None,
      train_kwargs: Optional[dict[str, Any]] = None,
  ):
```
where the user is free to pass their own `dicts`.

**Comment by adamgayoso** [comment]
I'm more inclined to have a solution that looks more like a callback. Suppose we had `model.on_load_module_start` @jjhong922 any thoughts?

**Comment by jjhong922** [comment]
Given that this train step only happens in the Pyro model for a very specific reason, I would avoid putting it in the load signature of the BaseModelClass. Agree with @adamgayoso about having a callback solution or just fixing it for this case internally. Alternatively, you can also make this Module specific and put an `on_load()` callback on the Module level, then have that called by `model.load()`. This way you can just put it on the `PyroBaseModuleClass` and fix it across any of the relevant modules and, in turn, models.

**Comment by adamgayoso** [comment]
@jjhong922 we can also write a simple callback class specific to loading, and this class can be associated with the model class as like a property or something. This way in this case, devs can overwrite the one method they want to in the callback and tell the model to use that callback class

**Comment by vitkl** [comment]
I agree that would be good to pass train parameters to the load function. The current solution is that all models are loaded with minibatch training and default minibatch side (based on `batch_size = None`). Would be good to have an option to do otherwise. 

In terms of the backend, I don't fully understand the solutions so hard to comment but I would try to minimise the number of changes people need to do (changing both the model, module and pyro model class will be too much).

Could the problem that @chaichontat is facing be solved by simply creating a custom training method with a small default batch size? Both currently and in principle?

**Comment by chaichontat** [comment]
> Given that this train step only happens in the Pyro model for a very specific reason, I would avoid putting it in the load signature of the BaseModelClass. Agree with @adamgayoso about having a callback solution or just fixing it for this case internally. Alternatively, you can also make this Module specific and put an `on_load()` callback on the Module level, then have that called by `model.load()`. This way you can just put it on the `PyroBaseModuleClass` and fix it across any of the relevant modules and, in turn, models.

You're right. The `on_load()` solution seems to induce the lowest amount of complexity.

@vitkl Yep, the callback method would wrap the training method which can pass in the smaller batch size.

**Comment by adamgayoso** [comment]
@jjhong922 let's also prioritize this
