### ISSUE TITLE
n+1 problems

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scvi-tools#1491]
Hi,
each time I want to integrate n datasets, I must run scvi-tools on all the datasets again. Can I add 1 new datasets to the existed datasets without running the n+1 datasets again ?

**Comment by adamgayoso** [comment]
1. You might find [this](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scarches_scvi_tools.html) tutorial useful.
2. [This](https://www.nature.com/articles/s41587-021-01001-7) paper
3. We do appreciate these sorts of questions not related to development of the code on our [forum](https://discourse.scverse.org/). Thanks!
