### ISSUE TITLE
Fix destvi equation 6 in user guide

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scvi-tools#1500]
https://github.com/scverse/scvi-tools/blob/346b4a68a92ee310d0d0a7540012731f8339b56b/docs/user_guide/models/destvi.md?plain=1#L184-L188

Not sure what eta reg and beta reg are, and no need to write l1_reg as you have the norm notation

**Comment by cane11** [comment]
https://github.com/scverse/scvi-tools/pull/1501
