### ISSUE TITLE
What is the logic behind setting the max number of training epochs in scVI to min([round((20000 / n_cells) * 400), 400])

### ISSUE THREAD

**Issue by rangan2510** [scverse/scvi-tools#1509]
According to the documentation available at https://docs.scvi-tools.org/en/stable/api/reference/scvi.model.base.PyroSviTrainMixin.html?highlight=train#methods-table  scVI uses a default max training epochs of np.min([round((20000 / n_cells) * 400), 400]).

However, the documentation does not quite justify why. Any idea where I can get this information? Or was this set as just a rule of thumb?

**Comment by adamgayoso** [comment]
Hi @rangan2510 -- this is just a heuristic we use so that epochs linearly decrease given some threshold. In the future we really appreciate making questions like this on [discourse](https://discourse.scvi-tools.org/) as we reserve github for development related conversations.
