### ISSUE TITLE
Activation functions other than ReLU

### ISSUE THREAD

**Issue by Koncopd** [scverse/scvi-tools#1510]
Is there a way to pass an activation function class to SCVI? I don't see it in the arguments. I am trying to use differential geometry to analyze the manifold of VAE latent spaces and ReLU seems to break the approach.

**Comment by adamgayoso** [comment]
Internally, yes

https://github.com/scverse/scvi-tools/blob/5496b993b07e94ac4a6f111589d61a34154bb126/scvi/nn/_base_components.py#L69

From the user-facing API, not really. You'd have to make the `activation_fn` a kwarg of the `VAE` class

**Comment by Koncopd** [comment]
Yes, thx, this i saw already. But i really would prefer to use the base scvi, not custom implementation. I can make a PR with this option, would it be fine?

**Comment by adamgayoso** [comment]
yes, sounds good, so long as the PR adds `activation_fn` to the init of `VAE`

**Comment by martinkim0** [comment]
Closed via #1986
