### ISSUE TITLE
AttributeError: module 'jaxlib.xla_extension' has no attribute 'CpuDevice'

### ISSUE THREAD

**Issue by giovp** [scverse/scvi-tools#1513]
same as described here
https://github.com/google/jax/issues/10331

```python
from scvi.external import RNAStereoscope
```

#### Versions:
scvi-tools==0.16.0

reverting jax and jaxlib to 0.3.2 seemed to solve the issue

**Comment by adamgayoso** [comment]
This should be fixed now with the new release of chex
