### ISSUE TITLE
Can't set labels for scanvi

### ISSUE THREAD

**Issue by Koncopd** [scverse/scvi-tools#1514]
```
scanvae = scvi.model.SCANVI.from_scvi_model(
    vae, 
    adata=source_adata, 
    labels_key=cell_type_key, 
    unlabeled_category="Unknown"
)
```
This initialization always gives empty labelled indices because here
https://github.com/scverse/scvi-tools/blob/7ba36b13e940fbb89e2f1c5fde4ffe3c461cb5b5/scvi/model/_scanvi.py#L255
`labels != self.unlabeled_category_` always evaluates to just **scalar** value `True` (not an array) and therefore `self._labeled_indices` is always `[]`.

This happens because `labels` is integer and `self.unlabeled_category_` is a string

**Comment by jjhong922** [comment]
Thank you for finding this! We have a PR out for this bug now. It will be included in a patch release that should come out soon.
