### ISSUE TITLE
ValueError: Expected parameter loc of distribution Normal

### ISSUE THREAD

**Issue by johnjeang** [scverse/scvi-tools#1531]
I've noticed a recurring issues when trying to run either the scVI or scGEN batch correction methods.  My problem is probably not with either package itself, but I was hoping someone had some insight on how to fix it.

After creating a model via 

`
model = scvi.model.SCVI(train)
`
When trying to run 
`
model.train(train_size=1.0, early_stopping=True)
`
I get the following error, but I am having trouble interpreting where I need to make changes.  Is this perhaps an issue with the data itself or is it the environment I am trying to run this package in?
`
ValueError: Expected parameter loc (Tensor of shape (128, 10)) of distribution Normal(loc: torch.Size([128, 10]), scale: torch.Size([128, 10])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<AddmmBackward0>)
`

Let me know if anyone has any suggestions, 
Thanks!

**Comment by adamgayoso** [comment]
This is likely a data problem. Can you describe a bit about your data?

**Comment by johnjeang** [comment]
Of course, 
The data is scRNA-seq count data arranged as (cell x gene).  The data exists as an anndata object.
There aren't any nans in the count data.  The data is separated into 2 batches ("source" is the batch key) labeled as "cell" and "nuclei" respectively.

What other details might be important for identifying the problem?  There is a `layer` labeled as "counts" where the counts are stored.

**Comment by adamgayoso** [comment]
do you have any extreme values in your count matrix?

**Comment by johnjeang** [comment]
I don't think so, however I think I may have located the problem.
The count data was normalized, but when I input unnormalized counts the error appears to go away.  Sorry, I guess that was a key piece of information I left out!  I didn't realize that was relevant.

Does that seem like it fits?  Maybe negative numbers aren't allowed?

**Comment by adamgayoso** [comment]
yes exactly, at least in the SCVI model you need to use the count data. scGen should support normalized data

**Comment by jlehrer1** [comment]
So to confirm, having negative numbers in the scaled expression matrix causes this error correct? Is there a way to use scVI with scaled data? I have a dataset that is scaled and has some small, but negative, values.
