### ISSUE TITLE
what model to use when integrating batches of scRNA-seq matrices containing >150,000 T and innate lymphoid cell (ILC) sub-populations

### ISSUE THREAD

**Issue by MingwuDuan** [scverse/scvi-tools#1539]
Hi team and everyone,
Many thanks for developing such a great tool! I have already identified >150,000 pan-T and pan-ILC cells from >200 gene expression matrices of total >15 publicly available human scRNA-seq datasets, next I will re-cluster and interrogate them. I have also screened published scRNA-seq work which were akin to my downstream analysis scenario and list a few below :

> Cheng et al., 2021, Cell 184, 792–809  __________________________>130,000  ______myeloid cells _______diverse datasets _______integrating and re-clustering using scanpy+scanorama

> Zheng et al., Science 374, 1462 (2021)  _________________________>390,000  ______T cells  ______________diverse datasets _______integrating and re-clustering using seurat+harmony (mini-clusters used)

> Zheng et al., medRxiv doi:10.1101/2021.09.17.21263540 ______>67,000 ________T cells ______________one dataset ___________integrating and re-clustering using STACAS R package

> Schnell et al., 2021, Cell 184, 6281–6298 _______________________> 84,000 _______Th17 cells __________one dataset ___________integrating and re-clustering using seurat+sctransform

As known, T cells and ILCs are populations with **_obvious transcriptional shift continuity_**, which is also demonstrated among various sub-T populations. Since a strong technical batch effect (droplet-based and plate-based; 5-tag, 3-tag and full-length; various sequencing depth and saturation) in my present data and the abovementioned remarkable transcriptional profiles continuity exist, mnnCorrect algorithm and other derivatives (e.g. bbknn used in scanpy, Polański et al., Bioinformatics 2021,36(3) 964–965), which require that the differences between the same cell type across batches caused by batch effects should be less than the differences between cells of different types within a batch, could be unsuitable for downstream integration pipeline. Additionally, CCA-plus-anchors-based integration used in Seurat may lead to overcorrection and large computing resource consumption, though STACAS R package may resolve overcorrection issue caused by Seurat in certain degree. Can the powerful scvi-tools give me a better solution? If so, what models should I use for data integration?

**Comment by adamgayoso** [comment]
Hi @MingwuDuan 

we appreciate these types of usage questions on our discourse forum (https://discourse.scverse.org/). Would you be able to move the question over there? This helps us track code-related issues and usage-related issues better.

**Comment by MingwuDuan** [comment]
> Hi @MingwuDuan
> 
> we appreciate these types of usage questions on our discourse forum (https://discourse.scverse.org/). Would you be able to move the question over there? This helps us track code-related issues and usage-related issues better.

Sorry for misplacing this topic and I have re-created one on the forum.

**Comment by adamgayoso** [comment]
Thanks!
