### ISSUE TITLE
Cannot find class method setup_anndata

### ISSUE THREAD

**Issue by michalmark** [scverse/scvi-tools#1543]
Cannot run the scvi.model.SCVI.setup_anndata,
Although other SCV functions are executable 

```python
scvi.model.SCVI.setup_anndata 
```

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 scvi.model.SCVI.setup_anndata

AttributeError: type object 'SCVI' has no attribute 'setup_anndata'
```

#### Versions:

> 0.8.1

![image](https://user-images.githubusercontent.com/103484145/169327083-72f3c35a-665e-4f5f-b916-a108d04c19aa.png)

**Comment by cane11** [comment]
In 0.8.1 this function is not available. Please update scvi to a more recent version (>0.14.0 will work). If for any reason you want to stick to 0.8.1, you can find documentation here: https://docs.scvi-tools.org/en/0.8.0/user_guide/notebooks/data_loading.html.
Closing for now.
