### ISSUE TITLE
`AttributeError: module 'scvi.data' has no attribute 'setup_anndata'` when following atlas-level integration tutorial

### ISSUE THREAD

**Issue by jlehrer1** [scverse/scvi-tools#1544]
I am following the documentation for atlas level label transfer as found [here](https://docs.scvi-tools.org/en/0.10.0/user_guide/notebooks/harmonization.html). When following precisely the same code structure, I get the error.

```
scvi.data.setup_anndata(
    adata,
    layer="counts",
    batch_key="batch",
    labels_key="celltype_scanvi",
)
 >>> AttributeError: module 'scvi.data' has no attribute 'setup_anndata'
```

#### Versions:

> '0.16.2'

**Comment by adamgayoso** [comment]
Where did you get that link? The correct one is:

https://docs.scvi-tools.org/en/stable/tutorials/notebooks/harmonization.html

As you can see in the URL of the one you sent there is 0.10.0, indicating this is the documentation for v0.10.0

**Comment by jlehrer1** [comment]
Thank you! I simply googled "scvi label transfer", and clicked the very first result which brought me to the page I linked initially.
