### ISSUE TITLE
scANVI classification uncertainty extraction method

### ISSUE THREAD

**Issue by LuckyMD** [scverse/scvi-tools#1545]
It would be very useful to have some quantification of model uncertainty for the scANVI cell type classification output. In the simplest form this could be the softmax output from the penultimate layer. Ideally, it would be a separately trained linear activation function output as softmax will probably exaggerate the differences in uncertainties leading to poor calibration. The simple output would already be useful I think.

**Comment by PierreBoyeau** [comment]
@NathanAzol, this sounds like a relevant task to include. Can you take care of it?

**Comment by PierreBoyeau** [comment]
Hi, it sounds like [this](https://github.com/scverse/scvi-tools/blob/cc38acc8d72d1b03ef3592cb1699114dcd040438/scvi/model/_scanvi.py#L259) already returns the softmax outputs.

**Comment by martinkim0** [comment]
With the fixed scANVI released with v1.1, we are seeing better calibration performance in the classifier.
