### ISSUE TITLE
Unable to import scArches:  cannot import name 'settings' from 'scvi'

### ISSUE THREAD

**Issue by Mari123i** [scverse/scvi-tools#1561]
I try to import scarches and installed scvi-tools as a dependency manually. I get the following error: 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [45], in <cell line: 4>()
      2 import anndata
      3 import torch
----> 4 import scarches as sca
      5 import matplotlib.pyplot as plt
      6 import numpy as np

File ~\anaconda3\lib\site-packages\scarches\__init__.py:1, in <module>
----> 1 from . import dataset, metrics, trainers, models, zenodo, plotting, utils
      3 __author__ = ', '.join([
      4     'Marco Wagenstetter',
      5     'Mohsen Naghipourfar',
      6     'Mohammad Lotfollahi',
      7     'Sergei Rybakov'
      8 ])
     10 __email__ = ', '.join([
     11     'marco.wagenstetter@tum.de',
     12     'naghipourfar@ce.sharif.edu',
     13     'mohammad.lotfollahi@helmholtz-muenchen.de',
     14     'sergei.rybakov@helmholtz-muenchen.de'
     15 ])

File ~\anaconda3\lib\site-packages\scarches\models\__init__.py:8, in <module>
      6 from .scgen.vaearith_model import scgen
      7 from .expimap.expimap import expiMap
----> 8 from .expimap.expimap_model import EXPIMAP
     10 from scvi.model import SCVI, SCANVI, TOTALVI

File ~\anaconda3\lib\site-packages\scvi\model\__init__.py:2, in <module>
      1 from . import utils
----> 2 from ._amortizedlda import AmortizedLDA
      3 from ._autozi import AUTOZI
      4 from ._condscvi import CondSCVI

File ~\anaconda3\lib\site-packages\scvi\model\_amortizedlda.py:12, in <module>
      9 from anndata import AnnData
     11 from scvi._constants import REGISTRY_KEYS
---> 12 from scvi.data import AnnDataManager
     13 from scvi.data.fields import LayerField
     14 from scvi.module import AmortizedLDAPyroModule

File ~\anaconda3\lib\site-packages\scvi\data\__init__.py:3, in <module>
      1 from anndata import read_csv, read_h5ad, read_loom, read_text
----> 3 from ._datasets import (
      4     annotation_simulation,
      5     brainlarge_dataset,
      6     breast_cancer_dataset,
      7     cortex,
      8     dataset_10x,
      9     frontalcortex_dropseq,
     10     heart_cell_atlas_subsampled,
     11     mouse_ob_dataset,
     12     pbmc_dataset,
     13     pbmc_seurat_v4_cite_seq,
     14     pbmcs_10x_cite_seq,
     15     prefrontalcortex_starmap,
     16     purified_pbmc_dataset,
     17     retina,
     18     seqfish,
     19     seqfishplus,
     20     smfish,
     21     spleen_lymph_cite_seq,
     22     synthetic_iid,
     23 )
     24 from ._manager import AnnDataManager
     25 from ._preprocessing import (
     26     organize_cite_seq_10x,
     27     organize_multiome_anndatas,
     28     poisson_gene_selection,
     29 )

File ~\anaconda3\lib\site-packages\scvi\data\_datasets.py:5, in <module>
      1 from typing import List, Optional
      3 import anndata
----> 5 from ._built_in_data._brain_large import _load_brainlarge_dataset
      6 from ._built_in_data._cite_seq import (
      7     _load_pbmc_seurat_v4_cite_seq,
      8     _load_pbmcs_10x_cite_seq,
      9     _load_spleen_lymph_cite_seq,
     10 )
     11 from ._built_in_data._cortex import _load_cortex

File ~\anaconda3\lib\site-packages\scvi\data\_built_in_data\_brain_large.py:9, in <module>
      6 import numpy as np
      7 import scipy.sparse as sp_sparse
----> 9 from scvi.data._download import _download
     11 logger = logging.getLogger(__name__)
     14 def _load_brainlarge_dataset(
     15     save_path: str = "data/",
     16     sample_size_gene_var: int = 10000,
   (...)
     19     loading_batch_size: int = 100000,
     20 ) -> anndata.AnnData:

File ~\anaconda3\lib\site-packages\scvi\data\_download.py:8, in <module>
      4 from typing import Optional
      6 import numpy as np
----> 8 from scvi.utils import track
     10 logger = logging.getLogger(__name__)
     13 def _download(url: Optional[str], save_path: str, filename: str):

File ~\anaconda3\lib\site-packages\scvi\utils\__init__.py:3, in <module>
      1 from ._attrdict import attrdict
      2 from ._docstrings import setup_anndata_dsp
----> 3 from ._track import track
      5 __all__ = ["track", "setup_anndata_dsp", "attrdict"]

File ~\anaconda3\lib\site-packages\scvi\utils\_track.py:8, in <module>
      5 from rich.progress import track as track_base
      6 from tqdm import tqdm as tqdm_base
----> 8 from scvi import settings
      9 from scvi._compat import Literal
     12 def track(
     13     sequence: Iterable,
     14     description: str = "Working...",
   (...)
     17     **kwargs
     18 ):

ImportError: cannot import name 'settings' from 'scvi' (C:\Users\49176\anaconda3\lib\site-packages\scvi\__init__.py)

But I can call import scvi no problem.

What could be the reason? I work on Windows.

**Comment by adamgayoso** [comment]
What version of scvi-tools do you have?

**Comment by adamgayoso** [comment]
> Yes, I will but is there a quick fix for now? Maybe using scvi instead of scvi tools or some older version. It will take some time to switch for me.

You might also consider the windows subsystem for linux, which should work

**Comment by Mari123i** [comment]
> > Yes, I will but is there a quick fix for now? Maybe using scvi instead of scvi tools or some older version. It will take some time to switch for me.
> 
> You might also consider the windows subsystem for linux, which should work

What version of linux do you recommend?
