### ISSUE TITLE
Improve documentation on `batch_key` vs `categorical_covariate_keys`

### ISSUE THREAD

**Issue by justjhong** [scverse/scvi-tools#1613]
The documentation differentiating batch_key and categorical_covariate_keys currently does not clarify the difference between them well.

From chat with Allon:

1. is there a difference if I add a discrete batch ID under the batch_key or the categorical_covariate_keys arguments of setup_anndata?
2. Is the labels_key argument used in any way?

1. with the default settings the batch key and categorical covariate keys behave the same. However, if dispersion="gene-batch"  the model will learn batch-specific dispersion parameters (px_r in the codebase). Additionally if use_observed_lib_size=False the model will treat library size as a random variable and the prior distribution is set to a normal distribution with mean variance computed specific to each batch.
2. labels_key is only used if dispersion="gene-label" which learns label-specific dispersion parameters. Otherwise, it is mostly kept as a convenience for this from_scvi_model [method](https://github.com/scverse/scvi-tools/blob/master/scvi/model/_scanvi.py#L162) in scanvi. Not a great reason, but it would most likely break pipelines if removed now.

**Comment by cane11** [comment]
I think the main difference is that there is transform_batch in generating the posterior expression, while there is no transform_covariate.
In line of this, px_r doesn't support gene times other obs. I generally use it mainly when there are different technologies present. Setting batch to the technology ignores all patient batches and disables projecting to a single experimental batch while setting batch to patient_id gives higher chances of overfitting px_r (e.g. 2 technologies and 50 batches in total). One can set label to technology and use gene-label for px_r (I dislike the naming though).

**Comment by martinkim0** [comment]
closed via #2865
