### ISSUE TITLE
New defaults

### ISSUE THREAD

**Issue by watiss** [scverse/scvi-tools#1616]
- "zinb" vs "nb". Negative binomial seems more sensible of a default. Stipulation of changing will be rerunning all tutorials.
- encode_covariates=True/False. Typically we set this to True to improve mixing, but would like to check with Pierre since apparently there was a discussion about this before with Pierre and Jonas, and the conclusion was to leave it as False.

**Comment by jjhong922** [comment]
We can use the ray tune PR to test for the best hyperparameter settings once it gets in: https://github.com/scverse/scvi-tools/pull/1565
