### ISSUE TITLE
gimvi missing ?

### ISSUE THREAD

**Issue by giovp** [scverse/scvi-tools#1633]
cannot import gimVI

```python
from scvi.model import GIMVI
```

```pytb
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [26], in <cell line: 1>()
----> 1 from scvi.model import GIMVI
      2 setup_anndata(adata_sp)
      3 setup_anndata(adata_sc)

ImportError: cannot import name 'GIMVI' from 'scvi.model'
```

#### Versions:

0.17.1

**Comment by watiss** [comment]
GIMVI is an "external" model. Can you try accessing it from the `external` module using `from scvi.external import GIMVI` (example [here](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/gimvi_tutorial.html#Imputing-missing-genes-in-spatial-data-from-sequencing-data-with-gimVI)).

**Comment by giovp** [comment]
my bad, I was looking at older version of docs, really weird, sorry!
