### ISSUE TITLE
Wrong documentation on ZINB sampling

### ISSUE THREAD

**Issue by josephineyates** [scverse/scvi-tools#1644]
Dear scVI team, 
First I'd like to thank you for the great work you have done and the amazing responsiveness on git!
I realized there might be a small mistake in the documentation about the scVI ZINB sampling procedure. 

Indeed, in the `scvi.core.distributions.ZeroInflatedNegativeBinomial` documentation, it is written that when using the theta, mu parameterization, you do the following

$$ w \sim Gamma(\theta, \theta/\mu)$$

$$ x \sim Poisson(w)$$

where $\theta$ is the inverse dispersion and $\mu$ the mean. 

However, in the supplementary material of the scVI paper, in Supplementary Note 4, you write you sample from 

$$ w \sim Gamma(r, \frac{p}{1-p})$$ 

where $(p, r) = (\frac{\mu}{\theta + \mu}, \theta)$. 

This means you sample from 
$$Gamma(\theta, \frac{\frac{\mu}{\theta + \mu}}{1 - \frac{\mu}{\theta + \mu}}) = Gamma(\theta, \frac{\frac{\mu}{\theta + \mu}}{\frac{\theta}{\theta + \mu}}) = Gamma(\theta, \mu / \theta) $$

I found this to be more reasonable also empirically, as I was sampling from a ZINB using this procedure to simulate some data, and the total counts in the cell were off by a factor 10-100 when using the parameterization described in the docs, but the sampling seemed to work fine using $Gamma(\theta, \mu / \theta)$. 

In addition, it might help to be clearer in the docs as to what exactly the return of some functions are. In my specific case, I was quite confused as to what `scvi.model.SCVI.get_likelihood_parameters` returned, especially considering the dictionary returned has keys named `mean`, `dispersion`, and `dropout`, when the parameters returned are mean, inverse dispersion and logit dropout. This is obviously detail but can be quite cumbersome when one has only a superficial understanding of the generative procedure behind the model. 

I hope this helps! Thanks again for the great work.

**Comment by watiss** [comment]
In the scvi paper supp. note 4 ("Negative binomial parametrization"), we have:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/4193454/185981412-e35ae556-724c-4694-babc-4e4e3c25989b.png">

There are two possible parameterizations for the Gamma distribution (see [here](https://en.wikipedia.org/wiki/Gamma_distribution)). We use the alpha/beta parametrization in scvi-tools, where the first parameter (alpha) is the shape and the second (beta) is the rate (which is the **inverse** of the scale). To conform to the scvi paper supp. note 4, this means we sample from Gamma(theta, (1-p)/p) which simplifies down to to Gamma(theta, theta/mu) which is what we have in the scvi code and in the scvi documentation. 

Does that make sense? I think the trick here is the rate vs scale difference (one is the inverse of the other).

**Comment by josephineyates** [comment]
Thanks for the quick response! You are right, my bad! I am used to the shape/scale parameterization and missed the little arrow with "rate" in the scvi-tools documentation.
