### ISSUE TITLE
Clarification on the format of input data

### ISSUE THREAD

**Issue by sshen82** [scverse/scvi-tools#1652]
Hi,
Thank you for this awesome software! I am recently exploring peakVI. One thing came to my mind and I wish to clarify this with you. I am aware that the input data is AnnData format, and it is a sparse matrix. My question is: is this constantly a sparse matrix even when it is processed and inputted into the neural network and outputted from the decoder?

Yours sincerely,
Siqi Shen

**Comment by watiss** [comment]
No. We convert it into dense data before passing it into the network (see [AnnTorchDataset](https://docs.scvi-tools.org/en/stable/_modules/scvi/dataloaders/_anntorchdataset.html#AnnTorchDataset) for the source code).
The output of the networks is a matrix of distribution parameters estimated by the network. It is not sparse.

**Comment by adamgayoso** [comment]
Just to add to what Valeh said, only minibatches of data are dense, so not all the data at once is made dense.
