### ISSUE TITLE
Simplified scANVI

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scvi-tools#1669]
Right now, scANVI uses a complex hierarchy of latent variables. The first layer removes batch effects and the second layer removes label effects.

A simpler alternative would add a simple linear classifier head off of the primary scVI latent. This classifier would be co-trained with the rest of the model on the subset of the dataset that is labeled. For this we can use our existing infrastructure for semi-supervised data loading (a collection of minibatches, one from the full dataset without labels and another from just the labeled portion).

A longer term milestone would be to add an abstraction that allows adding this kind of classifier head to any model. In the short term we can add this simpler version of scANVI in `SCANVAE`. 

Once the simpler version is added we should evaluate performance to make sure we see no regression.

**Comment by martinkim0** [comment]
Closes via #2063
