### ISSUE TITLE
`get_latent_library_size` produces an error for trained SCVI model

### ISSUE THREAD

**Issue by sjfleming** [scverse/scvi-tools#1677]
Training an scVI model `vae`, as in
```python
vae = scvi.model.SCVI(adata)
vae.train()
```
(which runs successfully)
and then calling 
```python
vae.get_latent_library_size()
```
results in 
```pytb
File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/scvi/model/base/_rnamixin.py", line 567, in get_latent_library_size
"The module for this model does not compute the posterior distribution "
RuntimeError: The module for this model does not compute the posterior distribution for the library size. Set `give_mean` to False to use the observed library size instead.
```

My expectation:
Based on the docstring for the function `scvi.model.base._rnamixin.get_latent_library_size`, I see that 
```
This is denoted as :math:`\ell_n` in the scVI paper.
```
thus I would expect this parameter to be computable from a trained scVI model.  Calling `vae.get_latent_library_size()` for an scVI model worked without error in version 0.11.0 but no longer works in version 0.17.3

#### Versions:

> 0.17.3

**Comment by adamgayoso** [comment]
I believe since version 0.8 (would have to double check) we have been using the observed library size in the model by default, so this runtime error is correct.

You can treat the library size as random as well using an option in the init of the model, or you can provide your own size factor to `setup_anndata`, otherwise it uses `x.sum(1)`

**Comment by sjfleming** [comment]
Ah, okay, very cool!  Thank you @adamgayoso !
