### ISSUE TITLE
Outdated link to the breast cancer dataset

### ISSUE THREAD

**Issue by pawel-czyz** [scverse/scvi-tools#1707]
It seems that the link to the breast cancer dataset, one of the [built-in datasets](https://docs.scvi-tools.org/en/stable/api/reference/scvi.data.breast_cancer_dataset.html), has changed. 

```python
import scvi
adata = scvi.data.breast_cancer_dataset()
```

```pytb
FileNotFoundError: Found file with no content at http://www.spatialtranscriptomicsresearch.org/wp-content/uploads/2016/07/Layer2_BC_count_matrix-1.tsv. This is possibly a directory rather than a file path.
```

#### Versions:

> 0.17.4

**Comment by adamgayoso** [comment]
Thanks for letting us know, we will likely remove this function from the codebase.
