### ISSUE TITLE
Documentation for GPU support

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tools#1734]
We should add documentation regarding how to properly install PyTorch and Jax versions that work with user GPUs.

**Comment by adamgayoso** [comment]
On our computers the following works

```
mamba install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
mamba install -c conda-forge cudatoolkit-dev
mamba install jax jaxlib cuda-nvcc=11.7 -c conda-forge -c nvidia
```

though it should also make certain things faster downstream if the first command is `mamba install -c conda-forge scanpy`

**Comment by adamgayoso** [comment]
With cuda 11.8 installed globally on the system, the following works:

```
mamba install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch
mamba install jax jaxlib cuda-nvcc -c conda-forge -c nvidia
```

**Comment by adamgayoso** [comment]
We can also add this https://github.com/scverse/scvi-tools/issues/1755#issuecomment-1284473173
