### ISSUE TITLE
Problem when installing newest version of scvi-tools on Windows

### ISSUE THREAD

**Issue by Hongzhe12345** [scverse/scvi-tools#1755]
Hi, I have encountered a problem when I tried to upgrade scvi-tools to 0.16, the error message says there are conflicts among scvi-tools, jax and flax. But I have never installed jax and flax in my environment also no idea what they are. Is there any workaround?

```python
pip install scvi-tools==0.16.3
```

```ERROR: Cannot install scvi-tools and scvi-tools==0.16.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    scvi-tools 0.16.3 depends on jax>=0.3
    flax 0.6.1 depends on jax>=0.3.16
    scvi-tools 0.16.3 depends on jax>=0.3
    flax 0.6.0 depends on jax>=0.3.16
    scvi-tools 0.16.3 depends on jax>=0.3
    flax 0.5.3 depends on jax>=0.3.2
    scvi-tools 0.16.3 depends on jax>=0.3
    flax 0.5.2 depends on jax>=0.3.2
    scvi-tools 0.16.3 depends on jax>=0.3
    flax 0.5.1 depends on jax>=0.3.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

[Paste the error output produced by the above code here]
```

#### Versions:

> VERSION

![image](https://user-images.githubusercontent.com/115084467/196774048-7a5edf8e-229a-4425-bd8a-bb0546bd1955.png)

**Comment by adamgayoso** [comment]
Can you try upgrading to the latest scvi tools?

`pip install scvi-tools==0.18.0` or `conda install -c conda-forge scvi-tools=0.18.0`

**Comment by Hongzhe12345** [comment]
> Can you try upgrading to the latest scvi tools?
> 
> `pip install scvi-tools==0.18.0` or `conda install -c conda-forge scvi-tools=0.18.0`

Thank you so much for the prompt reply. For conda command it returned this 
![image](https://user-images.githubusercontent.com/115084467/196779638-7fcd7f7a-c563-4662-803a-cf383cc94b6c.png)

and for pip command it returned this:
![image](https://user-images.githubusercontent.com/115084467/196779765-f0d4dcb3-53b0-4f56-9ac3-82090325f30f.png)

**Comment by adamgayoso** [comment]
Ah I see, so you're on windows.

Can you first try

`pip install "jax[cpu]===0.3.14" -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver`

in your environment, and then install scvi-tools?

**Comment by Hongzhe12345** [comment]
> Ah I see, so you're on windows.
> 
> Can you first try
> 
> `pip install "jax[cpu]===0.3.14" -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver`
> 
> in your environment, and then install scvi-tools?

It totally worked. Thank you so much, you are my lifesaver :)

**Comment by adamgayoso** [comment]
I'm reopening this so we can add these instructions to the installation guide
