### ISSUE TITLE
`required_rngs` should have a `("params",)` default return value

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scvi-tools#1760]

**Comment by justjhong** [comment]
Could you clarify? It is already an abstract property

**Comment by adamgayoso** [comment]
Ah I see, but maybe we should change the return value from an empty tuple to `("params")`?

https://github.com/scverse/scvi-tools/blob/0c3808e857bfb7be429117ebf61ee0fcf792c718/scvi/module/base/_base_module.py#L567

**Comment by justjhong** [comment]
yea good idea 👍
