### ISSUE TITLE
Allow custom train/test/val splits

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scvi-tools#1765]
Right now we split the data randomly be a user specified proportion. We should provide api access to allow any custom splits.

A workaround right now is to train on a custom anndata and set train size to 1.0, and then use the fact that most model methods allow the ability to process held out anndatas.

E.g.,

```python
vae = scvi.model.SCVI(train_adata)
vae.train(train_size=1.0)
vae.get_elbo(test_adata)
```

however, you can't leverage things like early stopping this way.

**Comment by ori-kron-wis** [comment]
Because we will give the user a wildcard option to insert its own set of train/valid/test indices, coming from whatever logic he wanted (for example any of the sklearn splitting techniques), I don't think this issue require actual code fix
