### ISSUE TITLE
Update contributing guide in docs

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tools#1768]
- [ ] Update outdated links and references
- [ ] Add guide for installing GPU-supported PyTorch and Jax #1734 
- [ ] Add Jax installation for Windows #1755 

Should we also remove instructions for `virtualenv` and just stick with `conda`/`mamba` instead? @adamgayoso

**Comment by adamgayoso** [comment]
we should probably just ditch poetry and use the same system as the scverse cookiecutter instance, which simplifies things
