### ISSUE TITLE
Wrong figure of observed/predicted in scANVI

### ISSUE THREAD

**Issue by melancholy12** [scverse/scvi-tools#1800]
![image](https://user-images.githubusercontent.com/97800939/202839631-c7a7511e-411d-431b-810a-346da8fd731b.png)

**Comment by adamgayoso** [comment]
Can you please provide more detail of what's going on here? I reproduced the original tutorial and get the same results as in the tutorial

**Comment by melancholy12** [comment]
Do we need to provide our observed cell_type? In this matrix, it will compare the observed with predicted.
But in fact, if we want to use it as the annotation transfer, the observed cell_type should be "unknown". I think that is why the matrix look like this.
