### ISSUE TITLE
SpatialStereoscope.setup_anndata ignores layer key

### ISSUE THREAD

**Issue by cane11** [scverse/scvi-tools#1803]
Setting layer key in SpatialStereoscope.setup_anndata is without effect. I can't see an obvious bug there. It correctly checks for count data and then ignores the layer_key.
Reproducible in the Colab tutorial by setting:

<img width="1388" alt="Bildschirmfoto 2022-11-22 um 10 10 56" src="https://user-images.githubusercontent.com/9596415/203389838-1e25be31-be09-4c4e-9949-719bce4a1969.png">

**Comment by adamgayoso** [comment]
I think what might be happening is that the pre trained model was trained without a layer?

You can use view_setup_args on the pretrained model directory to check

**Comment by cane11** [comment]
I found the "problem". In disagreement with how we handle it in destVI line 233 in stereoscope/_model.py calls the setup_anndata method again.
So, we don't need the setup_anndata in the tutorial (redundant and confusing as this setup is overwritten in the next line) or we need to remove this line in the stereoscope code for consistency with destVI. What do you prefer?

**Comment by adamgayoso** [comment]
let's deprecate the call to setup anndata in stereoscope and then we can remove it, so it matches destvi
