### ISSUE TITLE
Unable to install scvi-tools

### ISSUE THREAD

**Issue by Saini-Amulya** [scverse/scvi-tools#1807]
I am unable to install scvi. I keep getting this error.

INFO: pip is looking at multiple versions of h5py to determine which version is compatible with other requirements. This could take a while.
Collecting h5py>=2.9.0
  Using cached h5py-3.6.0-cp310-cp310-win_amd64.whl (2.8 MB)
  Using cached h5py-3.5.0.tar.gz (384 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [229 lines of output]
      Collecting Cython>=0.29.15
        Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [202 lines of output]
        setup.py:67: RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.10.
          warnings.warn(
        Running from numpy source directory.
        setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
          run_build = parse_setuppy_commands()
        Processing numpy/random\_bounded_integers.pxd.in
        Processing numpy/random\bit_generator.pyx
        Processing numpy/random\mtrand.pyx
        Processing numpy/random\_bounded_integers.pyx.in
        Processing numpy/random\_common.pyx
        Processing numpy/random\_generator.pyx
        Processing numpy/random\_mt19937.pyx
        Processing numpy/random\_pcg64.pyx
        Processing numpy/random\_philox.pyx
        Processing numpy/random\_sfc64.pyx
        Cythonizing sources
        blas_opt_info:
        blas_mkl_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries mkl_rt not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        blis_info:
          libraries blis not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        openblas_info:
          libraries openblas not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
        customize GnuFCompiler
        Could not locate executable g77
        Could not locate executable f77
        customize IntelVisualFCompiler
        Could not locate executable ifort
        Could not locate executable ifl
        customize AbsoftFCompiler
        Could not locate executable f90
        customize CompaqVisualFCompiler
        Could not locate executable DF
        customize IntelItaniumVisualFCompiler
        Could not locate executable efl
        customize Gnu95FCompiler
        Could not locate executable gfortran
        Could not locate executable f95
        customize G95FCompiler
        Could not locate executable g95
        customize IntelEM64VisualFCompiler
        customize IntelEM64TFCompiler
        Could not locate executable efort
        Could not locate executable efc
        customize PGroupFlangCompiler
        Could not locate executable flang
        don't know how to compile Fortran code on platform 'nt'
          NOT AVAILABLE

        atlas_3_10_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries tatlas not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        atlas_3_10_blas_info:
          libraries satlas not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        atlas_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        atlas_blas_info:
          libraries f77blas,cblas,atlas not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        accelerate_info:
          NOT AVAILABLE

        C:\Users\saini\AppData\Local\Temp\pip-install-20erh8p2\numpy_e64eca08a5f84dd893a74cca49aaa801\numpy\distutils\system_info.py:1914: UserWarning:
            Optimized (vendor) Blas libraries are not found.
            Falls back to netlib Blas library which has worse performance.
            A better performance should be easily gained by switching
            Blas library.
          if self._calc_info(blas):
        blas_info:
          libraries blas not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        C:\Users\saini\AppData\Local\Temp\pip-install-20erh8p2\numpy_e64eca08a5f84dd893a74cca49aaa801\numpy\distutils\system_info.py:1914: UserWarning:
            Blas (http://www.netlib.org/blas/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [blas]) or by setting
            the BLAS environment variable.
          if self._calc_info(blas):
        blas_src_info:
          NOT AVAILABLE

        C:\Users\saini\AppData\Local\Temp\pip-install-20erh8p2\numpy_e64eca08a5f84dd893a74cca49aaa801\numpy\distutils\system_info.py:1914: UserWarning:
            Blas (http://www.netlib.org/blas/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [blas_src]) or by setting
            the BLAS_SRC environment variable.
          if self._calc_info(blas):
          NOT AVAILABLE

        non-existing path in 'numpy\\distutils': 'site.cfg'
        lapack_opt_info:
        lapack_mkl_info:
          libraries mkl_rt not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        openblas_lapack_info:
          libraries openblas not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        openblas_clapack_info:
          libraries openblas,lapack not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        flame_info:
          libraries flame not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        atlas_3_10_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\lib
          libraries tatlas,tatlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\lib
          libraries lapack_atlas not found in C:\
          libraries tatlas,tatlas not found in C:\
          libraries lapack_atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\libs
          libraries tatlas,tatlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\libs
        <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
          NOT AVAILABLE

        atlas_3_10_info:
          libraries lapack_atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\lib
          libraries satlas,satlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\lib
          libraries lapack_atlas not found in C:\
          libraries satlas,satlas not found in C:\
          libraries lapack_atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\libs
          libraries satlas,satlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\libs
        <class 'numpy.distutils.system_info.atlas_3_10_info'>
          NOT AVAILABLE

        atlas_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\lib
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\lib
          libraries lapack_atlas not found in C:\
          libraries ptf77blas,ptcblas,atlas not found in C:\
          libraries lapack_atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\libs
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\libs
        <class 'numpy.distutils.system_info.atlas_threads_info'>
          NOT AVAILABLE

        atlas_info:
          libraries lapack_atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\lib
          libraries f77blas,cblas,atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\lib
          libraries lapack_atlas not found in C:\
          libraries f77blas,cblas,atlas not found in C:\
          libraries lapack_atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\libs
          libraries f77blas,cblas,atlas not found in C:\Users\saini\AppData\Local\Programs\Python\Python310\libs
        <class 'numpy.distutils.system_info.atlas_info'>
          NOT AVAILABLE

        lapack_info:
          libraries lapack not found in ['C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\saini\\AppData\\Local\\Programs\\Python\\Python310\\libs']
          NOT AVAILABLE

        C:\Users\saini\AppData\Local\Temp\pip-install-20erh8p2\numpy_e64eca08a5f84dd893a74cca49aaa801\numpy\distutils\system_info.py:1748: UserWarning:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
        lapack_src_info:
          NOT AVAILABLE

        C:\Users\saini\AppData\Local\Temp\pip-install-20erh8p2\numpy_e64eca08a5f84dd893a74cca49aaa801\numpy\distutils\system_info.py:1748: UserWarning:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
          NOT AVAILABLE

        numpy_linalg_lapack_lite:
          FOUND:
            language = c
            define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

        C:\Users\saini\AppData\Local\Temp\pip-build-env-e10jb3xc\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
          warnings.warn(msg)
        running dist_info
        running build_src
        build_src
        building py_modules sources
        creating build
        creating build\src.win-amd64-3.10
        creating build\src.win-amd64-3.10\numpy
        creating build\src.win-amd64-3.10\numpy\distutils
        building library "npymath" sources
        error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by adamgayoso** [comment]
It looks like you're on windows. Please follow our installation guidance for [windows](https://docs.scvi-tools.org/en/stable/installation.html#windows-prerequisites).

It is recommended to do all installation in conda environments. If you continue to have issues, please feel free to create new posts on our [forum](https://discourse.scverse.org/)
