### ISSUE TITLE
Struggling to install scvi-tools on Mac M1

### ISSUE THREAD

**Issue by das2000sidd** [scverse/scvi-tools#1811]
Hi,
I was wondering if somebody here has experience with installing scvi-tools on a Mac with M1 chip. I tried the following command:

conda install scvi-tools -c conda-forge
But got the following error:

Collecting package metadata (current_repodata.json): failed
CondaSSLError: OpenSSL appears to be unavailable on this machine. OpenSSL is required to
download and install packages.
Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/osx-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

Then I tried to install OpenSSL with following command:
conda install -c anaconda openssl 
.....and I got the exact same error as the conda install scvi-tools -c conda-forge command.

I do not understand why collection of metadata is failing for openssl. Any inputs would be highly helpful.
Thanks!

**Comment by adamgayoso** [comment]
Can you ensure that you installed a version of conda that is native for mac m1?

scvi-tools will not work with python interpreted with rosetta.


<img width="861" alt="Screenshot 2022-11-30 at 1 37 48 PM" src="https://user-images.githubusercontent.com/10859440/204913513-455e5213-6953-4f23-ad05-620a67715661.png">

**Comment by das2000sidd** [comment]
Worked perfectly with the suggestion you gave about installing version of conda native for mac m1. Thanks again!

**Comment by adamgayoso** [comment]
Great!
