### ISSUE TITLE
About unstable result

### ISSUE THREAD

**Issue by GwangWooKim** [scverse/scvi-tools#1881]
Hello, I'm going to analyze the single-cell RNA sequencing data using the scVI framework.
After training the scVI model, I found that the result of model.differential_expression is unstable (specifically, it varies from seed to seed).
I've been trying to solve this problem, but I still haven't.
Please tell me the expected cause.
Thank you in advance.

**Comment by adamgayoso** [comment]
Hello,

Thank you for using scvi-tools. For this kind of discussion, we ask that users submit questions to our forum (https://discourse.scverse.org/) so that we can use github for development-related issues.

Thanks!

**Comment by GwangWooKim** [comment]
Ok. I will. Thanks!
