### ISSUE TITLE
Dimensionality reduction issue in Peak VI under 0.20

### ISSUE THREAD

**Issue by jtls0n** [scverse/scvi-tools#1912]
Thank you for your effort on these tools.

We have been testing PeakVI for our application and had some promsing results with it under scvi-tools 0.19

We were intrigued to try the batch correction and integration features in scBasset so we upgraded to 0.20. 

We have been unable to recapitulate our previously successful analyses in 0.20 with both our own data and with PBMC data in the tutorial.

The intial issue seems to be the output of dimensionality reduction in 0.20

```python
import scvi
import anndata
import scipy
import numpy as np
import pandas as pd
import scanpy as sc
import matplotlib.pyplot as plt

scvi.settings.seed = 2023

sc.set_figure_params(figsize=(4, 4), frameon=True)

%config InlineBackend.print_figure_kwargs={'facecolor' : "w"}
%config InlineBackend.figure_format='retina'

# reproducible version using 10x sample data
!wget https://cf.10xgenomics.com/samples/cell-atac/1.2.0/atac_pbmc_5k_nextgem/atac_pbmc_5k_nextgem_filtered_peak_bc_matrix.tar.gz
!tar -xvf atac_pbmc_5k_nextgem_filtered_peak_bc_matrix.tar.gz

# use read_10x to load data
adata = scvi.data.read_10x_atac("filtered_peak_bc_matrix")

# input shape
print(adata.shape)

# compute the threshold: 5% of the cells
min_cells = int(adata.shape[0] * 0.05)

# in-place filtering of regions
sc.pp.filter_genes(adata, min_cells=min_cells)

# filtered shape
print(adata.shape)

# setup anndata object pre-training
scvi.model.PEAKVI.setup_anndata(adata)

# train
pvi = scvi.model.PEAKVI(adata)
pvi.train()

latent = pvi.get_latent_representation()
adata.obsm["X_PeakVI"] = latent

# compute the k-nearest-neighbor graph that is used in both clustering and umap algorithms
sc.pp.neighbors(adata, use_rep="X_PeakVI")

# compute the umap
sc.tl.umap(adata, min_dist=0.2,spread=0.8)

# cluster the space (we use a lower resolution to get fewer clusters than the default)
sc.tl.leiden(adata, key_added="cluster_pvi", resolution=0.22)

#print umap
sc.pl.umap(adata, color='cluster_pvi',add_outline=True,size=40)
```

#### Versions:

> VERSION

This is output of the same code with an environment using 0.19 or 0.20.

![image](https://user-images.githubusercontent.com/125699295/220117320-1c429c9e-7f80-46bb-a3ca-e8b4d08c261f.png)

Thank you!

**Comment by adamgayoso** [comment]
Thank you for sharing this. I've identified that it's an issue with our [`SaveBestState`](https://docs.scvi-tools.org/en/stable/api/reference/scvi.train.SaveBestState.html#scvi.train.SaveBestState) callback.

For now you can add `save_best=False` to the train method of peakvi, but we will try to patch this asap.

**Comment by jtls0n** [comment]
save_best=False worked in our existing environment. 
![image](https://user-images.githubusercontent.com/125699295/220208788-c10557c0-8075-4c72-a9f2-0c7d17a31562.png)

I haven't tried to apply the fix yet, but will try to verify. We really appreciate the fix.

Thanks again for the really useful tools.

**Comment by jtls0n** [comment]
rebuilt environment with 0.20.x worked as well. Thanks again!
