### ISSUE TITLE
scVI integration and highly variable genes selection

### ISSUE THREAD

**Issue by pmarzano97** [scverse/scvi-tools#1931]
Hello everyone!
I have a question on scanpy and the selection of the highly variable genes before the downstream integration step with scVI.

In my dataset I have two main variables: “donor” and “batch_ID”. Each donor (X, Y, Z, …) corresponds to more than one sample sequenced (Xa, Xb, Xc, …), so the variable “donor” groups more than one sample. While, instead, the “batch_ID” variable corresponds to each sample sequenced.
In the code of HVG selection, sc.pp.highly_variable_genes, there is the option to set the batch_key. Should I set the batch_key equal to “batch_ID” or to “donor”?

Another question, should I use the same variable of HVG selection as the one on which I perform the batch correction for the integration? I mean, if I decide to select the HVGs on the “donor” instead of on “batch_ID”, should I set the batch correction in the modeling of the training on “donor” as well? Or the selection of HVGs is independent from the choice of the variable to correct the batch for the integration?

And last one, if I want to make a subset of clusters to focus the analysis on specific type of cells (like, starting from total PBMCs, I want to focus on myeloid cells == adata_reduced), should I recalculate the HVGs and perform again the training of the adata_reduced? If yes, the batch_key in the HVG code on adata_reduced should be the same as the one chosen for the adata?

Thanks so much!!
Paolo

**Comment by adamgayoso** [comment]
Hi Paolo,

Thank you for the question. Do you mind asking on our [forum](https://discourse.scverse.org/). We reserve github issues for development related content. Thanks!
