### ISSUE TITLE
in scvi.model.utils.mde - expose the embedding_dim of the undelying mds function call?

### ISSUE THREAD

**Issue by stela2502** [scverse/scvi-tools#1943]
Hi, we have developed a VR application to analyse single cell data and are frequently using this to compare 3D dimension reduction outcomes. I would love to compare harmony results with the results I get from scvi.model.SCVI. But then 3D is more informative than 2D and it is not as comfortable to work  with 2D in a 3D application.

I have - now that I looked into your implementation - seen that I can also use a embedding_dim=3 in the function call. Could you be so kind and add that into your documentation? That would likely make the live of some bioinformaticians more comfortable.
Thank you!

**Comment by adamgayoso** [comment]
I fixed the documentation so that on the website it hyperlinks out to the pymde website function reference, which should make it easier to set kwargs.
