### ISSUE TITLE
when i import scvi i get this error

### ISSUE THREAD

**Issue by irfan11223344** [scverse/scvi-tools#1972]
when i import scvi i got this result, i install scvi through this code !pip install scvi-tools and I import it through import scvi

```python
# Your code here
```

 1 import scvi

~\anaconda3\lib\site-packages\scvi\__init__.py in <module>
      5 
      6 from ._constants import _CONSTANTS
----> 7 from ._settings import settings
      8 
      9 # this import needs to come after prior imports to prevent circular import

~\anaconda3\lib\site-packages\scvi\_settings.py in <module>
      3 from typing import Union
      4 
----> 5 import pytorch_lightning as pl
      6 import torch
      7 from rich.console import Console

~\anaconda3\lib\site-packages\pytorch_lightning\__init__.py in <module>
     18 _PROJECT_ROOT = os.path.dirname(_PACKAGE_ROOT)
     19 
---> 20 from pytorch_lightning import metrics  # noqa: E402
     21 from pytorch_lightning.callbacks import Callback  # noqa: E402
     22 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402

~\anaconda3\lib\site-packages\pytorch_lightning\metrics\__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from pytorch_lightning.metrics.classification import (  # noqa: F401
     16     Accuracy,
     17     AUC,

~\anaconda3\lib\site-packages\pytorch_lightning\metrics\classification\__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
     15 from pytorch_lightning.metrics.classification.auc import AUC  # noqa: F401
     16 from pytorch_lightning.metrics.classification.auroc import AUROC  # noqa: F401

~\anaconda3\lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py in <module>
     16 from torchmetrics import Accuracy as _Accuracy
     17 
---> 18 from pytorch_lightning.metrics.utils import deprecated_metrics
     19 
     20 

~\anaconda3\lib\site-packages\pytorch_lightning\metrics\utils.py in <module>
     20 from torchmetrics.utilities.data import dim_zero_mean as _dim_zero_mean
     21 from torchmetrics.utilities.data import dim_zero_sum as _dim_zero_sum
---> 22 from torchmetrics.utilities.data import get_num_classes as _get_num_classes
     23 from torchmetrics.utilities.data import select_topk as _select_topk
     24 from torchmetrics.utilities.data import to_categorical as _to_categorical

ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (C:\Users\IRFAN\anaconda3\lib\site-packages\torchmetrics\utilities\data.py)

adata

```pytb
[Paste the error output produced by the above code here]
```

#### Versions:

> VERSION
Python 3.9.13

**Comment by Pedramto89** [comment]
I am trying to import scvi too, but I get an error:
Just I want to mention that I installed the scvi tools by !pip install on a new environment on Anaconda on Mac M1.
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[13], line 1
----> 1 import scvi

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/scvi/__init__.py:10
      7 from ._settings import settings
      9 # this import needs to come after prior imports to prevent circular import
---> 10 from . import autotune, data, model, external, utils
     12 from importlib.metadata import version
     14 package_name = "scvi-tools"

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/scvi/autotune/__init__.py:1
----> 1 from ._manager import TuneAnalysis, TunerManager
      2 from ._tuner import ModelTuner
      3 from ._types import Tunable, TunableMixin

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/scvi/autotune/_manager.py:10
      7 from typing import Any, Callable, List, Optional, Tuple
      9 import rich
---> 10 from chex import dataclass
     12 try:
     13     import ray

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/chex/__init__.py:17
      1 # Copyright 2020 DeepMind Technologies Limited. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Chex: Testing made fun, in JAX!"""
---> 17 from chex._src.asserts import assert_axis_dimension
     18 from chex._src.asserts import assert_axis_dimension_comparator
     19 from chex._src.asserts import assert_axis_dimension_gt

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/chex/_src/asserts.py:26
     23 import unittest
     24 from unittest import mock
---> 26 from chex._src import asserts_internal as _ai
     27 from chex._src import pytypes
     28 import jax

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/chex/_src/asserts_internal.py:34
     31 from typing import Any, Sequence, Union, Callable, Optional, Set, Tuple, Type
     33 from absl import logging
---> 34 from chex._src import pytypes
     35 import jax
     36 from jax.experimental import checkify

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/chex/_src/pytypes.py:18
     15 """Type definitions to use for type annotations."""
     17 from typing import Any, Iterable, Mapping, Union
---> 18 import jax
     19 import jax.numpy as jnp
     20 import numpy as np

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/jax/__init__.py:35
     30 del _cloud_tpu_init
     32 # Confusingly there are two things named "config": the module and the class.
     33 # We want the exported object to be the class, so we first import the module
     34 # to make sure a later import doesn't overwrite the class.
---> 35 from jax import config as _config_module
     36 del _config_module
     38 # Force early import, allowing use of `jax.core` after importing `jax`.

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/jax/config.py:17
      1 # Copyright 2018 The JAX Authors.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     14 
     15 # TODO(phawkins): fix users of this alias and delete this file.
---> 17 from jax._src.config import config

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/jax/_src/config.py:25
     22 import warnings
     23 from typing import Any, List, Callable, Hashable, NamedTuple, Iterator, Optional
---> 25 from jax._src import lib
     26 from jax._src.lib import jax_jit
     27 from jax._src.lib import transfer_guard_lib

File ~/opt/anaconda3/envs/scRNA_seq/lib/python3.9/site-packages/jax/_src/lib/__init__.py:75
     71   return _jaxlib_version
     73 version_str = jaxlib.version.__version__
     74 version = check_jaxlib_version(
---> 75   jax_version=jax.version.__version__,
     76   jaxlib_version=jaxlib.version.__version__,
     77   minimum_jaxlib_version=jax.version._minimum_jaxlib_version)
     81 # Before importing any C compiled modules from jaxlib, first import the CPU
     82 # feature guard module to verify that jaxlib was compiled in a way that only
     83 # uses instructions that are present on this machine.
     84 import jaxlib.cpu_feature_guard as cpu_feature_guard

AttributeError: partially initialized module 'jax' has no attribute 'version' (most likely due to a circular import)`

**Comment by shinohara-xiao** [comment]
Hi,  when I am running 
```
python scripts/scVI-3D.py -b 10 -c "whole" -r 1000000 -i "demoData" -o "results" -cs "supplementaryData/demoData_summary.txt" -g "supplementaryData/hg19.chrom.sizes" -br -n 100 -gpu -p 10 -pca 50 -up -tp -v
```

I got the same error:
 **ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'** 

Traceback (most recent call last):
  File "scripts/scVI-3D.py", line 22, in <module>
    import scvi
  File "/home/zhangx/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/scvi/__init__.py", line 7, in <module>
    from ._settings import settings
  File "/home/zhangx/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/scvi/_settings.py", line 5, in <module>
    import pytorch_lightning as pl
  File "/home/zhangx/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/home/zhangx/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/home/zhangx/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/home/zhangx/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics
  File "/home/zhangx/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/pytorch_lightning/metrics/utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' 

and my versions are :

* scvi-tools:  0.14.5
* pytorch_lightning:  1.3.8
* torchmetrics:  0.11.0

**Comment by irfan11223344** [comment]
>pip show scvi-tools

Name: scvi-tools
Version: 0.14.6
Summary: Deep probabilistic analysis of single-cell omics data.
Home-page: https://github.com/YosefLab/scvi-tools
Author: Romain Lopez
Author-email: romain_lopez@gmail.com
License: BSD-3-Clause
Location: c:\users\irfan\anaconda3\lib\site-packages
Requires: anndata, docrep, h5py, ipywidgets, numba, numpy, openpyxl, pandas, pyro-ppl, pytorch-lightning, rich, scikit-learn, setuptools, torch, torchmetrics, tqdm
Required-by: 
Note: you may need to restart the kernel to use updated packages.


my pytorch-lightning


Name: pytorch-lightning
Version: 1.3.0
Summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
Home-page: https://github.com/PyTorchLightning/pytorch-lightning
Author: William Falcon et al.
Author-email: waf2107@columbia.edu
License: Apache-2.0
Location: c:\users\irfan\anaconda3\lib\site-packages
Requires: fsspec, future, numpy, packaging, pyDeprecate, PyYAML, tensorboard, torch, torchmetrics, tqdm
Required-by: scvi-tools


and torchmetrics
Name: torchmetrics
Version: 0.11.4
Summary: PyTorch native Metrics
Home-page: https://github.com/Lightning-AI/metrics
Author: Lightning-AI et al.
Author-email: name@pytorchlightning.ai
License: Apache-2.0
Location: c:\users\irfan\anaconda3\lib\site-packages
Requires: numpy, packaging, torch
Required-by: pytorch-lightning, scvi-tools
!pip install scanpy

I still cant import scvi

**Comment by adamgayoso** [comment]
Please install the latest scvi-tools version. Version 0.20.3

**Comment by Agamart** [comment]
Dear all,
I have a similar problem when importing scvi. I installed scvi-tools on miniforge3 virtual env with arm64 architecture, Python version 3.9. After ‘import scvi’ command I get the error message:
AttributeError: module ‘anndata.compat’ has no attribute ‘Literal’
I am using the newest version of scvi-tools 0.20 (but also 0.19 and 0.18 gives the same error).

Can somebody please help me? Thank you!
