### ISSUE TITLE
Posterior probability of scVI/scANVI models

### ISSUE THREAD

**Issue by TzuTingWei** [scverse/scvi-tools#1979]
I was looking for any confidence or uncertainty measurement provided by scVI or scANVI for me to understand how reliable the prediction is, and I came across the notebook in the original scVI paper: https://github.com/chenlingantelope/HarmonizationSCANVI/blob/master/notebooks/ContinuousSymSim.ipynb.

I found that using create_posterior() in the model training and then compute_predictions(soft=True) could provide the posterior probability of each cell/label. 

So I wonder if we could have the posterior probability as part of the model output. Thank you.

**Comment by martinkim0** [comment]
Hi, apologies for the late response. 

You can access the predicted probabilities in scANVI by passing in `predict(soft=True)`. Please note that these values should not necessarily be interpreted as uncertainty estimates as the classifier is typically not well calibrated (it is confident even when incorrect).
