### ISSUE TITLE
MultiVI for trimodal integration

### ISSUE THREAD

**Issue by tt2190** [scverse/scvi-tools#1992]
Thanks so much for developing the scVI tools.

I have CITE-seq, 10x multiome and unimodal scATAC data from the corresponding tissue of multiple donors and hope to put them together and perform an integrated analysis of the trimodal (RNA, protein, ATAC) data.

I was considering [Multigate](https://github.com/theislab/multigrate) from Theis Lab, but I have just realised that MultiVI has been trying to support protein information (#1712) and [_multivi.py](https://github.com/scverse/scvi-tools/blob/main/scvi/model/_multivi.py) has been updated to accept protein input.

I would be grateful if you could enlighten me on the current recommendation regarding the use of MultiVI for this trimodal integration scenario.

**Comment by marianogabitto** [comment]
Hello tt (not sure your name),
                             is there anything that you would like to know? MultiVI works for protein information. 

Cheers,
Mariano

**Comment by tt2190** [comment]
Hi Mariano,

Thank you very much for your reply. My apologies for not being clear in my original post.

I wanted to ask if MultiVI works for trimodal integration scenarios, as the MultiVI [paper](https://www.biorxiv.org/content/10.1101/2021.08.20.457057v2) and [documentation](https://docs.scvi-tools.org/en/stable/user_guide/models/multivi.html) do not mention its applicability for protein data or for integration of three modalities.

Have you released any tutorial for trimodal integration (e.g. CITE-seq + 10x multiome)?

Many thanks,
Tomo

**Comment by marianogabitto** [comment]
Hi Tomo,
           protein information has to enter as in TotalVI, in the .obsm field of the anndata. Can you give it a try and let me know?

M

**Comment by tt2190** [comment]
Hi Mariano,

Thank you for clarifying this point. I will let you know once I get the results!

Many thanks,
Tomo

**Comment by tt2190** [comment]
Hi Mariano,

I have tried integration of CITE-seq + multiome using the datasets used in the totalVI and MultiVI tutorials:
CITE-seq: scvi.data.pbmcs_10x_cite_seq()
multiome: https://cf.10xgenomics.com/samples/cell-arc/2.0.0/pbmc_unsorted_10k/pbmc_unsorted_10k_filtered_feature_bc_matrix.tar.gz

I have specified `protein_expression_obsm_key="protein_expression"` when I setup the anndata with `scvi.model.MULTIVI.setup_anndata`. However, it seems that the protein_foreground_probability has not been computed.
Could you please give me some additional guidance on how to integrate protein information into the MultiVI workflow?

My analysis notebook is available from the following link:
https://www.dropbox.com/s/n8uzw2wfzoqnlnu/trimodal_MultiVI_test.ipynb?dl=0

I have also realised that the `organize_multiome_anndatas` function does not work when protein information is included in obsm.

Many thanks,
Tomo

**Comment by marianogabitto** [comment]
Hi Tomo,
        sorry for the delay. We are running the last edits on the manuscript and I will work on the tutorial soon. I will based it on your notebook actually ! Thanks for sharing it. 

        At a first pass, you did everything right. Let me work on the example myself and get back to you in 2 days.

Thanks,
Mariano

**Comment by tt2190** [comment]
Hi Mariano,

Thank you for your reply.

Performance-wise, as shown in my notebook, the CITE-seq and multiome data were completely separated (not integrated) after model training. This may be because I don't currently have GPU available and I tested with max_epochs=150 to save runtime on CPU, but I was also concerned if I was doing something wrong other than #epochs. Therefore, it would be very helpful if I could learn from your tutorial. 

Thank you for your time and help and I look forward to hearing from you soon!

Thanks,
Tomo

**Comment by marianogabitto** [comment]
Tomo, I will work on this and I should cite you as a reference in the tutorial for helping with this. We should connect outside this thread to make the tutorial happen !

**Comment by fimunty** [comment]
Hello there, is there an update on this issue? I see that it has been marked as completed, but I can't find the mentioned tutorial anywhere on the scvi website. Further, when trying to use `setup_multiome_anndatas` with an anndata with protein I encouter an error since the index of the protein data doesn't match the obs_names of the newly created anndata anymore.
I understand that I can work around using `setup_multiome_anndatas`, but what is the intended way of preparing data with protein expression for MultiVI?

Thank you and best,
Fiona

**Comment by canergen** [comment]
There exists no tutorial. I was suggesting how to fix it. We have an open issue to switch to MuData which would be the correct way IMO to fix this. However, there is no timeline for this. @marianogabitto Any suggestions?
