### ISSUE TITLE
Possible Bug in  NegativeBinomial()

### ISSUE THREAD

**Issue by exaibioamir** [scverse/scvi-tools#1999]
Hi, Thank you so much for this package.

The potential issue is with https://github.com/scverse/scvi-tools/blob/2779a3244a6265a3a5c7bc2f174914b684e57350/scvi/distributions/_negative_binomial.py#L564

There `gamma_d` is being calculated by `_gamma(mu, theta)`
While `_gamma` function is defined as:
```python
def _gamma(theta, mu):
    concentration = theta
    rate = theta / mu
    # Important remark: Gamma is parametrized by the rate = 1/scale!
    gamma_d = Gamma(concentration=concentration, rate=rate)
    return gamma_d
```
It looks that `mu` and `theta` are flipped in the function call

This is in the `main` branch.

**Comment by adamgayoso** [comment]
Indeed this looks like a bug, but it's restricted to `NegativeBinomialMixture` sample method, which is only used by one method of totalVI
