### ISSUE TITLE
TotalVI loss computation excluding unobserved proteins

### ISSUE THREAD

**Issue by SabrinaRichter** [scverse/scvi-tools#2008]
How sure are you about this line here?
https://github.com/scverse/scvi-tools/blob/cb17e10b2a82dc95c0c8c261e1aef7781c3b0df9/scvi/module/_totalvae.py#L315

I guess it is supposed to do normal masking, but this mask_scatter_ method is filling the nonmasked entries just with the first entries of the loss matrix not taking into account the position of the masking matrix (https://pytorch.org/docs/stable/generated/torch.Tensor.masked_scatter_.html)

If I am correct, `temp_pro_loss_full = pro_batch_mask_minibatch.bool() * full_loss` should i think work.

**Comment by adamgayoso** [comment]
Note that I reran the tutorials with the fix and the results aren't substantially different as the imputation occurs by making counterfactual abundance predictions (decoding on a batch where the protein was observed)
