### ISSUE TITLE
Un-registering an anndata object from an scvi-tools BaseModelClass model

### ISSUE THREAD

**Issue by yanwu2014** [scverse/scvi-tools#2053]
It seems like in order to create an scvi dataloader from an anndata object, that object must be "[registered](https://github.com/scverse/scvi-tools/blob/864afefa317ec6ae72fd5824d02d6bb3a19959c7/scvi/model/base/_base_model.py#L401)" with the model which then seems to create a [pointer](https://github.com/scverse/scvi-tools/blob/864afefa317ec6ae72fd5824d02d6bb3a19959c7/scvi/model/base/_base_model.py#L214) to that object in the model itself. This creates an issue for perturbational prediction models like CPA where you might want to run inference on many new datasets, which will then accumulate in memory due the pointers to all of these datasets in the model itself

Would it be possible to create an easy way to "unregister" an anndata object so that it doesn't persist in the model?

**Comment by martinkim0** [comment]
I believe you can `del adata` for any datasets you want to remove from memory to achieve a similar effect. Since the model class only stores pointers to the original AnnData object, this will mean that the full dataset won't persist in the model. Let me know if this works for you.

**Comment by justjhong** [comment]
I had this same issue a while back and had to clear the pointers occasionally. A deregister or clear manager store function should be helpful. For a clear store function you would probably want to keep around the original train adata manager pointer and dump all subsequent ones. Also, the bigger issue is this store https://github.com/scverse/scvi-tools/blob/864afefa317ec6ae72fd5824d02d6bb3a19959c7/scvi/model/base/_base_model.py#L212 which keeps around class level pointers even after the instances are deleted. This needs to be cleared appropriately as well

**Comment by yanwu2014** [comment]
Perfect thanks so much guys! And yes I've been manually deleting the pointers for now but it seems like a deregister function may be helpful

**Comment by adamgayoso** [comment]
So it sounds like we can add 

`clear_manager_from_registry(self, manager: Optional[AnndataManager] = None)` that clears everything except the current manager `self.adata_manager` by default, and a specific manager if specified.

Clearing should occur for both class and instance manager stores.

Sounds good @justjhong

**Comment by martinkim0** [comment]
Is there a scenario where the instance manager store would not be a subset of the class manager store?

**Comment by adamgayoso** [comment]
> Is there a scenario where the instance manager store would not be a subset of the class manager store?

Yes this can happen if a brand new anndata is passed to a `get_...(adata)`. You can trace through what `self._validate_adata` does

**Comment by yanwu2014** [comment]
> I had this same issue a while back and had to clear the pointers occasionally. A deregister or clear manager store function should be helpful. For a clear store function you would probably want to keep around the original train adata manager pointer and dump all subsequent ones. Also, the bigger issue is this store
> 
> https://github.com/scverse/scvi-tools/blob/864afefa317ec6ae72fd5824d02d6bb3a19959c7/scvi/model/base/_base_model.py#L212
> 
> which keeps around class level pointers even after the instances are deleted. This needs to be cleared appropriately as well

Ah I just ran into the class level issue as well, it accumulates memory when you run many different models (i.e. for hyperparameter optimization). Would be great to have a class level unregister function as well.

Out of curiosity is there a reason why the class level object needs to hang on to these pointers?

**Comment by justjhong** [comment]
The PR @martinkim0 has out will clear the class registry and make sure there is still consistency there (a class level deregister might cause issues or confusing errors if the instance level pointers are still around).

The reason is because we wanted to avoid dumping a bunch of user-unintended objects and clobbering interactions within the input AnnData. Instead we use this store to retain the same API of a class-level setup_anndata function and being able to retrieve the setup metadata later.

**Comment by yanwu2014** [comment]
Makes sense, basically somewhere to stash the anndata setup, thanks for clarifying!
