### ISSUE TITLE
lvm-DE

### ISSUE THREAD

**Issue by StanislavBratchikov** [scverse/scvi-tools#2059]
Hello!

Not sure where to put this so will put it here. 
First, I would like to thank you for the scvi tools package you have created and continue to develop. 

My question concerns the recently published lvm-DE method by your lab for noval Bayesian differential expression. In [paper](https://www.pnas.org/doi/10.1073/pnas.2209124120#abstract) you state that it should be available in betta version. However after [release](https:/github.com/scverse/scvi-tools/releases/tag/1.0.0b0) lookup I wasn’t able to locate any method that would contain the implementation of lvm-DE. As well as I couldn’t find any tutorials on how to use it. 
I would appreciate if you could tell where to find those, or when it is going to be available. 
Thank you

**Comment by PierreBoyeau** [comment]
Hello Stanislas,
We updated the following notebook to use lvm-DE [here](https://github.com/scverse/scvi-tutorials/blob/main/scVI_DE_worm.ipynb). Some default parameters may change #2064 , but you should still be able to use lvm-DE now. Let me know if you need any help!

**Comment by StanislavBratchikov** [comment]
Joseph, Thank you for bringing this up I would also be interested in finding this out. @PierreBoyeau Can you please comment on this - in what release we should find it?

**Comment by PierreBoyeau** [comment]
Hi Joseph & Stanislas, and many thanks for your interest in lvm-DE. 

Indeed, lvm-DE can already be accessed via the `differential_expression` method, and the SNIS procedure described in the paper can be used by modifying `weights`.  The other tools described in the paper (pseudo counts and automatic effect size threshold estimation) can respectively be enabled by setting a value to `pseudocounts` and by setting`delta=None` in the differential expression method.
I'm here if you have other questions!

**Comment by joseph-siefert** [comment]
Thanks Pierre. Last question, since when has lvm-DE framework been used in the `differential_expression` function? I ask because I have been using this method for the past 6 months and I need to know if the implementation has recently changed and if I need to reanalyze my previous results to remain consistent.

**Comment by PierreBoyeau** [comment]
Dear Joseph, don't worry, the current default parameters of differential expression have remained the [same](https://github.com/scverse/scvi-tools/blob/4fbd059c87dfe208fc1ed618a926d1fecd2cf07f/scvi/model/base/_rnamixin.py#L315), even after the merge of the new functionalities. You don't need to reanalyze the data :)

**Comment by rLannes** [comment]
I am sorry, but I am still very confuse.

Could you show an example, on how to access:

-  lvm-DE using model.differential_expression VS how to run the previous model.differential_expression.

It is unclear for me how to use this function, and I don't find mention of it (ctrl-f lvm return nothing) in the notebook example.

Could you please you clarify this point?

**Comment by StanislavBratchikov** [comment]
Hey, its me again :) I was running your lvm-DE method on several of our in house datasets to compare number of DE genes retrieved with its help to other tool. My question is: do I understand correctly that this method can be only used for genes that were used to fit the model (usually we integrate samples using HVG, for example 1000 of them). I am asking because it seems that I can't get more DE genes than those 1000 HVG genes used to train the model. In my mind this could be a limitation given that we want to explore all of the genes we have... Maybe I am misunderstanding something.Will be glad if you could clear this for me. Thank you !
