### ISSUE TITLE
UnsupervisedTrainingMixin.train(): default max_epochs is zero when cell count is large

### ISSUE THREAD

**Issue by bkmartinjr** [scverse/scvi-tools#2071]
The `UnsupervisedTrainingMixin.train()` method in file `_training_mixin.py` defaults the value of `max_epochs` to:

> int(np.min([round((20000 / n_cells) * 400), 400]))

When `n_cells` is large (>=16000000), this will default to zero, and the method will silently fail to train.

It seems like there should be a minimum number of epochs for the default case, or perhaps an error thrown in this corner case.

scvi version 0.20.3

**Comment by adamgayoso** [comment]
Thanks for the issue. @martinkim0 can you pull out this heuristic into a private function and set the min to 1?

**Comment by adamgayoso** [comment]
the heuristic may exist in a few places in the codebase
