### ISSUE TITLE
Deprecate multivi setup anndata

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scvi-tools#2073]
One thing we may need to consider is a util to patch loading old saves of multivi models if we remove setup anndata

**Comment by marianogabitto** [comment]
Guys, can you comment on slack what are the plans for removing the setup_anndata. I have not heard about them and even if I want to help, I am not going to be able.

**Comment by canergen** [comment]
Will be adressed with HuggingFace MultiVI. See https://github.com/scverse/scvi-tools/pull/3039 for a suggestion.
