### ISSUE TITLE
docstring for JaxSCVI has small typo in example code

### ISSUE THREAD

**Issue by bkmartinjr** [scverse/scvi-tools#2074]
The JaxSCVI docstring has an example containing a small cut & paste error.

The third line references `.SCVI(...)`, when it should read `.JaxSCVI(...)`.

Current docstring - see third line:
```
    >>> adata = anndata.read_h5ad(path_to_anndata)
    >>> scvi.model.JaxSCVI.setup_anndata(adata, batch_key="batch")
    >>> vae = scvi.model.SCVI(adata)
    >>> vae.train()
    >>> adata.obsm["X_scVI"] = vae.get_latent_representation()
```

**Comment by martinkim0** [comment]
Thanks for catching this, I'll add a fix asap!
