### ISSUE TITLE
Documentation inaccurate for SCANVI class (for unlabeled_category arg)

### ISSUE THREAD

**Issue by jnboehm** [scverse/scvi-tools#2091]
The documentation for the class `SCANVI` does not accurately reflect the `unlabeled_category` argument in the documentation for [`scvi.model.SCANVI.setup_anndata`](https://docs.scvi-tools.org/en/stable/api/reference/scvi.model.SCANVI.html#scvi.model.SCANVI.setup_anndata). It does not document the argument `unlabeled_category` (and the order of arguments in the documentation should maybe be sorted accordingly to the order in the argument list of the function).

Additionally, the docs for the `SCANVI` class do not pass the `unlabeled_category` argument to the function `setup_anndata`, which currently throws an error.  The line 
```python
scvi.model.SCANVI.setup_anndata(adata, batch_key="batch", labels_key="labels")
````

throws the following error
```pytb
TypeError                                 Traceback (most recent call last)
Cell In[14], line 1
----> 1 scvi.model.SCANVI.setup_anndata(adata, batch_key="batch", labels_key="labels")

TypeError: SCANVI.setup_anndata() missing 1 required positional argument: 'unlabeled_category'
```

#### Versions:

This is currently the case on the main branch of the repository (i.e. [`scvi/model/_scanvi.py`](https://github.com/scverse/scvi-tools/blob/70e7d268b4474ebbb886af038dca4a0399522147/scvi/model/_scanvi.py)), commit 70e7d268b4474ebbb886af038dca4a0399522147

```
In [2]: scvi.__version__
Out[2]: '1.0.0'
```

> VERSION

**Comment by martinkim0** [comment]
Hi, thanks for bringing up this issue. Indeed, it looks like `unlabeled_category` is not documented in that function, we'll fix it now.

**Comment by martinkim0** [comment]
@adamgayoso Is it strictly necessary for there to be an unlabeled category? My understanding is that scANVI would work the same even if all observations are labeled.

**Comment by adamgayoso** [comment]
I think there is based on the way it's implemented under the hood. We can use a default str argument and raise a warning if that's not found in the labels key.
