### ISSUE TITLE
[minor] Spurious warning when using JaxSCVI

### ISSUE THREAD

**Issue by bkmartinjr** [scverse/scvi-tools#2092]
When triaining JaxSCVI model on a GPU-enabled host, there is a spurious warning emitted:

> .../lightning/pytorch/trainer/setup.py:176: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=1)`.

There are similar warnings filtered - I thought you might want to add this one as well.

I ran on a AWS g5 instance (A10)

```python
scvi.model.JaxSCVI.setup_anndata(adata, layer="counts", batch_key="batch")
vae = scvi.model.JaxSCVI(adata)

# when on a g5 instance, with A10G TensorCores, torch requires that we specify desired precision.
torch.set_float32_matmul_precision("high")

vae.train(max_epochs=100, early_stopping=True, batch_size=4096)
```

#### Versions:

scvi version:  1.0.0
Ubuntu 22
Python 3.10
cuda 11.8

**Comment by adamgayoso** [comment]
this must be a generic torch/lightning warning as jaxscvi technically doesn't use torch as a backend

**Comment by bkmartinjr** [comment]
it seems to be harmless, so no urgency from my viewpoint
