### ISSUE TITLE
404 Not Found Link in “Introduction to scvi-tools” walkthrough

### ISSUE THREAD

**Issue by bakhtiarRepo** [scverse/scvi-tools#2097]
Underneath "[Introduction to scvi-tools](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/api_overview.html)" subsection "Loading and preparing data":

" Now we preprocess the data to remove, for example, genes that are very lowly expressed and other outliers. For these tasks we prefer the [Scanpy preprocessing module](https://scanpy.readthedocs.io/en/stable/api/index.html#module-scanpy.pp)."

The link sends someone to a 404 page

**Comment by martinkim0** [comment]
Thanks for pointing this out! This has been fixed in https://github.com/scverse/scvi-tutorials/pull/128
