### ISSUE TITLE
[feature request] scvi.autotune.ModelTuner: random seed config

### ISSUE THREAD

**Issue by bkmartinjr** [scverse/scvi-tools#2098]
I am attempting to reproduce some autotune experiments.  It would really nice if the scvi.autotune.ModelTuner allowed a user-controlled random seed to be passed to the trainable, more-or-less supporting the approach described in the [Ray docs](https://docs.ray.io/en/latest/tune/faq.html#how-can-i-reproduce-experiments)

**Comment by martinkim0** [comment]
This is a good idea, I'll see what I can do
