### ISSUE TITLE
Allow for computation and logging of integration metrics during training

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tools#2105]
Need to implement a way to allow the user to view available functions in scib-metrics and track them during model training.

**Comment by adamgayoso** [comment]
those could take a long time to run, but I'm sure you could subclass torch metrics object and run the benchmarker object.

**Comment by martinkim0** [comment]
Hopefully it can be mitigated a bit by adjusting `check_val_every_n_epoch`.
