### ISSUE TITLE
Training Speedup with Sparse Dataloader

### ISSUE THREAD

**Issue by valentinwust** [scverse/scvi-tools#2152]
This is probably dependent on the particular setup. But for the machine I am working on, and with high-dimensional data, training with your dataloader is much slower than it needs to be. The basic problem is that sending high-dimensional ATAC data between RAM and VRAM takes a lot of time, and this really slows down training. My fix for this is to load the counts from the dataset without making them dense, turning them into a sparse torch tensor, sending it to the device, and only filling the zeros in the VRAM. For my use case (60k peaks, my machine) this gives me a 3x speed boost, while not hurting performance for 3k dimensional RNA data.

If anyone wants to test whether the speedup is specific to my setup, I implemented this [in a self-contained file](https://github.com/scverse/scvi-tools/files/11956858/sparsemixin.zip) that implements `SparseUnsupervisedTrainingMixin` as a plug-in replacement for `UnsupervisedTrainingMixin` (on version 0.20.3, not sure if the new version breaks this). If trained normally nothing changes, if `device="cuda:0"` or equivalent is passed to `model.train()` it uses my approach for sparse data and directly sends all tensors to `device`. The actual implementation is just a few lines, most of the code is duplicated since I wanted something stand-alone (and didn't know how to get the appropriate device from within AnnDataLoader).

I'm happy to help with implementing this in the normal package (I don't know if you have good reasons to keep the dataloader fully on the CPU, for me this approach is faster even for low-dimensional data so I just use it as the default for all sparse data), although I'm not that deep into your code.

**Comment by martinkim0** [comment]
This is very interesting, thanks for sharing your code. If I'm understanding this correctly, these changes would load sparse data as follows:
```
scipy csr -> torch csr -> torch csr on device -> torch dense on device
```
As opposed to what we have currently:
```
scipy csr -> numpy dense -> torch dense -> torch dense on device
```
This makes sense given that sending a dense tensor to VRAM probably takes longer than a sparse one, although I wouldn't have anticipated it would give a 3x speed boost. Do you happen to have your benchmark code and results on hand? I'd be interested to try this on my setup. 

Even if the speedup is not as dramatic, this would be a valuable addition to our codebase. Would you be interested in opening a PR with these changes?

**Comment by martinkim0** [comment]
Ok I ran a simple benchmark with these changes (~20,000 cells x 27,000 genes) and I'm seeing a ~1.3x improvement per training epoch and specifically a 4.6x improvement during data loading. We can probably add this as a non-default option, though we definitely need to run some benchmarks to ensure that model performance is not significantly affected by this.

**Comment by valentinwust** [comment]
> Ok I ran a simple benchmark with these changes (~20,000 cells x 27,000 genes) and I'm seeing a ~1.3x improvement per training epoch and specifically a 4.6x improvement during data loading. We can probably add this as a non-default option, though we definitely need to run some benchmarks to ensure that model performance is not significantly affected by this.

The speedup is obviously larger for higher dimensions (60k, 120k etc. peaks), but I expected that it's going to vary with how the GPU is connected etc.

**Comment by valentinwust** [comment]
> This is very interesting, thanks for sharing your code. If I'm understanding this correctly, these changes would load sparse data as follows:
> 
> ```
> scipy csr -> torch csr -> torch csr on device -> torch dense on device
> ```

Yes, that's the idea.

About the PR, I'm not sure I'm the right person to implement this in a way that fits well with the rest of the code. It doesn't require that many changes, what I did was basically dropping the `.toarray()` for sparse data in `AnnTorchDataset`, and changing the collating function used in `AnnDataLoader`. Instead of the default `collate_fn=torch.utils.data.default_convert` I use a short extension that deals with sparse data as proposed (default_convert just passes sparse scipy data through without converting it):

```python
def sparse_convert(x, device=None):
    """ Torch default default_convert for non-sparse data.
        Sparse data is turned into torch csr, sent to device, and only then turned to dense.
    """
    if device is None: # If no device is given, use the torch default.
        return torch.utils.data.default_convert(x)
    else:
        if isinstance(x, dict): # If dictionary {"x":..., "y":..., etc.} do separately for each
            return {key: sparse_convert(x[key], device) for key in x}
        else:
            if scipy.sparse.issparse(x):
                # If sparse, go through torch csr, to device, then dense
                # Manually converting indptr etc. to torch is faster for some reason, as_tensor to not copy the data
                tensor_sparse = torch.sparse_csr_tensor(torch.as_tensor(x.indptr), torch.as_tensor(x.indices), torch.as_tensor(x.data), dtype=torch.float32, size=x.shape)
                return tensor_sparse.to(device).to_dense() # first to device, then to dense
            else: # Default is not sparse
                return torch.utils.data.default_convert(x).to(device)
```

Two issues with that are that I don't know how to properly get the correct device from within `AnnDataLoader`, and that the current dataloaders don't send data to the GPU at all. So sending it to the GPU already here might break something elsewhere for all I know. So it might be better if someone else who has a better overview over what the rest of the code does adds this in a way that doesn't break anything.

**Comment by martinkim0** [comment]
Sounds good - Lightning automatically sends data from the DataLoader to the correct device, so we don't explicitly set that on our end. I can open up a PR and tag you in it if that works for you.
