### ISSUE TITLE
Unable to use custom training plan with PyroSviTrainMixin

### ISSUE THREAD

**Issue by austinv11** [scverse/scvi-tools#2159]
Right now, the `PyroSviTrainMixin` class ignores the user-provided training_plan argument, making it impossible to overwrite. This line of code should have an if statement to check if a training plan was provided: https://github.com/scverse/scvi-tools/blob/main/scvi/model/base/_pyromixin.py#L161

```python
PyroSviTrainMixin().train(..., training_plan=...)
```

#### Versions:

> 1.0.1

**Comment by martinkim0** [comment]
Thanks for bringing up this issue! Seems like a simple fix, we can release it with the next patch.
