### ISSUE TITLE
Seurat Object Conversion

### ISSUE THREAD

**Issue by zacharyjxy2020** [scverse/scvi-tools#2160]
**Is your feature request related to a problem? Please describe.**
I am working with datasets which have been processed through Seurat. I am trying to move these data into scvi-tools and use CellAssign to assign different cell types. I am wondering how I can do this as the CellAssign function requires both the counts and cell type matrix, which I don't have from my original datasets.

**Describe the solution you'd like**
A method to extract the cell type matrix out of a seurat object or anndata and use CellAssign.

**Comment by martinkim0** [comment]
Hi, I can't really answer your question without more information, such as where your dataset is from and what kind of preprocessing was performed on it. CellAssign expects a DataFrame with marker genes corresponding to cell types. Depending on the tissues present in your dataset and the cell types you're expecting to find, you might be able to search for such a resource online.

If you have any additional questions, I'd encourage you to post in the [scverse Discourse](https://discourse.scverse.org/), a more appropriate forum. We'd like to reserve GitHub for bugs or feature requests only. Thanks!
