### ISSUE TITLE
Problem importing seurat object as h5ad with Cellassign

### ISSUE THREAD

**Issue by zacharyjxy2020** [scverse/scvi-tools#2164]
I am able to import the seurat object as an Anndata object and am trying to use it to run the CellAssign pipeline. I am encountering an error when trying to filter the genes. It seems that the anndata obs doesn't contain size_factor and cannot be filtered.

```python
bdata = adata[:, marker_gene_mat.index].copy()
lib_size = adata.X.sum(1)
adata.obs['size_factor'] = lib_size/np.mean(lib_size)
scvi.external.CellAssign.setup_anndata(bdata, size_factor_key="size_factor")
```

```pytb
KeyError: 'size_factor not found in adata.obs.'
```

#### Versions:

1.0.0

**Comment by martinkim0** [comment]
Hi, you can fix this issue by running `scvi.external.CellAssign.setup_anndata(adata, size_factor_key="size_factor")` since you put the size factor key in `adata`, not `bdata`.

**Comment by zacharyjxy2020** [comment]
Worked perfectly thank you so much
