### ISSUE TITLE
Couldn't find UMAP error

### ISSUE THREAD

**Issue by zacharyjxy2020** [scverse/scvi-tools#2165]
Trying to follow the CellAssign pipeline with another seurat dataset. Trained the model and obtained the predictions. I am trying to umap these predictions as per the tutorial but it seems as if there is an error.

```python
adata = sc.read("data/adultHumanChoroidSeurat.h5ad")
adata.obs.index = adata.obs.index.astype('str')
adata.var.index = adata.var.index.astype('str')
marker_gene_mat = pd.read_csv('data/cellType_mtx.csv', index_col=0)
adata.obs_names_make_unique()
adata.var_names_make_unique()
bdata = adata[:, marker_gene_mat.index].copy()
lib_size = adata.X.sum(1)
bdata.obs['size_factor'] = lib_size/np.mean(lib_size)
scvi.external.CellAssign.setup_anndata(bdata, size_factor_key="size_factor")
model = CellAssign(bdata, marker_gene_mat)
model.train()
model.history["elbo_validation"].plot()
predictions = model.predict()
predictions.head()
predictions.to_csv('data/predictions.csv')
bdata.obs["scvi-tools predictions"] = predictions.idxmax(axis=1).values
sc.pl.umap(bdata, color=["celltype","scvi-tools predictions"], frameon=False, ncols=1)
#%%

```

```pytb

Keyerror: "Could not find 'umap' or 'X_umap' in .obsm"
```

#### Versions:

1.0.0

**Comment by martinkim0** [comment]
Hi, you would need to compute the UMAP representation prior to plotting it. You can do so as follows:
```
sc.tl.pca(adata)  # compute PCA
sc.pp.neighbors(adata)  # compute neighbors on PCA representation for UMAP computation
sc.tl.umap(adata)  # compute UMAP representation from neighbors

sc.pl.umap(adata)  # plot UMAP now
```
You can see an example of this in our [introductory tutorial](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/api_overview.html#visualization-without-batch-correction)

**Comment by zacharyjxy2020** [comment]
Should I do this before or after I train the model and make predictions?

**Comment by cane11** [comment]
Thanks for your interest in using scVI.
It doesn't matter but you need to compute it before trying to plot UMAP (sc.pl.umap). I would recommend starting with the scanpy tutorials if you haven't looked at them yet.
Our GitHub page is reserved for bugs. This isn't a bug but a usage question. We prefer to answer those on our discourse forum.
