### ISSUE TITLE
Import error due to pydantic

### ISSUE THREAD

**Issue by hiraksarkar** [scverse/scvi-tools#2183]
`import scvi` fails with the following error 
`ImportError: cannot import name 'ModelMetaclass' from 'pydantic.main' (/n/fs/ragr-data/users/environments/mambaforge/envs/scvi-env/lib/python3.9/site-packages/pydantic/main.py)`

```bash
mamba install scvi-tools -c conda-forge
```

```python
import scvi
```

```pytb
[Paste the error output produced by the above code here]
```

#### Versions:

> VERSION
1.0.2

**Comment by martinkim0** [comment]
Hi, can you try `pip install -U lightning` prior to installing scvi-tools?

**Comment by hiraksarkar** [comment]
I tried that the error persisted, installing from the main github resolved the issue. Probably related to the recent lightening version change.

```
 pip install git+https://github.com/scverse/scvi-tools.git@main
 ```
