### ISSUE TITLE
Unable to import scvi

### ISSUE THREAD

**Issue by raman91** [scverse/scvi-tools#2192]
Hello,

I install scvi-tools using pip by the following command: pip install "scvi-tools[tutorials]" but getting an error: 
AttributeError: module 'anndata.compat' has no attribute 'Literal'

Could you please help in solving this issue?

Thank you

**Comment by martinkim0** [comment]
Hi, could you provide more information about your environment such as the scvi-tools version, anndata version etc? Thanks

**Comment by raman91** [comment]
Thank you for your help. I managed to solve it now by using another version of pyro.

**Comment by martinkim0** [comment]
Awesome, great to hear
