### ISSUE TITLE
model.save() fails for large models

### ISSUE THREAD

**Issue by yanwu2014** [scverse/scvi-tools#2195]
Right now `model.save()` seems to fail for large scvi-tools models due to limits on files that can be pickled with the default pickle protocol. I think a quick fix could be to either by default use `pickle_protocol=5` in `torch.save()` or enable passing of keyword arguments to `torch.save`

**Comment by martinkim0** [comment]
Thanks for bringing up this issue! Let me look into this

**Comment by yanwu2014** [comment]
Awesome thanks so much Martin!
