### ISSUE TITLE
Expected more than 1 value per channel when training, input size torch.Size([1, 128])

### ISSUE THREAD

**Issue by Josuerinho** [scverse/scvi-tools#2214]
Hi all!!

I'm having a similar issue as the ones reported here: https://github.com/scverse/scvi-tools/issues/221 and here: https://github.com/scverse/scvi-tools/issues/426. 

In my case I'm trying to predict doublets and I have an issue at the very beginning with one of the samples with the following code:

```python

SEED = 35

sc.pp.filter_genes(adata,  min_cells=10)
sc.pp.highly_variable_genes(adata, n_top_genes=2000, subset=True, flavor='seurat_v3')

scvi.settings.seed = SEED

scvi.model.SCVI.setup_anndata(adata)

vae = scvi.model.SCVI(adata)

vae.train()

```

The dataset size after the filtering steps is: `(4409, 2000)` and I've seen that the default value for `batch_size = 128`.
So as others have reported before, I get the following error (there are 45 collapsed lines that I can also show if you believe are needed to understand the problem):

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-33-8f71af99b8f8>](https://localhost:8080/#) in <cell line: 10>()
      8 
--->  9 vae.train()

45 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py](https://localhost:8080/#) in _verify_batch_size(size)
   2414         size_prods *= size[i + 2]
   2415     if size_prods == 1:
-> 2416         raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
   2417 
   2418 

ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 128])
```

So, when I divide `4409%128 = 57`, clearly shows that the last batch shouldn't be of `size = 1` and still, I get this error. When I remove on row of the `adata` object so the size now is `(4408, 2000)` or if I instead change the `batch_size` to `batch_size!=128` for example:

```python
vae.train(batch_size = 129)
```
In both cases it works just fine. So could you let me know why it is failing in this case with the original `batch_size = 128`?
I'm trying to understand the problem but I can't grasp it.

Thanks so much for your time and help!

Josu

**Comment by martinkim0** [comment]
Hi Josu, thanks for bringing up this issue. This is occurring because we have a default train-validation split with `train_size=0.9`. Thus, the number of training observations is computed as `train_n_obs = ceil(n_obs * train_size) = ceil(4409 * 0.9) = ceil(3968.1) = 3969` and therefore `train_n_obs % 128 = 1`. Hope this makes sense!

**Comment by Josuerinho** [comment]
Hi @martinkim0! That makes perfect sense and I should have thought about this 😅. Thanks so much. 

If you have the time and it's not too much of a bother, could you share with me where I can this part of the code in the `GitHub` repo? You guys have created an amazing library for scRNAseq analysis but, for me at least, is quite difficult and complex to navigate to the code I want to understand. Trying to walk through the steps/functions called in the background when I run, ie `vae.train()`, isn't that easy for me yet. 

Thanks for your answer and help! Really appreciate it.

**Comment by martinkim0** [comment]
Hi, sure I can provide some pointers on walking through the traceback. Apologies that the code is not always easy to follow, we could definitely do some work on simplifying the codebase. 

`SCVI` inherits its `train` method from `UnsupervisedTrainingMixin`. In this [method](https://github.com/scverse/scvi-tools/blob/main/scvi/model/base/_training_mixin.py#L73-L84), we create a `DataSplitter` instance, where you'll see the default `train_size=0.9` being passed in during initialization. If you're already familiar with Lightning, `DataSplitter` is just a subclass of `LightningDataModule` with our custom setup.

`DataSplitter` then [validates](https://github.com/scverse/scvi-tools/blob/main/scvi/model/base/_training_mixin.py#L73-L84) `train_size` and computes the actual number of training observations [here](https://github.com/scverse/scvi-tools/blob/main/scvi/dataloaders/_data_splitting.py#L41). We then have a method for creating a [train dataloader](https://github.com/scverse/scvi-tools/blob/main/scvi/dataloaders/_data_splitting.py#L139) that samples mini-batches from our subsampled training set.

From there, we're back in the `train` method, where this `DataSplitter` is [passed into](https://github.com/scverse/scvi-tools/blob/main/scvi/model/base/_training_mixin.py#L94) Lightning's `Trainer`. After that, Lightning handles all training procedures. Hope this helps!

**Comment by Josuerinho** [comment]
Not your fault at all! It's just that I definitely need some more experience tracing down processes that involve nested code and class inheritance, and I'm not there yet. Your post has been of great help indeed! Thank you so much for taking the time and effort. I do really appreciate it @martinkim0!
