### ISSUE TITLE
Conda recipe broken due to flax

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tools#2218]
Installing via conda will fail due to the latest jax release (0.4.14) that deprecates `jax.ShapedArray`. This is causing flax to fail since its conda and pypi releases are out of sync (0.6.1 vs. 0.7.1) due to its newer dependencies not being on conda: https://github.com/conda-forge/flax-feedstock/pull/24

**Comment by MishalAshraf** [comment]
Any idea how to work around this for the time being? install with pip?

**Comment by martinkim0** [comment]
Yep! Installing with just pip will work. Alternatively, you can pip install flax before installing scvi-tools with conda

**Comment by martinkim0** [comment]
Fixed now as the latest version of Flax is on conda forge.
