### ISSUE TITLE
Implement contrastiveVI

### ISSUE THREAD

**Issue by chris522229197** [scverse/scvi-tools#2242]
Proposal to implement contrastiveVI.

1. Code: https://github.com/suinleelab/contrastiveVI
2. Paper: https://www.nature.com/articles/s41592-023-01955-3

I can take on this issue since I know the implementation details of contrastiveVI. Are there things I should be aware of before submitting a pull request (e.g., an upcoming major release)?

**Comment by martinkim0** [comment]
Hi Chris, it'd be great to have contrastiveVI in the codebase. Feel free to put in an initial PR and I can give feedback then. I'm thinking this can be included in our v1.1 release.
