### ISSUE TITLE
Long (never ending???) runtime of scvi.model.SCVI.differential_expression with "weights = 'importance'"

### ISSUE THREAD

**Issue by MaximilianNuber** [scverse/scvi-tools#2253]
Hello everyone,

Thanks for the great tool, scvi has become my bread and butter.

I would like to ask about the option "weights = 'importance'" in the differential expression method of scvi.

I set up the model training just like I described here: #2236
However, I went further to test for differential genes.

Whenever weights = "uniform", I get my results within a few minutes.
For weights = "importance", I let the function run for around 4 hours, and less for a few times, but it never terminated successfully.
As compared to the successful run, the only thing I changed was weights = "uniform" to weights = "importance.
Again, I tried to follow the C.elegans tutorial with my own data.

Is there something I am doing wrong, or is the runtime expected?

Thank you for any help

```python

# continued after my previous post #2236 

cell_idx1 = adata.obs["cell type"] == "ct_1"
print(sum(cell_idx1), "cells of type", "ct_1")

cell_idx2 = adata.obs["cell type"] == "ct_2"
print(sum(cell_idx2), "cells of type", "ct_2")


# simple example from the tutorial

de_change = model.differential_expression(idx1=cell_idx1, idx2=cell_idx2)
de_change

# uniform weights is successful
de_change_uniform = model.differential_expression(
    idx1=cell_idx1,  # we use the same cells as chosen before
    idx2=cell_idx2,
    weights="uniform",
    batch_correction=True,
)

# importance-weights runs forever

de_change_uniform = model.differential_expression(
    idx1=cell_idx1,  # we use the same cells as chosen before
    idx2=cell_idx2,
    weights="importance",
   # I ran the method with and without "filter_outlier_cells"
   # filter_outlier_cells=True, 
    batch_correction=True,
)
```

```pytb
```

#### Versions:

> 1.0.2

**Comment by canergen** [comment]
Hi @MaximilianNuber, how much RAM is used? Is the CPU/GPU busy? It could be that it's caching and this leads to the slowdown but it's very hard to tell from the provided information.

**Comment by canergen** [comment]
Closed due to inactivity
