### ISSUE TITLE
Observed a bug in GimVI

### ISSUE THREAD

**Issue by HelloWorldLTY** [scverse/scvi-tools#2273]
Hi, I observed a bug in GimVI. That happened when I define a GimVI model and then re-define it:
```
# create our model
model = GIMVI(seq_data, spatial_data_partial)

# train for 200 epochs
model.train(200, batch_size = len(spatial_data_partial))
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[13], line 2
      1 # create our model
----> 2 model = GIMVI(seq_data, spatial_data_partial)
      4 # train for 200 epochs
      5 model.train(200, batch_size = len(spatial_data_partial))

File /gpfs/gibbs/project/zhao/tl688/conda_envs/scgpt/lib/python3.8/site-packages/scvi/external/gimvi/_model.py:139, in GIMVI.__init__(self, adata_seq, adata_spatial, generative_distributions, model_library_size, n_latent, correlation_const, **model_kwargs)
    137 library_log_vars = []
    138 for adata_manager in self.adata_managers.values():
--> 139     adata_library_log_means, adata_library_log_vars = _init_library_size(
    140         adata_manager, n_batches
    141     )
    142     library_log_means.append(adata_library_log_means)
    143     library_log_vars.append(adata_library_log_vars)

File /gpfs/gibbs/project/zhao/tl688/conda_envs/scgpt/lib/python3.8/site-packages/scvi/model/_utils.py:292, in _init_library_size(adata_manager, n_batch)
    286         warnings.warn(
    287             "This dataset has some empty cells, this might fail inference."
    288             "Data should be filtered with `scanpy.pp.filter_cells()`"
    289         )
    291     log_counts = masked_log_sum.filled(0)
--> 292     library_log_means[i_batch] = np.mean(log_counts).astype(np.float32)
    293     library_log_vars[i_batch] = np.var(log_counts).astype(np.float32)
    295 return library_log_means.reshape(1, -1), library_log_vars.reshape(1, -1)

IndexError: index 2 is out of bounds for axis 0 with size 2

If I re-define it more times, the error will be like "IndexError: index 3 is out of bounds for axis 0 with size 3", ...
I used the latest version of scVI. Could you please help me address this problem? Thanks.

**Comment by martinkim0** [comment]
Hi, I was able to reproduce your error. I'm working on a fix, but meanwhile you can fix it by rerunning `setup_anndata` prior to re-defining the model.

**Comment by HelloWorldLTY** [comment]
Thanks a lot!
