### ISSUE TITLE
ImportError: cannot import name 'SparseDataset' from 'anndata._core.sparse_dataset' 

### ISSUE THREAD

**Issue by knadia07** [scverse/scvi-tools#2276]
Hi I am currently test this tutorial out directly on google collab: https://docs.scvi-tools.org/en/1.0.3/tutorials/notebooks/quick_start/data_loading.html 

After unhashing the following and i am experiencing the following error;
!pip install --quiet scvi-colab
from scvi_colab import install 
install()
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-1-87955b66e060>](https://localhost:8080/#) in <cell line: 3>()
      1 get_ipython().system('pip install --quiet scvi-colab')
      2 from scvi_colab import install
----> 3 install()

5 frames
[/usr/local/lib/python3.10/dist-packages/scvi_colab/_core.py](https://localhost:8080/#) in install(version, branch, run_outside_colab, unfixed)
     80 
     81     try:
---> 82         import scvi  # noqa: F401
     83     except ContextualVersionConflict:
     84         logger.warning(

[/usr/local/lib/python3.10/dist-packages/scvi/__init__.py](https://localhost:8080/#) in <module>
      9 
     10 # this import needs to come after prior imports to prevent circular import
---> 11 from . import autotune, data, model, external, utils, criticism
     12 
     13 from importlib.metadata import version

[/usr/local/lib/python3.10/dist-packages/scvi/autotune/__init__.py](https://localhost:8080/#) in <module>
----> 1 from ._manager import TuneAnalysis, TunerManager
      2 from ._tuner import ModelTuner
      3 from ._types import Tunable, TunableMixin
      4 
      5 __all__ = ["ModelTuner", "Tunable", "TunableMixin", "TunerManager", "TuneAnalysis"]

[/usr/local/lib/python3.10/dist-packages/scvi/autotune/_manager.py](https://localhost:8080/#) in <module>
     21 from scvi._decorators import dependencies
     22 from scvi._types import AnnOrMuData
---> 23 from scvi.data._constants import _SETUP_ARGS_KEY, _SETUP_METHOD_NAME
     24 from scvi.model.base import BaseModelClass
     25 from scvi.utils import InvalidParameterError

[/usr/local/lib/python3.10/dist-packages/scvi/data/__init__.py](https://localhost:8080/#) in <module>
      1 from anndata import read_csv, read_h5ad, read_loom, read_text
      2 
----> 3 from ._anntorchdataset import AnnTorchDataset
      4 from ._datasets import (
      5     annotation_simulation,

[/usr/local/lib/python3.10/dist-packages/scvi/data/_anntorchdataset.py](https://localhost:8080/#) in <module>
      5 import numpy as np
      6 import pandas as pd
----> 7 from anndata._core.sparse_dataset import SparseDataset
      8 from scipy.sparse import issparse
      9 from torch.utils.data import Dataset

ImportError: cannot import name 'SparseDataset' from 'anndata._core.sparse_dataset' (/usr/local/lib/python3.10/dist-packages/anndata/_core/sparse_dataset.py)

Please comment. thanks.

**Comment by hanhanele** [comment]
I also encountered the same problem when installing scvi-tools

**Comment by martinkim0** [comment]
Hi, thank you for bringing up this issue. This is due to the new AnnData 0.10.0 release, which we are working on to get supported. For now, you can fix this by installing an AnnData version < 0.10.0.

**Comment by lindaseong** [comment]
Hello, 
I have also encountered this same error when trying to install and import. I have downgraded the AnnData as suggested, but am still getting the same import error. I've tried downgrading to versions 0.9.2, 0.8.0, and 0.7.8, none of which are working.

**Comment by martinkim0** [comment]
Hi, sorry that the solution did not work. I'm address the issue in #2271 and patching this week with 1.0.4.
