### ISSUE TITLE
ImportError when Installing scvi-colab: Cannot Import 'Doc' from 'typing_extensions'

### ISSUE THREAD

**Issue by aasingh2** [scverse/scvi-tools#2302]
Hi scvi team,

I encountered an ImportError when trying to install and run scvi-colab. The code and  error message with  traceback are as follows:

```python
!pip install --quiet scvi-colab
from scvi_colab import install
install()
```

```pytb
INFO     scvi-colab: Installing scvi-tools.                                                                        
INFO     scvi-colab: Install successful. Testing import.                                                           
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-8-87955b66e060>](https://localhost:8080/#) in <cell line: 3>()
      1 get_ipython().system('pip install --quiet scvi-colab')
      2 from scvi_colab import install
----> 3 install()

15 frames
[/usr/local/lib/python3.10/dist-packages/fastapi/exceptions.py](https://localhost:8080/#) in <module>
      4 from starlette.exceptions import HTTPException as StarletteHTTPException
      5 from starlette.exceptions import WebSocketException as StarletteWebSocketException
----> 6 from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]
      7 
      8 

ImportError: cannot import name 'Doc' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

---------------------------------------------------------------------------

```

I appreciate your help in resolving this issue. Please let me know if you need any additional information. Thanks!

**Comment by martinkim0** [comment]
Hi, thank you for bringing up this issue. Looks like the Google Colab environment comes installed with `typing_extensions 4.5.0` already, which is conflicting with `fastapi`'s requirement for `typing-extensions >= 4.8.0`. For now, you can solve this issue by running `!pip uninstall -y typing_extensions` before installing `scvi_colab`.

**Comment by aasingh2** [comment]
Removing `typing_extensions` did the trick. Appreciate the prompt response! It might be a good idea to consider bundling it with the package itself.

Additionally, this problem seems to be stemming from the fact that `typing-extensions >= 4.8.0` is incompatible with `tensorflow-probability 0.22.0`, which was recently updated in the Colab environment.

**Comment by mashrufehsan** [comment]
> Hi, thank you for bringing up this issue. Looks like the Google Colab environment comes installed with `typing_extensions 4.5.0` already, which is conflicting with `fastapi`'s requirement for `typing-extensions >= 4.8.0`. For now, you can solve this issue by running `!pip uninstall -y typing_extensions` before installing `scvi_colab`.
> 
> Edit: Looks like restarting the runtime (Runtime > Restart runtime) after installing also solves the issue. Most likely due to some package management issue in the environment.

It worked! Thanks a lot man.
