### ISSUE TITLE
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 128])

### ISSUE THREAD

**Issue by Huiflorazhan** [scverse/scvi-tools#2314]
When I try to use scvi to train the model, I got the following error. Could you please help me to solve this problem? Thank you for your time!
![image](https://github.com/scverse/scvi-tools/assets/139293021/bd0cb813-e5d8-4ef4-bcd6-2ed593d2df4f)

ValueError("Expected more than 1 value per channel when training, got input size {}".format(size)) 
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 128])

My code:
![image](https://github.com/scverse/scvi-tools/assets/139293021/cd7af8f2-e00d-4038-8a5f-7306854e4084)

scvi-tools version 1.0.4

**Comment by martinkim0** [comment]
Hi, this unfortunately occurs when the last batch of the training set contains one observation, leading to the batch norm layer complaining. You can solve this by passing in a `batch_size` to the `train` method that is different than the default one.

**Comment by Huiflorazhan** [comment]
> Hi, this unfortunately occurs when the last batch of the training set contains one observation, leading to the batch norm layer complaining. You can solve this by passing in a `batch_size` to the `train` method that is different than the default one.

It works. Thank you so much!
