### ISSUE TITLE
scvi-tools fails

### ISSUE THREAD

**Issue by joseagraz** [scverse/scvi-tools#2333]
scvi-tools installation fails on ubuntu 20. I've tried the installation two different ways (see below), but did not get far. Any suggestions how install scvi-tools properly?
GPU: NVIDIA RTX A4000

**1st SCVI installation fail:** See atached scvi-env_lib_list_version.txt for environment libraries installed

conda create -n scvi-env python=3.9
conda activate scvi-env
conda install -c anaconda pip
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
conda install jax jaxlib -c conda-forge
conda install scvi-tools -c conda-forge

Error:
/python3.9/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv

**2nd SCVI installation fail:** See atached scvi-env-p310_lib_list_version.txt for environment libraries installed
conda create -n scvi-env-p310 python=3.10
conda activate scvi-env-p310
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
conda install anndata -c conda-forge
conda install scvi-tools -c conda-forge
conda install -c conda-forge scanpy python-igraph leidenalg
conda install jax jaxlib -c conda-forge

Error:
libtorch_cuda.so: cannot open shared object file: No such file or directory

reinstalling torch produces:
lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
[scvi-env_lib_list_version.txt](https://github.com/scverse/scvi-tools/files/13444319/scvi-env_lib_list_version.txt)
[scvi-env-p310_lib_list_version.txt](https://github.com/scverse/scvi-tools/files/13444320/scvi-env-p310_lib_list_version.txt)

**Comment by martinkim0** [comment]
Could you try installing PyTorch and JAX dependencies as follows and seeing if it works:
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 cuda-nvcc=11.8 -c pytorch -c nvidia -c conda-forge
pip install jax[cuda11_pip] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
and then
```
pip install scvi-tools
```
We've had some issues with our conda install in the past, so please give pip a try!

**Comment by demian1** [comment]
Jumping on this issue as well. I have tried installing scvi-tools in many ways but always bump into variations of the following error:
`CUDA backend failed to initialize: Found cuSOLVER version 11305, but JAX was built against version 11401, which is newer.`

This is after installing it the way @martinkim0 suggested. I have not found a way yet to match cuda, cudnn etc with jax and jaxlib... Would be extremely grateful for a combination that works

**Comment by demian1** [comment]
Manually upgrading seems to work 👍
Would be great if you could update the installation section in the docs :)

**Comment by martinkim0** [comment]
Hey @demian1, glad you got it to work! What package did you manually upgrade that led to the fix?

**Comment by joseagraz** [comment]
I've tried the suggested recipe including scanpy, but get the error below. Reinstalling scvi-tools did not help. Have any other suggestions to try? Thank you

conda install pytorch torchvision torchaudio pytorch-cuda=11.8 cuda-nvcc=11.8 -c pytorch -c nvidia -c conda-forge
pip install jax[cuda11_pip] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install scvi-tools
pip install scanpy

OSError: libtorch_cuda.so: cannot open shared object file: No such file or directory

**Comment by martinkim0** [comment]
Hi, please see this https://github.com/pytorch/pytorch/issues/91186 and see if any of the fixes work for you

**Comment by ghar1821** [comment]
Ran into few errors (different from the ones described above) installing scVI using the tutorial on the website. This solution below from @martinkim0 works for me in conjunction with cuda/11.7.1 and python 3.9.

> Could you try installing PyTorch and JAX dependencies as follows and seeing if it works:
> 
> ```
> conda install pytorch torchvision torchaudio pytorch-cuda=11.8 cuda-nvcc=11.8 -c pytorch -c nvidia -c conda-forge
> pip install jax[cuda11_pip] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
> ```
> 
> and then
> 
> ```
> pip install scvi-tools
> ```
> 
> We've had some issues with our conda install in the past, so please give pip a try!

**Comment by joseagraz** [comment]
This installation worked for me:
git clone https://github.com/scverse/scvi-tools.git
conda create -n scvi-pip-p310 python=3.10
conda activate scvi-pip-p310
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
cd scvi-tools
pip install .
pip install scanpy
pip install jax[cuda11_pip] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install --user scikit-misc
python -c "import scvi; print(scvi.__version__)"

**Comment by demian1** [comment]
@martinkim0 After setting it up as explained in your previous comment, I needed to upgrade
`pip install nvidia-cusolver-cu11==11.4.1.48`

**Comment by frac2738** [comment]
I managed to fix all the compatibility issues by running
  `conda install jaxlib=*=*cuda* jax cuda-nvcc -c conda-forge -c nvidia` ,
which took care of selecting the right version based on the cuda version I have installed 

This is the full code:

    conda create -n scvi-env python=3.9
    conda activate scvi-env
    nvidia-smi
    +---------------------------------------------------------------------------------------+
    | NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
    |-----------------------------------------+----------------------+----------------------+
    | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
    |                                         |                      |               MIG M. |
    |=========================================+======================+======================|
    |   0  Quadro P2000                   On  | 00000000:09:00.0  On |                  N/A |
    | 65%   69C    P0              52W /  75W |   1165MiB /  5120MiB |     87%      Default |
    |                                         |                      |                  N/A |
    +-----------------------------------------+----------------------+----------------------+

    pip install pandas PyYAML scipy

    conda install jaxlib=*=*cuda* jax cuda-nvcc -c conda-forge -c nvidia

    # some things I tried but all failed
    # pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    # pip install -U --pre jaxlib -f https://storage.googleapis.com/jax-releases/jaxlib_nightly_cuda12_releases.html
    # pip3 install torch torchvision torchaudio

    pip install scvi-tools
    pip install 'scanpy[leiden]'

Now the GPU is recognised and used correctly
![image](https://github.com/scverse/scvi-tools/assets/7560675/98d26c0f-53a5-4f9f-b757-ffb1b3abed5f)

**Comment by joseagraz** [comment]
@frac2738, tried your recipe and worked great getting the same output as your. However, I also received a warning on JAX and cuDNN conflict. Any suggestions on how to resolve this new issue? 

Unable to initialize backend 'cuda': Found cuDNN version 8700, but JAX was built against version 8800, which is newer. The copy of cuDNN that is installed must be at least as new as the version against which JAX was built.

![Screenshot from 2024-01-11 13-47-08](https://github.com/scverse/scvi-tools/assets/2177473/6b9d5ae4-2196-4046-a490-cbc5afc3ce07)

**Comment by joseagraz** [comment]
Actually, the warning went away after executing the command below. Any suggestion how to resolve the other warning? I'm using a nVidia RTXA4000 GPU 

"pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"

2024-01-11 13:52:13,509 - INFO - Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA
2024-01-11 13:52:13,520 - INFO - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory

**Comment by martinkim0** [comment]
@joseagraz I wouldn't worry about the JAX warning if you don't intend on using any of our JAX models. I also wouldn't worry about the additional warning messages you're seeing as they relate to AMD and TPU backends, which you're not using.

**Comment by joseagraz** [comment]
Great, thanks.
I put together these two repositories with the info gathered here. I hope it helps others!

https://github.com/Kidney-Science/python_single_cell_analisys
https://github.com/Kidney-Science/install_RTXA4000_Driver_CUDA_cudNN_Ubuntu_22
