### ISSUE TITLE
Possible mistake in error formating - `scvi.data.fields._layer`

### ISSUE THREAD

**Issue by yotamcons** [scverse/scvi-tools#2335]
I have a model trained on 5k hvgs, and i tried to load it with the full Anndata object. The error text replaces the input and output

```python
model_dir = test
scvi.model.SCVI.setup_anndata(adata[:, adata.var.highly_variable].copy())
vae = scvi.model.SCVI(adata[:, adata.var.highly_variable].copy())
vae.save(model_dir, overwrite=True)
vae = scvi.model.SCVI.load(model_dir, adata=adata)
```

```pytb
File conda/envs/pp_t/lib/python3.9/site-packages/scvi/data/fields/_layer_field.py:116, in LayerField.transfer_field(self, state_registry, adata_target, **kwargs)
    114 target_n_vars = adata_target.n_vars
    115 if target_n_vars != n_vars:
--> 116     raise ValueError(
    117         "Number of vars in adata_target not the same as source. "
    118         + f"Expected: {target_n_vars} Received: {n_vars}"
    119     )
    121 return self.register_field(adata_target)

ValueError: Number of vars in adata_target not the same as source. Expected: 16964 Received: 5000
```

#### Versions:

> VERSION '1.0.4'

**Comment by canergen** [comment]
The problem is how you instantiate the model with 'adata[:, adata.var.highly_variable].copy()'
Please create a copy of your anndata as bdata and load the model using the subset object. We don't modify datasets during model load.

**Comment by yotamcons** [comment]
I think @canergen you did not understand my issue at all, the problem is the error message i got, not that i got the error

**Comment by martinkim0** [comment]
Hey so sorry, you're right, the error message is formatted incorrectly. I'll get this fixed!
