### ISSUE TITLE
question on mismatch peak to gene association

### ISSUE THREAD

**Issue by marjorieb12345** [scverse/scvi-tools#2337]
Hello,

I would like to know how MultiVI associates ATACseq peaks to genes. Does it associate it to TSS up/down some specific distance, or does it associate it to to the full gene including introns?
We run MultiVI on multiomics (TEAseq) data but found that in many cases the open chromatin regions do not match with the regions of gene expression on the joint UMAP representation.

Also, in your tutorial you say: In a well-mixed space, MultiVI can seamlessly impute the missing modalities for single-modality cells. First, imputing expression and accessibility is done with get_normalized_expression and get_accessibility_estimates, respectively. Does that mean for paired data, we still also need to use those function to get the gene expression and the accessibility for   the same gene? Let's say if i want to plot the gene expression and the accessibility of the gene POLR2A on the same latent space, could you provide a code to complete the tutorial?

We noticed that in the tutorial, there is no information on the genome database (e.g. hg38 or hg19). Does the program knows what database to use?

Thank you for your help

Marjorie

```python
# Your code here
```

```pytb
[Paste the error output produced by the above code here]
```

#### Versions:

> VERSION

**Comment by canergen** [comment]
@marianogabitto Can you provide insights?
