### ISSUE TITLE
PyMDE seed fixation suggestion

### ISSUE THREAD

**Issue by seyoon-lee** [scverse/scvi-tools#2372]
Hello,

I've been trying out different dimension reduction methods mostly for visualization purpose.
scvi.model.utils.mde seems to be a very interesting and useful feature added in the ecosystem, but I realized while I was playing around few parameters like neighbors and repulsive_fraction that the random seed is not fixed nor it could be fixed with a global seed in my script.
Could we just add a quick feature like scvi.model.utils.mde(seed=42) and add the pymde.seed(seed) calling right around there?

in _mde.py
 ```
    try:
         import pymde
         pymde.seed(seed)
```

Thank you for all your work!
Seyoon

**Comment by martinkim0** [comment]
Thanks for the suggestion, we can definitely add this as part of the next release!
