### ISSUE TITLE
Cannot train model

### ISSUE THREAD

**Issue by stefraptis** [scverse/scvi-tools#2375]
While I am am trying to run the differential expression test using the tutorial found https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scrna/scVI_DE_worm.html the model cannot be trained.

model = scvi.model.SCVI(
    adata, gene_likelihood="nb"
)  # We use Negative Binomial count likelihoods, following Boyeau et al., 2023.
model.train(
    check_val_every_n_epoch=1,
    max_epochs=400,
    early_stopping=True,
    early_stopping_patience=20,
    early_stopping_monitor="elbo_validation",
)

INFO: GPU available: False, used: False
INFO:lightning.pytorch.utilities.rank_zero:GPU available: False, used: False
GPU available: False, used: False
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
TPU available: False, using: 0 TPU cores
INFO: IPU available: False, using: 0 IPUs
INFO:lightning.pytorch.utilities.rank_zero:IPU available: False, using: 0 IPUs
IPU available: False, using: 0 IPUs
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
HPU available: False, using: 0 HPUs
/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fit_loop.py:281: PossibleUserWarning: The number of training batches (5) is smaller than the logging interval Trainer(log_every_n_steps=10). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 1/400:   0%|          | 0/400 [00:00<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-69-c9fda889f35a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model.train(
      2     check_val_every_n_epoch=1,
      3     max_epochs=400,
      4     early_stopping=True,
      5     early_stopping_patience=20,

44 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py](https://localhost:8080/#) in forward(self, input)
    112 
    113     def forward(self, input: Tensor) -> Tensor:
--> 114         return F.linear(input, self.weight, self.bias)
    115 
    116     def extra_repr(self) -> str:

RuntimeError: mat1 and mat2 must have the same dtype
#### Versions:

INFO: Global seed set to 0
INFO:lightning.fabric.utilities.seed:Global seed set to 0
Global seed set to 0
Last run with scvi-tools version: 1.0.4

**Comment by martinkim0** [comment]
I've never seen this particular error. Are you using the dataset from the tutorial or your own data? Also, are you on Linux or Mac?

**Comment by stefraptis** [comment]
Hello, thanks for your reply. I am using Windows and working on Google Colab. However, I found the cause of the error, which seems to be due to inconsistency between SCVI and PyTorch. I had installed the latest edition of PyTorch, while version 2.1.0 was needed. Downgrading to 2.1.0 solved the issue!

**Comment by martinkim0** [comment]
Great, glad you were able to resolve the issue! I'll be closing this thread.
