### ISSUE TITLE
No validation_step for scANVI

### ISSUE THREAD

**Issue by marcovarrone** [scverse/scvi-tools#2376]
I am trying to log the validation loss and accuracy during the fitting of scANVI.
However, I noticed that the function `validation_step` of `SemiSupervisedTrainingPlan` is never called.

I am following the [seed labeling tutorial](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scrna/seed_labeling.html) using version 1.0.4 of scvi-tools.

Is this something expected?

Thank you very much!

**Comment by martinkim0** [comment]
Hi, thanks for your question. Yes, by default we don't run the validation loop during training. You can change this behavior by passing in `check_val_every_n_epoch=1` to the training method.

**Comment by marcovarrone** [comment]
Thank you for such a quick answer!

However, using `check_val_every_n_epoch=1` works for scVI but not for scANVI.

**Comment by martinkim0** [comment]
Yeah, technically we should be running validation by default since `train_size != 1.0` (or alternatively setting train_size=1.0), but we haven't done so because of backwards compatibility reasons. Sorry for the confusion!
