### ISSUE TITLE
Replace `scvi.nn._utils.one_hot` in favor of the PyTorch version

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tools#2430]
No deprecation as it is part of the internal API

**Comment by erleholgersen** [comment]
Hi @martinkim0! I took a look at this (hoping to start contributing here!) and I noticed there is a difference in behaviour between these two functions when the input has more than one column. 

For example, consider the following input tensor:
```
x = tensor([[2, 1],
        [1, 2],
        [0, 2]])
```
The PyTorch version `one_hot` will one-hot encode each element of this tensor, resulting in a 3 x 2 x 3 tensor as output:
```
import torch.nn.functional as F
y_torch = F.one_hot(x, 3)
```
returns
```
tensor([[[1, 0, 0],
         [0, 1, 0]],

        [[0, 1, 0],
         [0, 0, 1]],

        [[0, 1, 0],
         [1, 0, 0]]])
```
The scvi-tools version of `one_hot` will jointly one-hot encode each row and return a 3 x 3 tensor as output. If a row has two different elements, it will return a single new row where those two elements are set to one, and all others are set to zero:
```
from scvi.nn import one_hot
y_scvi = one_hot(x, 3)
```
returns 
```
tensor([[1., 1., 0.],
        [0., 1., 1.],
        [1., 1., 0.]])
```
Do we want to preserve this behaviour? I wasn't sure if this is something we are relying on anywhere. All of the test cases only have a single column as input, in which case the output between the two functions is similar (PyTorch output is of dimensions N x 1 x C, scvi-tools output is dimension N x C).

**Comment by martinkim0** [comment]
@erleholgersen Thanks for taking a look at this! This is insightful - I didn't realize that the behaviors between our implementation and the torch one were different in this way. 

To confirm what you mentioned, I took a skim of instances of `scvi.nn.one_hot` in our codebase, and it looks like we always apply it to categorical tensors of shape `(n,)` or `(n, 1)`. If we want to replace these instances with the torch version, I think the most straightforward way then is to call `flatten` or `squeeze` so that the input is always of shape `(n,)` and the output is of shape `(n, n_categories)`. 

Also I misspoke - I didn't realize this was in our public API, so there has to be a deprecation. It also looks like several [repos](https://github.com/search?q=from+scvi.nn+import+one_hot&type=code) are using this too. We can deprecate in v1.2 and remove in v1.3.

Would be happy to take a PR if you're interested in contributing!

**Comment by erleholgersen** [comment]
Oh great, that makes sense! And yes, I'd love to take a stab at this – will aim to have a PR by the end of the week.

**Comment by erleholgersen** [comment]
Hi @martinkim0! I now have a local branch for this. Would you be able to give me write access to the repository so I can open a PR? Thank you!

**Comment by martinkim0** [comment]
Hi, are you working on a clone of the main repository or off a fork? If the former, I'd recommend doing the latter, and then you should be able to open a PR without write access. We typically don't give write permissions to contributors.

**Comment by erleholgersen** [comment]
Oh sorry, my bad! Will move to a fork.
