### ISSUE TITLE
UserWarning: The value argument must be within the support of the distribution   reconst_loss = -px.log_prob(x).sum(-1)

### ISSUE THREAD

**Issue by FZ-hajji** [scverse/scvi-tools#2449]
Hello,

I am using the scANVI model for batch correction of pancreas cell data, as demonstrated in this [tutorial.](https://docs.scvi-tools.org/en/0.15.1/tutorials/notebooks/scarches_scvi_tools.html) However, during the training of my model, I encountered the following warning: "The value argument must be within the support of the distribution. Reconst_loss = -px.log_prob(x).sum(-1)."

Here is the code snippet I used:
url = "https://figshare.com/ndownloader/files/24539828"
raw_adata = sc.read("raw_scib_pancreas.h5ad", backup_url=url)
sc.pp.highly_variable_genes(raw_adata, n_top_genes=2000,batch_key="tech")
scvi.model.SCANVI.setup_anndata(raw_adata, batch_key="tech", labels_key="celltype",unlabeled_category="Unknown")
vae = scvi.model.SCANVI(raw_adata)
vae.train()
adata.obsm["X_scVI"] = vae.get_latent_representation()

My question is : could this warning affect my results afterward ?

**Comment by martinkim0** [comment]
Hi, this means that your data does not exclusively contain non-negative integers. This will most likely affect the training of your model, so we recommend that you only use raw counts for scANVI.
