### ISSUE TITLE
mamba receipt to use gpu for scvitools

### ISSUE THREAD

**Issue by qiyubio** [scverse/scvi-tools#2471]
**Is your feature request related to a problem? Please describe.**
To make scvitools utilize gpus, Jax, cudatoolkit and torch all have to be installed without conflicts.

**Describe the solution you'd like**
Here is the receipt we used on our cluster, might save others some time:
```
mamba create -n scvi-env python=3.9
mamba activate scvi-env
# install cudatoolkit/11.8 with jax
pip install -U "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
mamba install cudatoolkit
# install torch
pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121
# install scvi-tools with scanpy
pip install "scvi-tools[tutorials]"
```

**Comment by martinkim0** [comment]
For anyone visiting this thread, please also refer to our [documentation](https://docs.scvi-tools.org/en/latest/installation.html#prerequisites) for how to correctly set up and environment with PyTorch and JAX.
