### ISSUE TITLE
scvi modules not able to import

### ISSUE THREAD

**Issue by scarlettcanny** [scverse/scvi-tools#2490]
Hi I am a new user to scvi, I tried to install scvi-tools from this installation manual: https://docs.scvi-tools.org/en/stable/installation.html, followed every step, and failed to import scvi sub-modules such as scvi.models, scvi.metrics, scvi.inference and scvi.dataset. ALL FAILED. only **import scvi** works.

Thanks for your help and any response is highly appreciated!

```python
#
import scvi
from scvi.dataset.dataset import GeneExpressionDataset
from scvi.inference.posterior import *
from scvi.metrics.clustering import select_indices_evenly, clustering_scores, entropy_batch_mixing
from scipy import sparse
from scvi.models.vae import VAE

```

```pytb
In [3]: import scvi

In [4]: from scvi.inference.posterior import *
   ...: from scvi.metrics.clustering import select_indices_evenly, clustering_scores, entropy_batch_mixing
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[4], line 1
----> 1 from scvi.inference.posterior import *
      2 from scvi.metrics.clustering import select_indices_evenly, clustering_scores, entropy_batch_mixing

ModuleNotFoundError: No module named 'scvi.inference'

In [5]: from scvi.metrics.clustering import select_indices_evenly, clustering_scores, entropy_batch_mixing
   ...: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], line 1
----> 1 from scvi.metrics.clustering import select_indices_evenly, clustering_scores, entropy_batch_mixing

ModuleNotFoundError: No module named 'scvi.metrics'

In [6]: from scvi.models.vae import VAE
   ...: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], line 1
----> 1 from scvi.models.vae import VAE

ModuleNotFoundError: No module named 'scvi.models'
```

#### Versions:

> VERSION1.0.4

**Comment by martinkim0** [comment]
Hi, sorry you're experiencing this issue. Where did you get your code from? It looks like it's referencing the old API. We don't have a lot of those submodules anymore, and this has been the case for a while now.

**Comment by scarlettcanny** [comment]
Hi Martin,

The code is coming from: 
https://github.com/chenlingantelope/HarmonizationSCANVI/blob/master/notebooks/harmonization-CitePure-SCANVI.ipynb

Just wondering if I can still reproduce the main functions in the code?

Thanks!

**Comment by martinkim0** [comment]
Unfortunately that notebook is outdated, and we don't have a corresponding current tutorial that goes through exactly what that notebook does. However, we do have various newer tutorials for [`scANVI`](https://docs.scvi-tools.org/en/latest/tutorials/index_scrna.html), such as [this](https://docs.scvi-tools.org/en/latest/tutorials/notebooks/scrna/harmonization.html) one, that recapitulate the main analyses. It also looks like that tutorial uses a CITE-seq dataset. If you're interested, we also have [totalVI](https://docs.scvi-tools.org/en/latest/tutorials/notebooks/multimodal/totalVI.html), a model similar to scANVI that was primarily intended for CITE-seq. Let me know if this helps!

**Comment by scarlettcanny** [comment]
Hi, thanks a lot for your info. Just wondering for batch removal which specific tutorial might be the most helpful one to try scanvi?

Best,
S

**Comment by martinkim0** [comment]
Hi, you may refer to [this tutorial](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scrna/tabula_muris.html) for how to perform batch removal with scANVI.

I'm also going to go ahead and close this issue since it's resolved, but feel free to follow up here in the future.
