### ISSUE TITLE
Unable to set n_latent for PoissonVI

### ISSUE THREAD

**Issue by shahrozeabbas** [scverse/scvi-tools#2516]
Hello,

Thanks for your help in the recent months regarding other issues. 

I have been testing `poissonvi` and noticed that I am unable to set `n_latent` for the model prior to training. It seems to always use the default calculation, both in the pre-release and the recent version from yesterday. 

I was wondering if I am missing something and this is by design or a potential bug. 

Let me know if you need to see an example, thanks. 

@lauradmartens

**Comment by martinkim0** [comment]
Hi @shahrozeabbas, sorry about this issue. Indeed, it looks like the model does not correctly apply a user-supplied `n_latent`. I'll go ahead and fix this and release it with 1.1.1.

**Comment by martinkim0** [comment]
@shahrozeabbas Just released the fix with 1.1.1, let me know if this works on your end!

**Comment by shahrozeabbas** [comment]
Working as expected, thanks so much! @martinkim0
