### ISSUE TITLE
Unable to retrieve region factors for PoissonVI model

### ISSUE THREAD

**Issue by duyguk** [scverse/scvi-tools#2529]
Hi! I am unable to retrieve region factors with `model.get_region_factors()` for PoissonVI models (one trained on my own dataset, another trained on a subset of the tutorial PBMC data). The call instead returns the following error:

```pytb
AttributeError: 'VAE' object has no attribute 'region_factors'
```

#### Versions:

> 1.1.1
> 1.1.0.post2

**Comment by ori-kron-wis** [comment]
Originally This is a PEAKVI thing but PoissonVI didn't have get_region_factors cause it uses the VAE module.
I added that function to it.
There will be a fix for 1.2.0
