### ISSUE TITLE
is  there any way to sepcific the number of workers when using scvi  in R ?

### ISSUE THREAD

**Issue by lwlive** [scverse/scvi-tools#2545]
when I integrating datasets with scVI in R (https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scrna/scvi_in_R.html), it reports the following warnings. I am wondering how could I  set the num_workers in   R? Could  you give some suggestions?

python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=111` in the `DataLoader` to improve performance.

**Comment by canergen** [comment]
Hi, I wouldn't worry to much about this message. The speed improvement by increasing num_worker is not high. @ori-kron-wis it's not high priority to look into this but it would be good to figure this one out.

**Comment by ori-kron-wis** [comment]
Hi @lwlive yes, you can specify in you R code:

```
# run setup_anndata
scvi$model$SCVI$setup_anndata(adata)
scvi$settings$dl_num_workers = 7L #where here you will set your num of workers in R integer
scvi$settings$persistent_workers = 'True' #this will not be ready until scvi 1.2.0

# create the model
model = scvi$model$SCVI(adata)

# train the model
model$train()
```
