### ISSUE TITLE
reference mapping  using the original umap

### ISSUE THREAD

**Issue by Sirin24** [scverse/scvi-tools#2613]
Hello, I would appreciate your help.
I was following https://docs.scvi-tools.org/en/1.0.1/tutorials/notebooks/scarches_scvi_tools.html

I would like to use the umap which came with an h5ad reference for reference mapping because upon computing the following, the resulting umap is different:
#obtain latent representation
adata.obsm["X_scVI"] = vae_ref.get_latent_representation()
sc.pp.neighbors(adata, use_rep="X_scVI")
sc.tl.leiden(adata)
sc.tl.umap(adata)
sc.pl.umap(
    adata,
    color=["supercluster_term"],
    frameon=False,
    ncols=1,
)

is there a way to preserve it or infere the parameters of an already existing umap to carry those parameters to the new umap?

**Comment by canergen** [comment]
Hi, my understanding is that you downloaded a reference dataset and want your test dataset to have a similar UMAP embedding. UMAP is not a part of scVI-tools. Therefore this is not a bug. Please use our discourse forum for feature requests. You might want to look into https://umap-learn.readthedocs.io/en/latest/transform.html to compute the same UMAP for reference and query data, but there is no way to yield this from an h5ad with an existing UMAP.
