### ISSUE TITLE
No search space autotune error

### ISSUE THREAD

**Issue by mousepixels** [scverse/scvi-tools#2614]
Autotune is telling me there is no search space. I have tried the default search space and a custom one. Both give the same error.

```python
from scvi.autotune import ModelTuner
#other imports

param_space = {...}

adata = sc.read_h5ad('adata.h5ad')
scvi.model.SCVI.setup_anndata(adata)
tuner = ModelTuner(model)

results = tuner.fit(adata, metric="validation_loss", search_space = param_space)
#results = tuner.fit(adata, metric="validation_loss") #also throws error

```

```pytb
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[21], line 3
      1 tuner = ModelTuner(model)
----> 3 results = tuner.fit(adata, metric="validation_loss", search_space = param_space)

File ~/miniconda3/envs/scvi/lib/python3.9/site-packages/scvi/autotune/_tuner.py:116, in ModelTuner.fit(self, adata, **kwargs)
     34 """Run a specified hyperparameter sweep for the associated model class.
     35 
     36 Parameters
   (...)
    113     A dataclass containing the results of the tuning experiment.
    114 """
    115 tuner, config = self._manager._get_tuner(adata, **kwargs)
--> 116 results = tuner.fit()
    117 return self._manager._get_analysis(results, config)

File ~/miniconda3/envs/scvi/lib/python3.9/site-packages/ray/tune/tuner.py:381, in Tuner.fit(self)
    379 if not self._is_ray_client:
    380     try:
--> 381         return self._local_tuner.fit()
    382     except TuneError as e:
    383         raise TuneError(
    384             _TUNER_FAILED_MSG.format(
    385                 path=self._local_tuner.get_experiment_checkpoint_dir()
    386             )
    387         ) from e

File ~/miniconda3/envs/scvi/lib/python3.9/site-packages/ray/tune/impl/tuner_internal.py:509, in TunerInternal.fit(self)
    507 param_space = copy.deepcopy(self.param_space)
    508 if not self._is_restored:
--> 509     analysis = self._fit_internal(trainable, param_space)
    510 else:
    511     analysis = self._fit_resume(trainable, param_space)

File ~/miniconda3/envs/scvi/lib/python3.9/site-packages/ray/tune/impl/tuner_internal.py:628, in TunerInternal._fit_internal(self, trainable, param_space)
    615 """Fitting for a fresh Tuner."""
    616 args = {
    617     **self._get_tune_run_arguments(trainable),
    618     **dict(
   (...)
    626     **self._tuner_kwargs,
    627 }
--> 628 analysis = run(
    629     **args,
    630 )
    631 self.clear_remote_string_queue()
    632 return analysis

File ~/miniconda3/envs/scvi/lib/python3.9/site-packages/ray/tune/tune.py:845, in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, storage_path, storage_filesystem, search_alg, scheduler, checkpoint_config, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, resume, reuse_actors, raise_on_failed_trial, callbacks, max_concurrent_trials, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, chdir_to_trial_dir, local_dir, _remote, _remote_string_queue, _entrypoint)
    842 if isinstance(search_alg, Searcher):
    843     search_alg = SearchGenerator(search_alg)
--> 845 if config and not searcher_set_search_props(
    846     search_alg.set_search_properties,
    847     metric,
    848     mode,
    849     config,
    850     **experiments[0].public_spec,
    851 ):
    852     if _has_unresolved_values(config):
    853         raise ValueError(
    854             f"You passed a `{error_message_map['search_space_arg']}` parameter to "
    855             f"`{error_message_map['entrypoint']}` with "
   (...)
    859             "them in the search algorithm's search space if necessary."
    860         )

File ~/miniconda3/envs/scvi/lib/python3.9/site-packages/ray/tune/search/util.py:19, in _set_search_properties_backwards_compatible(set_search_properties_func, metric, mode, config, **spec)
     14 """Wraps around set_search_properties() so that it is backward compatible.
     15 
     16 Also outputs a warning to encourage custom searchers to be updated.
     17 """
     18 try:
---> 19     return set_search_properties_func(metric, mode, config, **spec)
     20 except TypeError as e:
     21     if str(e).startswith(
     22         "set_search_properties() got an unexpected keyword argument"
     23     ):

File ~/miniconda3/envs/scvi/lib/python3.9/site-packages/ray/tune/search/search_generator.py:63, in SearchGenerator.set_search_properties(self, metric, mode, config, **spec)
     60 def set_search_properties(
     61     self, metric: Optional[str], mode: Optional[str], config: Dict, **spec
     62 ) -> bool:
---> 63     return _set_search_properties_backwards_compatible(
     64         self.searcher.set_search_properties, metric, mode, config, **spec
     65     )

File ~/miniconda3/envs/scvi/lib/python3.9/site-packages/ray/tune/search/util.py:19, in _set_search_properties_backwards_compatible(set_search_properties_func, metric, mode, config, **spec)
     14 """Wraps around set_search_properties() so that it is backward compatible.
     15 
     16 Also outputs a warning to encourage custom searchers to be updated.
     17 """
     18 try:
---> 19     return set_search_properties_func(metric, mode, config, **spec)
     20 except TypeError as e:
     21     if str(e).startswith(
     22         "set_search_properties() got an unexpected keyword argument"
     23     ):

File ~/miniconda3/envs/scvi/lib/python3.9/site-packages/ray/tune/search/hyperopt/hyperopt_search.py:294, in HyperOptSearch.set_search_properties(self, metric, mode, config, **spec)
    290     self._mode = mode
    292 self.metric_op = -1.0 if self._mode == "max" else 1.0
--> 294 self._setup_hyperopt()
    295 return True

File ~/miniconda3/envs/scvi/lib/python3.9/site-packages/ray/tune/search/hyperopt/hyperopt_search.py:205, in HyperOptSearch._setup_hyperopt(self)
    202 from hyperopt.fmin import generate_trials_to_calculate
    204 if not self._space:
--> 205     raise RuntimeError(
    206         UNDEFINED_SEARCH_SPACE.format(
    207             cls=self.__class__.__name__, space="space"
    208         )
    209         + HYPEROPT_UNDEFINED_DETAILS
    210     )
    212 if self._metric is None and self._mode:
    213     # If only a mode was passed, use anonymous metric
    214     self._metric = DEFAULT_METRIC

RuntimeError: Trying to sample a configuration from HyperOptSearch, but no search space has been defined. Either pass the `space` argument when instantiating the search algorithm, or pass a `param_space` to `tune.Tuner()`. This issue can also come up with HyperOpt if your search space only contains constant variables, which is not supported by HyperOpt. In that case, don't pass any searcher or add sample variables to the search space.
```

#### Versions:

1.1.2

absl-py==2.1.0
aiohttp==3.9.3
aiohttp-cors==0.7.0
aiorwlock==1.4.0
aiosignal==1.3.1
anndata==0.10.6
annotated-types==0.6.0
anyio==4.3.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array_api_compat==1.4.1
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.2.0
Babel==2.14.0
beautifulsoup4==4.12.3
bleach==6.1.0
blessed==1.20.0
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
chex==0.1.85
click==8.1.7
cloudpickle==3.0.0
colorful==0.5.6
comm==0.2.2
contextlib2==21.6.0
contourpy==1.2.0
cycler==0.12.1
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.8
docrep==0.3.2
etils==1.5.2
exceptiongroup==1.2.0
executing==2.0.1
fastapi==0.108.0
fastjsonschema==2.19.1
filelock==3.13.1
flax==0.8.2
fonttools==4.50.0
fqdn==1.5.1
frozenlist==1.4.1
fsspec==2024.3.0
future==1.0.0
get-annotations==0.1.2
google-api-core==2.17.1
google-auth==2.28.2
googleapis-common-protos==1.63.0
gpustat==1.1.1
grpcio==1.62.1
h11==0.14.0
h5py==3.10.0
httpcore==1.0.4
httptools==0.6.1
httpx==0.27.0
hyperopt==0.2.7
idna==3.6
importlib_metadata==7.0.2
importlib_resources==6.3.0
ipykernel==6.29.3
ipython==8.18.1
ipywidgets==8.1.2
isoduration==20.11.0
jax==0.4.25
jaxlib==0.4.25
jedi==0.19.1
Jinja2==3.1.3
joblib==1.3.2
json5==0.9.22
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter-events==0.9.1
jupyter-lsp==2.2.4
jupyter_client==8.6.1
jupyter_core==5.7.2
jupyter_server==2.13.0
jupyter_server_terminals==0.5.3
jupyterlab==4.1.5
jupyterlab_pygments==0.3.0
jupyterlab_server==2.25.4
jupyterlab_widgets==3.0.10
kiwisolver==1.4.5
lightning==2.1.4
lightning-utilities==0.10.1
llvmlite==0.42.0
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.3
matplotlib-inline==0.1.6
mdurl==0.1.2
mistune==3.0.2
ml-collections==0.1.1
ml-dtypes==0.3.2
mpmath==1.3.0
msgpack==1.0.8
mudata==0.2.3
multidict==6.0.5
multipledispatch==1.0.0
natsort==8.4.0
nbclient==0.10.0
nbconvert==7.16.2
nbformat==5.10.3
nest-asyncio==1.6.0
networkx==3.2.1
notebook==7.1.2
notebook_shim==0.2.4
numba==0.59.0
numpy==1.26.4
numpyro==0.14.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==12.535.133
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.1.105
opencensus==0.11.4
opencensus-context==0.1.3
opt-einsum==3.3.0
optax==0.2.1
orbax-checkpoint==0.5.6
overrides==7.7.0
packaging==24.0
pandas==2.2.1
pandocfilters==1.5.1
parso==0.8.3
patsy==0.5.6
pexpect==4.9.0
pillow==10.2.0
platformdirs==4.2.0
prometheus_client==0.20.0
prompt-toolkit==3.0.43
protobuf==4.25.3
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
py-spy==0.3.14
py4j==0.10.9.7
pyarrow==15.0.1
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==2.6.4
pydantic_core==2.16.3
Pygments==2.17.2
pynndescent==0.5.11
pyparsing==3.1.2
pyro-api==0.1.2
pyro-ppl==1.9.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-json-logger==2.0.7
pytorch-lightning==2.2.1
pytz==2024.1
PyYAML==6.0.1
pyzmq==25.1.2
ray==2.9.3
referencing==0.33.0
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.1
rpds-py==0.18.0
rsa==4.9
scanpy==1.9.8
scikit-learn==1.4.1.post1
scipy==1.12.0
scvi-tools==1.1.2
seaborn==0.13.2
Send2Trash==1.8.2
session-info==1.0.0
six==1.16.0
smart-open==7.0.1
sniffio==1.3.1
soupsieve==2.5
stack-data==0.6.3
starlette==0.32.0.post1
statsmodels==0.14.1
stdlib-list==0.10.0
sympy==1.12
tensorboardX==2.6.2.2
tensorstore==0.1.55
terminado==0.18.1
threadpoolctl==3.3.0
tinycss2==1.2.1
tomli==2.0.1
toolz==0.12.1
torch==2.2.1
torchaudio==2.2.1
torchmetrics==1.3.1
torchvision==0.17.1
tornado==6.4
tqdm==4.66.2
traitlets==5.14.2
triton==2.2.0
types-python-dateutil==2.9.0.20240315
typing_extensions==4.10.0
tzdata==2024.1
umap-learn==0.5.5
uri-template==1.3.0
urllib3==2.2.1
uvicorn==0.28.0
uvloop==0.19.0
virtualenv==20.25.1
watchfiles==0.21.0
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
websockets==12.0
widgetsnbextension==4.0.10
wrapt==1.16.0
yarl==1.9.4
zipp==3.18.1

> VERSION

**Comment by martinkim0** [comment]
Hi, sorry you're experiencing this issue. Could you paste the search space you are trying out?

**Comment by mousepixels** [comment]
I also tried the default with just:

`tuner.fit(adata, metric="validation_loss")
`

`param_space = {
    'n_hidden': {
        'distribution': 'choice',
        'choices': [64, 128, 256, 512], 
    },
    'n_latent': {
        'distribution': 'choice',
        'choices': [5, 10, 20, 30], 
    },
    'n_layers': {
        'distribution': 'choice',
        'choices': [1, 2, 3], 
    },
    'dropout_rate': {
        'distribution': 'uniform',
        'low': 0.0,
        'high': 0.5, 
    },
    'gene_likelihood': {
        'distribution': 'choice',
        'choices': ['zinb', 'nb'], 
    }
}
`

**Comment by mousepixels** [comment]
I am also a little confused because in the model.history there is no validation loss even after successful training. Only reconstruction_loss_train

**Comment by mousepixels** [comment]
I checked earlier versions of scvi-tools:
1.0.4 did not work
0.20.3 does work

**Comment by martinkim0** [comment]
It's possible that this is due to a new release of Ray. Could you pass in `param_space` formatted using the tune search API:
```
from ray import tune 

param_space = {
  'n_hidden': tune.choice([64, 128, 256, 512]),
  'n_latent': tune.choice([5, 10, 20, 30]),
  'n_layers': tune.choice([1, 2, 3]),
  ... # other params
}
```

**Comment by martinkim0** [comment]
Regarding validation loss, our default is set to not run validation steps. This can be enabled with passing in `check_val_every_n_epoch=1` to the train method.

**Comment by mousepixels** [comment]
Ok, great. That fixed it. I was a little confused because the default search_space was returning the same error. Thanks!

**Comment by martinkim0** [comment]
Yeah we format the default search space a little differently because of the way we parse it internally. That might have been a bit confusing, sorry.
