### ISSUE TITLE
conda issue-  import scvi

### ISSUE THREAD

**Issue by Sirin24** [scverse/scvi-tools#2639]
I tried multiple times to install scvi through. I still have an issue with import scvi. Nothing happens when i  try to import it.

#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_pytorch_select           0.2                       gpu_0    anaconda
alabaster                 0.7.12                   pypi_0    pypi
anndata                   0.7.4            py38h32f6830_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
argon2-cffi               20.1.0           py38h1e0a361_2    conda-forge
assorthead                0.0.11                   pypi_0    pypi
astroid                   2.4.1                    pypi_0    pypi
async_generator           1.10                       py_0    anaconda
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
babel                     2.8.0                    pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    anaconda
backports.functools_lru_cache 1.6.1                      py_0    anaconda
biocframe                 0.5.9                    pypi_0    pypi
biocutils                 0.1.5                    pypi_0    pypi
black                     20.8b1                     py_1    conda-forge
blas                      1.0                         mkl    anaconda
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
blosc                     1.20.1               he1b5a44_0    conda-forge
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cachecontrol              0.12.6                     py_0    anaconda
cachy                     0.3.0                      py_0    anaconda
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.14.3           py38h1bdcb99_1    conda-forge
cfgv                      3.2.0                    pypi_0    pypi
chardet                   3.0.4           py38h924ce5b_1008    conda-forge
chart-studio              1.1.0                    pypi_0    pypi
cleo                      0.7.6                      py_0    anaconda
click                     7.1.2              pyh9f0ad1d_0    conda-forge
clikit                    0.4.3              pyh9f0ad1d_0    conda-forge
codecov                   2.1.13                   pypi_0    pypi
colorama                  0.4.3                      py_0    anaconda
commonmark                0.9.1                      py_0    anaconda
coverage                  5.3                      pypi_0    pypi
cryptography              3.1.1            py38hb23e4d4_1    conda-forge
cudatoolkit               10.1.243             h6bb024c_0    anaconda
cudnn                     7.6.5                cuda10.1_0    anaconda
cycler                    0.10.0                     py_2    conda-forge
dataclasses               0.7                pyhb2cacf7_7    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    anaconda
defusedxml                0.6.0                      py_0    anaconda
delayedarray              0.5.0                    pypi_0    pypi
distlib                   0.3.1                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
dodgy                     0.2.1                    pypi_0    pypi
entrypoints               0.3             py38h32f6830_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
filelock                  3.0.12                   pypi_0    pypi
flake8                    3.8.4                    pypi_0    pypi
flake8-polyfill           1.0.2                    pypi_0    pypi
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.3               he06d7ca_0    conda-forge
future                    0.18.2           py38h32f6830_2    conda-forge
genomicranges             0.4.12                   pypi_0    pypi
get-version               2.1                      pypi_0    pypi
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.66.1               h680cd38_0    conda-forge
gmp                       6.2.0                he1b5a44_3    conda-forge
h5py                      2.10.0          nompi_py38h7442b35_105    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
hyperopt                  0.1.2                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
identify                  1.5.6                    pypi_0    pypi
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        2.0.0                      py_1    anaconda
importlib_metadata        2.0.0                         1    anaconda
iniconfig                 1.0.1                    pypi_0    pypi
intel-openmp              2020.2                      254    anaconda
ipykernel                 5.3.4            py38h5ca1d4c_0    anaconda
ipython                   7.18.1           py38h1cdfbd6_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
iranges                   0.2.3                    pypi_0    pypi
isort                     4.3.21                   pypi_0    pypi
jedi                      0.17.2           py38h32f6830_1    conda-forge
jeepney                   0.4.3                      py_0    anaconda
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    anaconda
jpeg                      9d                   h516909a_0    conda-forge
jsonschema                3.2.0                      py_2    anaconda
jupyter                   1.0.0                    pypi_0    pypi
jupyter-console           6.2.0                    pypi_0    pypi
jupyter_client            6.1.7                      py_0    anaconda
jupyter_core              4.6.3            py38h32f6830_2    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
keyring                   18.0.1           py38h32f6830_0    conda-forge
kiwisolver                1.2.0            py38hbf85e49_1    conda-forge
lazy-object-proxy         1.4.3                    pypi_0    pypi
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
legacy-api-wrap           1.2                      pypi_0    pypi
leidenalg                 0.8.2            py38habedc41_0    conda-forge
libblas                   3.8.0                    16_mkl    conda-forge
libcblas                  3.8.0                    16_mkl    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.8.0                    16_mkl    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_5    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libsodium                 1.0.18               h516909a_1    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvmlite                  0.34.0           py38h4f45e52_2    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
loompy                    3.0.6                    pypi_0    pypi
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                1.1.1            py38h8df0ef7_2    conda-forge
matplotlib-base           3.3.2            py38h4d1ce4f_1    conda-forge
mattress                  0.1.6                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4           py38h1e0a361_1002    conda-forge
mkl                       2020.2                      256    anaconda
mkl-service               2.3.0            py38h1e0a361_1    conda-forge
mock                      4.0.2            py38h32f6830_1    conda-forge
msgpack-python            1.0.0            py38hbf85e49_2    conda-forge
mypy_extensions           0.4.3            py38h32f6830_1    conda-forge
natsort                   7.0.1                      py_0    anaconda
nb_black                  1.0.7                      py_0    conda-forge
nbclient                  0.5.0                      py_0    anaconda
nbconvert                 6.0.7            py38h32f6830_0    conda-forge
nbformat                  5.0.7                      py_0    anaconda
nbsphinx                  0.7.1                    pypi_0    pypi
nbsphinx-link             1.3.0                    pypi_0    pypi
ncls                      0.0.68                   pypi_0    pypi
ncurses                   6.2                  he1b5a44_2    conda-forge
nest-asyncio              1.4.1                      py_0    anaconda
networkx                  2.5                        py_0    anaconda
ninja                     1.10.1               hc9558a2_1    conda-forge
nodeenv                   1.5.0                    pypi_0    pypi
notebook                  6.1.4            py38h32f6830_0    conda-forge
numba                     0.51.2           py38hc5bc63f_0    conda-forge
numexpr                   2.7.1            py38hc5bc63f_2    conda-forge
numpy                     1.19.2           py38hbc27379_1    conda-forge
numpy-groupies            0.9.13                   pypi_0    pypi
obonet                    0.2.6                    pypi_0    pypi
olefile                   0.46                       py_0    anaconda
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.3            py38hc5bc63f_2    conda-forge
pandoc                    2.11                 hd18ef5c_0    conda-forge
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pastel                    0.2.0                      py_0    anaconda
pathspec                  0.8.0              pyh9f0ad1d_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pep8-naming               0.10.0                   pypi_0    pypi
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    7.2.0            py38h9776b28_2    conda-forge
pip                       20.2.3                     py_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
plotly                    4.11.0                   pypi_0    pypi
pluggy                    0.13.1                   pypi_0    pypi
poetry                    1.0.10           py38h32f6830_0    conda-forge
pre-commit                2.7.1                    pypi_0    pypi
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.8                      py_0    anaconda
prospector                1.3.0                    pypi_0    pypi
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0                    pypi_0    pypi
pycairo                   1.20.0           py38h323dad1_1    conda-forge
pycodestyle               2.6.0                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydata-sphinx-theme       0.4.1                    pypi_0    pypi
pydocstyle                5.1.1                    pypi_0    pypi
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.7.1                      py_0    anaconda
pylev                     1.3.0                      py_0    anaconda
pylint                    2.5.2                    pypi_0    pypi
pylint-celery             0.3                      pypi_0    pypi
pylint-django             2.0.15                   pypi_0    pypi
pylint-flask              0.6                      pypi_0    pypi
pylint-plugin-utils       0.6                      pypi_0    pypi
pymongo                   3.11.0           py38h348cfbe_4    conda-forge
pyopenssl                 19.1.0                     py_1    anaconda
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3                   pypi_0    pypi
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
pytables                  3.6.1            py38h1b207d3_2    conda-forge
pytest                    6.1.1                    pypi_0    pypi
python                    3.8.6           h852b56e_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    anaconda
python-igraph             0.8.2            py38hb721cf7_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.2           py38ha71036d_2    conda-forge
qtconsole                 4.7.7                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.0                  he28a2e2_2    conda-forge
regex                     2020.10.11       py38h1e0a361_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
requests-toolbelt         0.8.0                      py_1    anaconda
requirements-detector     0.7                      pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
rich                      8.0.0            py38h32f6830_0    conda-forge
scanpy                    1.6.0                    pypi_0    pypi
scanpydoc                 0.5.3                    pypi_0    pypi
scikit-learn              0.23.2           py38hee58b96_0    conda-forge
scikit-misc               0.1.3                    pypi_0    pypi
scipy                     1.5.2            py38h8c5af15_1    conda-forge
scvi-tools                0.7.0b0                    py_0    bioconda
seaborn                   0.11.0                        0    conda-forge
seaborn-base              0.11.0                     py_0    conda-forge
secretstorage             3.1.2            py38h32f6830_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setoptconf                0.2.0                    pypi_0    pypi
setuptools                49.6.0           py38h924ce5b_2    conda-forge
setuptools-scm            4.1.2                    pypi_0    pypi
shellingham               1.3.2                      py_0    conda-forge
sinfo                     0.3.1                    pypi_0    pypi
singler                   0.1.2                    pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    3.2.1                    pypi_0    pypi
sphinx-autodoc-typehints  1.11.1                   pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.33.0               h4cf870e_1    conda-forge
statsmodels               0.12.0           py38h1e0a361_0    conda-forge
stdlib-list               0.7.0                    pypi_0    pypi
summarizedexperiment      0.4.3                    pypi_0    pypi
terminado                 0.9.1            py38h32f6830_0    conda-forge
testpath                  0.4.4                      py_0    anaconda
texttable                 1.6.3              pyh9f0ad1d_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    anaconda
tk                        8.6.10               hed695b0_1    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
tomlkit                   0.5.11           py38h32f6830_1    conda-forge
torch                     1.6.0                    pypi_0    pypi
tornado                   6.0.4            py38h1e0a361_2    conda-forge
tqdm                      4.50.2             pyh9f0ad1d_0    conda-forge
traitlets                 5.0.4                      py_1    conda-forge
typed-ast                 1.4.1            py38h516909a_0    conda-forge
typing-extensions         3.7.4.2                       0    anaconda
typing_extensions         3.7.4.2                    py_0    anaconda
umap-learn                0.4.6                    pypi_0    pypi
urllib3                   1.25.10                    py_0    anaconda
virtualenv                20.0.34                  pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                    py38_1    anaconda
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.5.1            py38h32f6830_1    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
xlrd                      1.2.0              pyh9f0ad1d_1    conda-forge
xlsxwriter                1.3.6                    pypi_0    pypi
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.3                he1b5a44_2    conda-forge
zipp                      3.3.0                      py_0    anaconda
zlib                      1.2.11            h516909a_1009    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

**Comment by martinkim0** [comment]
Hi, what kind of import error are you getting?

**Comment by Sirin24** [comment]
Thank you for your fast reply. I copied it below. I am not sure why when I try to import scvi it attempts to read an h5ad file.

[sir@lm602-20 scvi_folder]$ conda activate py-env
(/user/conda-environments/py-env) [sir@lm602-20 scvi_folder]$ python
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scanpy as sc
>>> import scvi
Traceback (most recent call last):
  File "/user/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/user/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 510, in read_group
    EncodingVersions[encoding_type].check(
  File "/user/conda-environments/py-env/lib/python3.8/enum.py", line 355, in __getitem__
    return cls._member_map_[name]
KeyError: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/user/brainref/scvi_folder/scvi.py", line 5, in <module>
    ref_adata=sc.read_h5ad('/user/brainref/a5463d8f-07df-4870-8cae-bc504de762c8.h5ad')
  File "/user/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 413, in read_h5ad
    d[k] = read_attribute(f[k])
  File "/user/conda-environments/py-env/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/user/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/utils.py", line 162, in func_wrapper
    raise AnnDataReadError(
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.

**Comment by martinkim0** [comment]
What version of scvi-tools is it installing? We don't support Python 3.8 in our latest versions. This might be the source of the issue, I'd recommend making sure that you're installing scvi-tools>=1.1.0

**Comment by canergen** [comment]
It says that you have a file called scvi in your folder. Please rename this file: `/user/brainref/scvi_folder/scvi.py`. Local files have a higher priority during import than installed modules.

**Comment by canergen** [comment]
To add, you currently can't read this file as there is a version conflict between anndata (likely your current environment has an older version of anndata than the one used to create the file).
