### ISSUE TITLE
benign typo in kwarg

### ISSUE THREAD

**Issue by ghwatson** [scverse/scvi-tools#2720]
typo in this line for a kwarg: https://github.com/scverse/scvi-tools/blob/95f2e1d2fa921c6433a04e257d844280ba0c25e5/scvi/train/_callbacks.py#L112

note this doesn't manifest as a bug. the default behaviour for save has save_anndata set to False already.

**Comment by martinkim0** [comment]
Thanks for pointing that out! Not sure how that made past our tests...
