### ISSUE TITLE
 Assistance Required with scvi-tools GPU Setup on Ubuntu

### ISSUE THREAD

**Issue by qweasdf1354** [scverse/scvi-tools#2754]
Dear scvi-tools Team,

I am currently experiencing issues with setting up scvi-tools to run on a GPU on my Ubuntu system, and I am seeking your assistance to resolve this problem.

I have successfully installed scvi-tools and am able to import the package and run models using CPU. However, I am unable to utilize the GPU capabilities, and the issue appears to be related to JAX and CUDA compatibility.

My system details are as follows:

OS: Ubuntu 22.04
Python environment: Miniforge3
CUDA versions tried: 11.8, 12.0, 12.1, 12.2
Despite trying multiple versions of CUDA, I am encountering an issue with cuSPARSE version mismatches. The error indicates that JAX requires cuSPARSE version 12200, but my setup only supports version 12002. I have been unable to find a solution through online installation guides.

Could you please advise on the recommended installation procedure for ensuring scvi-tools works with GPU acceleration on my system? Any specific versions of CUDA, cuDNN, or other dependencies that you recommend would be greatly appreciated.

Thank you for your assistance and for the excellent work on scvi-tools.

Best regards,

```python
# Your code here
```

```pytb
[Paste the error output produced by the above code here]
```

#### Versions:

> VERSION

**Comment by qweasdf1354** [comment]
I just follow the latest installation guide page and i turn to the JAX page to install jax using the following 
pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

and
pip install "scvi-tools[tutorials]"

it could not using GPU in my computuer.

**Comment by martinkim0** [comment]
Take this with a grain of salt since we may have different system packages, but I'm on Ubuntu 22.04.4 with Nvidia driver version 550.54.15 and CUDA 12.4, and the following commands give me a working scvi-tools GPU environment in Miniforge3 (checked today using a cold cache):
```
conda create -n scvi-env python=3.11
conda activate scvi-env

pip install -U uv
uv pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
uv pip install --upgrade torch torchvision torchaudio
uv pip install --upgrade scvi-tools
```
Note that I'm using uv here for installation, but it should be the same with pip. 

Is there a particular reason that you're also installing all the tutorial dependencies? Sometimes installing these extra dependencies can mess up previous ones, and most tutorials can just be run without them.

**Comment by martinkim0** [comment]
Also for future reference, this would be a great question to post on our [Discourse](https://discourse.scverse.org/)! We prefer to have bug reports and feature requests only on GitHub issues.

I'm going to go ahead and close this issue then, but please feel free to follow up, and I'll try to help.

**Comment by qweasdf1354** [comment]
Thank you so much for your prompt help. I appreciate your suggestion and understand your reasoning. Initially, I chose to use "scvi-tools[tutorials]" primarily for its convenience, as it comes with Jupyter notebooks integrated, which simplifies my workflow. However, I agree with your perspective and will attempt the approach you recommended.

Thank you once again for providing such an excellent tool. I will make sure to keep you updated with any feedback or issues as I proceed.

**Comment by qweasdf1354** [comment]
I try it using pip and there are no error prompt but it is likely GPU not use 

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/ps/miniforge3/envs/scvi-env/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=127` in the `DataLoader` to improve performance.
Epoch 11/364:   3%| | 10/364 [00:21<12:30,  2.12s/it, v_num=1, train_loss_step=7

**Comment by qweasdf1354** [comment]
Above results are the generate by following code

```
scvi.model.SCVI.setup_anndata(adata)
vae = scvi.model.SCVI(adata)
vae.train()
```

My CPU is 8383C*2 which have many core, but it seems only one core is using. But it may not the major. The GPU utility is also low and it seems not activate. I checking it by nvidia-smi -l

**Comment by qweasdf1354** [comment]
I am successfully install and train without error. However, the GPU utility is remain low about 5-8%. A dataset around 20000*2000 will take 14 minutes. I am not sure is that normal. Thanks!

**Comment by canergen** [comment]
Both numbers are reasonable. You can increase the batch_size in train (which is safe up to 1024 cells for large datasets). This increases GPU usage. Warning: For small datasets (below 200k cells), this is not extensively tested and might reduce performance. You could also reduce the number of epochs. However, I would suggest waiting for the time it takes to train the model. ScVI is a small model that doesn't fully use a single GPU (it's due to the number of parameters). Downstream steps like clustering and annotating datasets is significantly more time-consuming in most applications.

**Comment by qweasdf1354** [comment]
Thank you!

**Comment by qweasdf1354** [comment]
I am not sure the time 10 minutes is means i am setting or installing the scvi correct. I see some video pipeline using the scvi and the speed is fast than me and the datasets is bigger than me. I know it may depending on many aspect, however I want to say the speed is the same i use the CPU training when the cuda and jax not correct install.
I am worry about the following trainning maybe DE or some will take me longer without or may not correct train using GPU.

the following is the code

`import os
import tempfile

import scanpy as sc
import scvi
import seaborn as sns
import torch

torch.set_float32_matmul_precision("high")

scvi.model.SCVI.setup_anndata(adata)
vae = scvi.model.SCVI(adata)
vae.train()`

the following is the output

```
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/ps/miniforge3/envs/scvi-env/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=127` in the `DataLoader` to improve performance.
Epoch 364/364: 100%|█| 364/364 [12:52<00:00,  2.10s/it, v_num=1, train_loss_step
`Trainer.fit` stopped: `max_epochs=364` reached.
Epoch 364/364: 100%|█| 364/364 [12:52<00:00,  2.12s/it, v_num=1, train_loss_step
```

Thanks you
