### ISSUE TITLE
Can we have a scVI with reconstruction distirbution as normal distribution?

### ISSUE THREAD

**Issue by HelloWorldLTY** [scverse/scvi-tools#2755]
Hi, I am interested in the implementation of scVI with normal distirbution as reconstruction distribution. I think this setting is meaningful for the dataset that we can only retrieve the normalized results. If I directly replace the reonstruction distribution with normal distribution, there will be an error. Thanks a lot.

**Comment by martinkim0** [comment]
We don't plan on implementing this for now as we haven't tested or benchmarked it on our end. Would be happy to take a PR with an implementation if you're willing to contribute, though!

**Comment by canergen** [comment]
Hi, you might want to check e.g. scGEN from Theis lab, which uses MSE as the default and only loss. I don't want to include a model that starts with some transformed data. The issue in my opinion is that we can't cover all types of data preprocessing and ensure that it works (scaling, log1p, Poisson residual, and others).

**Comment by martinkim0** [comment]
Closed via #2780
