### ISSUE TITLE
AttributeError: module 'scvi' has no attribute 'autotune'

### ISSUE THREAD

**Issue by itamarb-cgen** [scverse/scvi-tools#2784]
autotune fails with an error message _no attribute 'autotune'_.
I created a fresh conda environment with the latest scvi-tools on python 3.11.
Please advise,
Itamar

```python
tuner = scvi.autotune.ModelTuner(model_cls)
tuner
```

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[15], line 1
----> 1 tuner = scvi.autotune.ModelTuner(model_cls)
      2 tuner

AttributeError: module 'scvi' has no attribute 'autotune'
```

#### Versions:
```python
print (scvi.__version__)
```
> 1.1.2
```python
sc.logging.print_header()
```
> scanpy==1.10.1 anndata==0.10.7 umap==0.5.5 numpy==1.26.4 scipy==1.13.0 pandas==2.2.2 scikit-learn==1.4.2 statsmodels==0.14.1 igraph==0.11.5 pynndescent==0.5.12

**Comment by martinkim0** [comment]
Hi, please try `from scvi.autotune import ModelTuner`

**Comment by itamarb-cgen** [comment]
Thank you Martin!
This indeed helped proceed. 
Note that a few more installations are needed: 
`conda install hyperopt
pip install "ray[tune]"
`
with 
`from ray import tune`

Unfortunately, I encounter another error later in `tuner.fit`:
'ValueError: Grid search parameters cannot be automatically converted to a HyperOpt search space.'
What can be the problem here?
Best regards,
Itamar

**Comment by martinkim0** [comment]
Closed due to inactivity
