### ISSUE TITLE
poor integration effect cross species

### ISSUE THREAD

**Issue by GGboy-Zzz** [scverse/scvi-tools#2788]
I am using scvi to integrate single-cell data from zebrafish and human embryos. According to the default parameters of SCVI, I obtained a very poor integrated UMap, similar to not integrated. Is there any parameter to adjust this result?
![image](https://github.com/scverse/scvi-tools/assets/76716539/4f729c93-3553-40ac-8a1e-d8adb56dda2f)
my code as belows, 
[Untitled.md](https://github.com/scverse/scvi-tools/files/15270073/Untitled.md)

**Comment by canergen** [comment]
Cross-species integration is not really within the scope of scVI. For a similar model (VAE), optimized for cross-species integration, I would recommend looking into: https://www.nature.com/articles/s41592-024-02191-z.
If you still want to benchmark scVI within this framework, you can post a question on our discourse forum.

**Comment by GGboy-Zzz** [comment]
ok, thanks for your answer, I will try to discuss it in discourse forum.

**Comment by francicco** [comment]
Hi @GGboy-Zzz ,

I actually have the same problem, did you find a solution? 
scVI and scANVI were used for cross-species integration https://www.nature.com/articles/s41467-023-41855-w
I'm so confused!
Cheers
F

**Comment by canergen** [comment]
The code above was correct. While scVI/scANVI can be applied to integrate data across species (if gene names are harmonized), we can’t provide further guidance on it. IMO it is not the correct model (to little forced batch correction). SysVI which is an open PR in scVI-tools has some good benchmarks on cross-species integration: https://www.biorxiv.org/content/10.1101/2023.11.03.565463v2

**Comment by GGboy-Zzz** [comment]
Yes, I found that scVI and scANVI can't work well in intetrating distance species. I think you can try other mthods such as Saturn or SAMap, Perhaps it is more suitable.
