### ISSUE TITLE
Issues installing recommended packages

### ISSUE THREAD

**Issue by bykovam** [scverse/scvi-tools#2800]
I'm trying to follow installation requirements and recommendations for scvi-tools, and I'm installing packages within Anaconda Prompt on a Windows system. The readout as as follows when trying to run "conda install jax jaxlib -c conda-forge"

(Scvi_Tools_V_05_15_2024) C:\Users\BYKOVAM>conda install jax jaxlib -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - jaxlib

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch

In addition, running "conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia" produces

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

**Comment by martinkim0** [comment]
Hi, I've generally had more success these days relying on pip for installing PyTorch and JAX. I think the following should work on a Windows machine (if you don't intend on using an Nvidia GPU):
```bash
pip install -U "jax[cpu]"
pip install -U torchvision torchaudio torchvision
```
If you're attempting to use a GPU, [JAX](https://jax.readthedocs.io/en/latest/installation.html#supported-platforms) does not have a stable build currently while for PyTorch, the command would be:
```bash
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
# or depending on your cuda version
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```

**Comment by bykovam** [comment]
Thanks! I'll test it out later and report back on the results.

**Comment by bykovam** [comment]
Unrelated, but I love the tracksuit Shiba Inu profile pic

**Comment by canergen** [comment]
Closed due to inactivity.
