### ISSUE TITLE
different hidden unit in each layer

### ISSUE THREAD

**Issue by verao-amy** [scverse/scvi-tools#2804]
Is it possible to use different number of hidden units in different layers? For example, 128 hidden unites in layer1, 64 hidden units in layer2 and 30 latent variables.
How should we code that?

**Comment by martinkim0** [comment]
Hi, this is currently not possible - we've decided not to support this for the sake of simplicity of the user API. If you'd like to implement this for your purposes, it should be straightforward to modify [`FCLayers`](https://github.com/scverse/scvi-tools/blob/main/src/scvi/nn/_base_components.py#L15) using an [editable install](https://docs.scvi-tools.org/en/latest/developer/code.html) of scvi-tools.
