### ISSUE TITLE
bug for custom classifier in adversarial training plan 

### ISSUE THREAD

**Issue by SabrinaRichter** [scverse/scvi-tools#2810]
When trying to use a custom classifier in the adversarial training plan, i get an `scvi 'AdversarialTrainingPlan' object has no attribute 'n_output_classifier'` error, I think because it's not set here https://github.com/scverse/scvi-tools/blob/dcadecbc26979af916b92ba07c979535a4a32a48/src/scvi/train/_trainingplans.py#L526 similar to the case above, but it's used 6 lines further down.

**Comment by canergen** [comment]
Hi, thanks for trying to build on top of scVI-tools. To give a reasonable response, we will need more background than ‚custom classifier‘. What are you trying to do and how do you define it?
The easiest would be to add an additional batch key for adversarial training and I can share code for this.

**Comment by canergen** [comment]
Closed due to inactivity.
