### ISSUE TITLE
Exception has occurred: ImportError cannot import name 'REGISTRY_KEYS' from 'scvi'

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [scverse/scvi-tools#2833]
Whenever I try to import scvi in a remote explorer (in a server) I get the error below; Happens with both venv and conda install via pip

Nothing to reproduce, simply importing it causes this error

```pytb
Exception has occurred: ImportError cannot import name 'REGISTRY_KEYS' from 'scvi'
```

#### Versions:

> latest version of scvi and scvi-tools (already reinstalled it)

**Comment by martinkim0** [comment]
Hi, could you try clearing the conda/pip cache (``conda clean -ayf`` and ``pip cache purge``) and reinstalling again? If this doesn't work, I can help further debug this.

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi, could you try clearing the conda/pip cache (`conda clean -ayf` and `pip cache purge`) and reinstalling again? If this doesn't work, I can help further debug this.

Hey, I got it fixed already, I think I had both scvi and scvi-tools installed (scvi is no longer being used from what I was reading) and I just crated a brand new venv and reinstalled everything (without scvi) and it's working now, thank you

**Comment by martinkim0** [comment]
Great to hear! I'm going to go ahead and close the issue then.
