### ISSUE TITLE
Discussion thread: New DestVI model that supports Visium HD (single-cell spatial transcriptomics) data - Timeline, releases and alternatives

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [scverse/scvi-tools#2840]
Hey everyone!

In this thread https://github.com/scverse/scvi-tools/issues/2830 with @canergen it was mentioned a release of a new DestVI model that would be compatible with single-cell spatial data (such as Visium HD that has 2 micron bins/spots, resulting in well over 650k bins/observations). The current model seems to not be able to capture this sparse data and I don't think it has been optimized for this much data either (I tried training 15 epochs with GPU and it took 2 hours with the 8 micron resolution - 580k bins/"spots").

I've been testing my own implementations on "deconvolution" using annotated scRNA datasets and the new HD data (10X Visium datasets) doing:
- Extracting top cell markers from the reference scRNA for each cell type, and identify these same markers on the sc-ST data, take the average of them and then associate the cell type for that given bin with the highest average of log norms. This does capture the patterns, but it doesn't seem to be the best optimal way to go about this. I've also tried adjusting the lognorms by the spatial connectivities so it captures some spatial information in the mix, and this increased the "intensity" of the bins (bins that are closer together, will have their adjusted log norms uplifted by the spatial connectivities which consider neighbor bins)
- I've tried using LGBM models and using once again cell markers extraction methods as a method of dimensionality reduction. This way I go from 15k genes + to around 400 genes that were found to be markers for the cell types in the reference scRNA. However, I am not sure how well this translates into the spatial data either (see pictures below);

With this being said, I'm quite confident the new DestVI model could be a nice added feature to deconvolute/map sc-ST data from an annotated scRNA reference (or even unsupervised model, perhaps); 

Is there any timeline for when this would be release? Quite excited to test it out as I'm also trying to come up with a feasible solution for cell deconvolution on such granular/high resolution data 

Any ideas as well on this?

Thank you!

For reference, leaving some images here of my attempts:

Left: Predictions using LGBM model and cell markers as a dimensionality reduction method; Right: average of log norms of the top cell markers for that given cell type. The predictions seem to follow the patterns seen in the average of the log norms of cell markers for a given cel type, but not sure if this would be a good approach; Besides, cell types that are not well represented, no longer have those patterns captured (my training data has 1500 cells, and some only had 10-15 observations for a given cell type, so those naturally are not predicted well - this method is highly dependent on the training data, and I was hoping the new destVI would solve this)
![image](https://github.com/scverse/scvi-tools/assets/70116258/c2fca808-39ea-492b-9dc1-6cd979472008)
![image](https://github.com/scverse/scvi-tools/assets/70116258/32f06a61-9e42-48ec-8ab6-1cacf1ff0c02)
![image](https://github.com/scverse/scvi-tools/assets/70116258/f6cec639-0981-483b-a44d-ce2b50ffe952)

Cell type assignment using the top/highest 10% averages from the cell markers for each cell type, with experssion matrix adjusted by their spatial connectivities:
![image](https://github.com/scverse/scvi-tools/assets/70116258/8cf4dd7e-ac7e-4c17-bc49-97328365551f)

**Comment by canergen** [comment]
Hi, DestVI also after enhancements is still an expensive algorithm (for each spot it has to decode to each cell-type leading to a high compute time). Increasing batch size also has it's limitations specifically in DestVI.
TACCO (https://www.nature.com/articles/s41587-023-01657-3) is the most scalable deconvolution algorithm to my knowledge and it might be a good starting point. I think identifyinf marker genes is a justified approach though. Also the Visium HD preprint uses publication and it might be a good starting point to do the analysis (https://www.biorxiv.org/content/10.1101/2024.06.04.597233v1).
Timelines are somewhat hard to predict. We will post it on X/biorxiv.

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi, DestVI also after enhancements is still an expensive algorithm (for each spot it has to decode to each cell-type leading to a high compute time). Increasing batch size also has it's limitations specifically in DestVI. TACCO (https://www.nature.com/articles/s41587-023-01657-3) is the most scalable deconvolution algorithm to my knowledge and it might be a good starting point. I think identifyinf marker genes is a justified approach though. Also the Visium HD preprint uses publication and it might be a good starting point to do the analysis (https://www.biorxiv.org/content/10.1101/2024.06.04.597233v1). Timelines are somewhat hard to predict. We will post it on X/biorxiv.

Thank you for the reply! I've read their preprint paper, but they use very little amount of samples and they do a type of overclustering that is already done in scRNA; But this isn't scalable with lots of samples (I'd like something more automatic, thus the modelling approach). I will have a look at TACCO!
