### ISSUE TITLE
autotune throws error for ContrastiveVI (and possibly other external modules)

### ISSUE THREAD

**Issue by LinearParadox** [scverse/scvi-tools#2906]
When creating a tuner from a contrastiveVI object, an error is thrown due to the object missing the \_\_name\_\_ attribute.

```python

scvi.external.ContrastiveVI.setup_anndata(adata, layer="counts", batch_key='sample_id')
contrastive_vi_model = scvi.external.ContrastiveVI(
    adata, 
    n_salient_latent=10, 
    n_background_latent=10, 
    use_observed_lib_size=False,
)
scvi_tuner = autotune.ModelTuner(contrastive_vi_model)

```

```pytb
AttributeError: 'ContrastiveVI' object has no attribute '__name__'

```

#### Versions:

'1.1.2'

**Comment by canergen** [comment]
Hi, I can't reproduce this error in Colab (can you check my notebook below and see that it works for you).
However, be aware that several elements of ContrastiveVI are not setup to be tuned (all model parameters, while train parameters can be tuned).
https://colab.research.google.com/drive/18x9Nwh6Ql0_2MVMnjx2E00hJ8h8NPFOe
