### ISSUE TITLE
Incompatibility with new anndata 0.10.9

### ISSUE THREAD

**Issue by mehrankr** [scverse/scvi-tools#2953]
# Issue

There is a new anndata release incompatible with scVI

# Error message

```
> import scvi
ImportError: cannot import name 'AlignedViewMixin' from 'anndata._core.aligned_mapping' (/local_disk0/.ephemeral_nfs/envs/pythonEnv-41a17f4f-ae47-4ddc-a406-410dcbd282df/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py)
```
# Temporary fix

Pin down anndata:

`pip install anndata==0.10.8`

**Comment by canergen** [comment]
Hi, thanks for posting this. Please read the full error and post it as it makes it easier to figure out what's causing this. I opened the issue for MuData as it seems like this is causing the issue: https://github.com/scverse/mudata/issues/77.

**Comment by canergen** [comment]
Fixed in MuData.

**Comment by ori-kron-wis** [comment]
please start a clean new conda env and install scvi-tools 1.3 , it will install the needed packages and should be ok

**Comment by jflusche** [comment]
Hello, thanks for the response! I tried this and after re-installing scvi (version 1.3.0) and anndata (version 0.11.3) I still am getting the same error. Do you have any other suggestions? Thanks.

**Comment by canergen** [comment]
Your issue here is MuData and not AnnData or scvi-tools. Can you verify that the issue arises when you just import MuData and then follow their installation guideline?

**Comment by jflusche** [comment]
The same issue does arise when I import MuData. 

`import mudata as md
from mudata import MuData`

ImportError: cannot import name 'AlignedViewMixin' from 'anndata._core.aligned_mapping' (/home/jupyter/.local/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py)

**Comment by jflusche** [comment]
Hi! Just following up on this issue. Do you have any suggestions on where to go from here? I get the same error when I follow MuData installation guideline. Should I reach out to the MuData team for assistance? Thank you for your help thus far.

`ImportError: cannot import name 'AlignedViewMixin' from 'anndata._core.aligned_mapping'`

**Comment by ori-kron-wis** [comment]
Like I suggested before, please start a clean new conda env and install scvi-tools 1.3 , it will install the needed packages for both anndata and mudata and should be ok. Use python 3.12.

**Comment by jflusche** [comment]
Hi, thank you for your suggestions! I wanted to follow up with what worked for solving this issue. I upgraded MuData to the newest version 0.3.1, which is compatible with scvi version 1.3.0. I also wanted to note that in order to load existing scvi models I had to downgrade pandas to version 1.5.3.

**Comment by joeyQX** [comment]
I have the same error, and there is no use of pip install anndata==0.10.8. Moreover, my MuData is the newest version 0.3.2

**Comment by ori-kron-wis** [comment]
@joeyQX Im not quite following,  but anndata 0.10.x is at least 1 year old, and we can make certain it will be supported with most recent scvi-tools (e.g 1.4.x).
I suggest starting a clean environment and setting up scvi-tools, which will automatically install all other needed packages correct versions.
Let me know if you have other questions.

**Comment by joeyQX** [comment]
> [@joeyQX](https://github.com/joeyQX) Im not quite following, but anndata 0.10.x is at least 1 year old, and we can make certain it will be supported with most recent scvi-tools (e.g 1.4.x). I suggest starting a clean environment and setting up scvi-tools, which will automatically install all other needed packages correct versions. Let me know if you have other questions.

thx!
