### ISSUE TITLE
installation error when import scvi in conda/pip

### ISSUE THREAD

**Issue by biobai** [scverse/scvi-tools#2955]
Hi all
I follow the Installation (https://docs.scvi-tools.org/en/stable/installation.html)
```bash
mamba create -n scvi-env python=3.9
mamba activate scvi-env
mamba install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
mamba install jax jaxlib -c conda-forge
mamba install scvi-tools -c conda-forge
```
or
```bash
pip install scvi-tools
```
How to fix this error?
```python
Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import scvi
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 import scvi

File ~/miniforge3/envs/scvi-env/lib/python3.9/site-packages/scvi/__init__.py:11
      8 from ._settings import settings
     10 # this import needs to come after prior imports to prevent circular import
---> 11 from . import data, model, external, utils
     13 from importlib.metadata import version
     15 package_name = "scvi-tools"

File ~/miniforge3/envs/scvi-env/lib/python3.9/site-packages/scvi/data/__init__.py:3
      1 from anndata import read_csv, read_h5ad, read_loom, read_text
----> 3 from ._anntorchdataset import AnnTorchDataset
      4 from ._datasets import (
      5     annotation_simulation,
      6     brainlarge_dataset,
   (...)
     22     synthetic_iid,
     23 )
     24 from ._manager import AnnDataManager, AnnDataManagerValidationCheck
File ~/miniforge3/envs/scvi-env/lib/python3.9/site-packages/scvi/data/_anntorchdataset.py:23
     20 from torch.utils.data import Dataset
     22 from scvi._constants import REGISTRY_KEYS
---> 23 from scvi.utils._exceptions import InvalidParameterError
     25 if TYPE_CHECKING:
     26     from ._manager import AnnDataManager

File ~/miniforge3/envs/scvi-env/lib/python3.9/site-packages/scvi/utils/__init__.py:6
      4 from ._docstrings import de_dsp, setup_anndata_dsp
      5 from ._exceptions import InvalidParameterError
----> 6 from ._jax import device_selecting_PRNGKey
      7 from ._track import track
      9 __all__ = [
     10     "track",
     11     "setup_anndata_dsp",
   (...)
     18     "dependencies",
     19 ]

File ~/miniforge3/envs/scvi-env/lib/python3.9/site-packages/scvi/utils/_jax.py:3
      1 from typing import Callable
----> 3 import jax
      4 from jax import random
      7 def device_selecting_PRNGKey(use_cpu: bool = True) -> Callable:

File ~/miniforge3/envs/scvi-env/lib/python3.9/site-packages/jax/__init__.py:25
     22 from jax.version import __version_info__ as __version_info__
     24 # Set Cloud TPU env vars if necessary before transitively loading C++ backend
---> 25 from jax._src.cloud_tpu_init import cloud_tpu_init as _cloud_tpu_init
     26 try:
     27   _cloud_tpu_init()

File ~/miniforge3/envs/scvi-env/lib/python3.9/site-packages/jax/_src/cloud_tpu_init.py:37
     33   else:
     34     return libtpu
---> 37 def get_tpu_library_path() -> str | None:
     38   path_from_env = os.getenv("TPU_LIBRARY_PATH")
     39   if path_from_env is not None and os.path.isfile(path_from_env):

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by yz3n18** [comment]
Hi! I had a similar problem while following the installation tutorial.
Reinstalling the flax package with version 0.8.5 solved the issue. You can do this by running:
`pip install flax==0.8.5`
Hope this helps.


> TypeError                                 Traceback (most recent call last)
> Cell In[1], line 4
>       2 import tempfile
>       3 import scanpy as sc
> ----> 4 import scvi
>       5 import seaborn as sns
>       6 import torch
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/scvi/__init__.py:11
>       8 from ._settings import settings
>      10 # this import needs to come after prior imports to prevent circular import
> ---> 11 from . import data, model, external, utils
>      13 from importlib.metadata import version
>      15 package_name = "scvi-tools"
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/scvi/data/__init__.py:25
>       4 from ._datasets import (
>       5     annotation_simulation,
>       6     brainlarge_dataset,
>    (...)
>      22     synthetic_iid,
>      23 )
>      24 from ._manager import AnnDataManager, AnnDataManagerValidationCheck
> ---> 25 from ._preprocessing import (
>      26     add_dna_sequence,
>      27     organize_cite_seq_10x,
>      28     organize_multiome_anndatas,
>      29     poisson_gene_selection,
>      30     reads_to_fragments,
>      31 )
>      32 from ._read import read_10x_atac, read_10x_multiome
>      34 __all__ = [
>      35     "AnnTorchDataset",
>      36     "AnnDataManagerValidationCheck",
>    (...)
>      66     "cellxgene",
>      67 ]
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/scvi/data/_preprocessing.py:12
>       9 import torch
>      10 from scipy.sparse import issparse
> ---> 12 from scvi.model._utils import parse_device_args
>      13 from scvi.utils import dependencies, track
>      14 from scvi.utils._docstrings import devices_dsp
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/scvi/model/__init__.py:2
>       1 from . import utils
> ----> 2 from ._amortizedlda import AmortizedLDA
>       3 from ._autozi import AUTOZI
>       4 from ._condscvi import CondSCVI
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/scvi/model/_amortizedlda.py:15
>      13 from scvi.data import AnnDataManager
>      14 from scvi.data.fields import LayerField
> ---> 15 from scvi.module import AmortizedLDAPyroModule
>      16 from scvi.utils import setup_anndata_dsp
>      18 from .base import BaseModelClass, PyroSviTrainMixin
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/scvi/module/__init__.py:1
> ----> 1 from ._amortizedlda import AmortizedLDAPyroModule
>       2 from ._autozivae import AutoZIVAE
>       3 from ._classifier import Classifier
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/scvi/module/_amortizedlda.py:15
>      13 from scvi._constants import REGISTRY_KEYS
>      14 from scvi._types import Tunable
> ---> 15 from scvi.module.base import PyroBaseModuleClass, auto_move_data
>      16 from scvi.nn import Encoder
>      18 _AMORTIZED_LDA_PYRO_MODULE_NAME = "amortized_lda"
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/scvi/module/base/__init__.py:1
> ----> 1 from ._base_module import (
>       2     BaseMinifiedModeModuleClass,
>       3     BaseModuleClass,
>       4     JaxBaseModuleClass,
>       5     LossOutput,
>       6     PyroBaseModuleClass,
>       7     TrainStateWithState,
>       8 )
>       9 from ._decorators import auto_move_data, flax_configure
>      11 __all__ = [
>      12     "BaseModuleClass",
>      13     "LossOutput",
>    (...)
>      19     "BaseMinifiedModeModuleClass",
>      20 ]
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/scvi/module/base/_base_module.py:8
>       5 from dataclasses import field
>       6 from typing import Any, Callable
> ----> 8 import flax
>       9 import jax
>      10 import jax.numpy as jnp
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/flax/__init__.py:24
>      21 config: configurations.Config = configurations.config
>      22 del configurations
> ---> 24 from flax import core
>      25 from flax import jax_utils
>      26 from flax import linen
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/flax/core/__init__.py:15
>       1 # Copyright 2024 The Flax Authors.
>       2 #
>       3 # Licensed under the Apache License, Version 2.0 (the "License");
>    (...)
>      12 # See the License for the specific language governing permissions and
>      13 # limitations under the License.
> ---> 15 from .axes_scan import broadcast as broadcast
>      16 from .frozen_dict import (
>      17     FrozenDict as FrozenDict,
>      18     copy as copy,
>    (...)
>      22     unfreeze as unfreeze,
>      23 )
>      24 from .lift import (
>      25     custom_vjp as custom_vjp,
>      26     jit as jit,
>    (...)
>      33     while_loop as while_loop,
>      34 )
> 
> File ~/.conda/envs/scvi-env/lib/python3.9/site-packages/flax/core/axes_scan.py:41
>      31   pass
>      34 broadcast = _Broadcast()
>      37 def scan(
>      38   fn: Callable[..., Any],
>      39   in_axes: Any,
>      40   out_axes: Any,
> ---> 41   length: int | None = None,
>      42   reverse: bool = False,
>      43   unroll: int = 1,
>      44   _split_transpose: bool = False
>      45 ):
>      46   """A wrapper around `jax.lax.scan` with in_axes/out_axes api.
>      47 
>      48   Example::
>    (...)
>      83      (broadcast_in, carry_in, *args) -> (broadcast_out, carry_out, scan_out).
>      84   """
>      86   def transpose_to_front(ax, xs):
> 
> TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by canergen** [comment]
Thanks. I think both are unrelated (the one you are highlighting is in flax and the one originally described is in device management). Unfortunately, jax and its subpackages sometimes create version conflicts. There is little we can do to fix it except being compatible with the most recent jax version. If jax is correctly installed those issues both should be gone.
