### ISSUE TITLE
potential issue with zinb / nb loss

### ISSUE THREAD

**Issue by jkobject** [scverse/scvi-tools#2965]
Hi,

I have had some issues using the zero inflated negative binomial as well as the negative binomial loss from scvi. They seem to have issues of convergence and overflow. I have made an example notebook here [test_zinb.ipynb](https://scverse.zulipchat.com/user_uploads/41224/OKtSWovIUA-aVxp0rYTWm-p5/test_zinb.ipynb) but also talk about it in my the methods section of my manuscript: https://www.biorxiv.org/content/10.1101/2024.07.29.605556v1

It seems that there cannot be convergence to 0 but roughly 1.1 (depending on read depth) and that the model is not pushed to predict the exact values as the loss values don't change around some prediction accuracy. Worse, the loss can get even better with some error in the prediction of the mu. (see example with an error) Worse even, above some values of inverse dispersion (10_000), the use of logGamma causes overflow error and the loss to be nonsensical.

There might be something I did not understood on my end or don't do right. But I think the fact that the log gamma are used is an issue and causes imprecisions. I would be happy to work on this otherwise as I think it is quite important to get right.

Best,

**Comment by jkobject** [comment]
reuploading the notebook: https://gist.github.com/jkobject/35eefa7ca3c314e6d13bbc1070d4c15b

**Comment by canergen** [comment]
Continuing the discussion in our Zulip chat.

**Comment by canergen** [comment]
Closing here. If anyone wants to follow it, you can join the scverse Zulip channel. To summarize, our loss provides similar results to the torch NB loss. This is not an implementation error but it's not clear that NB is optimal for all applications.
