### ISSUE TITLE
change 1.1.6 release requirements

### ISSUE THREAD

**Issue by ori-kron-wis** [scverse/scvi-tools#2967]
we should re-release 1.1.6. with 2 changes to able to meet RTD autotune requirements as well as the conda forge recipe:
- Drop lightning upper bound -  see https://github.com/conda-forge/scvi-tools-feedstock/issues/54
- Add optional setuptools<=69.5.1 for tune parrt so RTD will work for the autotune version that is still in use for scvi 1.1.x
- finally, we should also increment this build number to 2 (if continue the same release, otherwise, we can release as 1.1.6.post1)

**Comment by canergen** [comment]
@jdblischak Our idea was to release 1.1.6.post1. Would this work for conda or should we change the build of 1.1.6 and release 1.1.7 without those requirements? I'm slightly puzzled about the feedstock rules.

**Comment by ori-kron-wis** [comment]
close https://github.com/scverse/scvi-tools/pull/2969

**Comment by jdblischak** [comment]
> Our idea was to release 1.1.6.post1. Would this work for conda

@canergen Yes, that version number is fine. Any valid Python package version should also be a valid [conda recipe version](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#package-version).

**Comment by jdblischak** [comment]
Confirming my understanding.

1.1.6post1 dropped the `lightning<2.2` upper bound via https://github.com/scverse/scvi-tools/pull/2969:

https://github.com/scverse/scvi-tools/compare/1.1.6...1.1.6.post1

And 1.1.6post2 also added the upper bound `anndata<=0.10.8` via https://github.com/scverse/scvi-tools/pull/2971: 

https://github.com/scverse/scvi-tools/compare/1.1.6.post1...1.1.6.post2
