### ISSUE TITLE
ValueError: "high is out of bounds for int32" when running setup_anndata on large AnnData object

### ISSUE THREAD

**Issue by Ron-bio** [scverse/scvi-tools#2968]
I encountered a `ValueError: high is out of bounds for int32` when using `scvi.model.SCVI.setup_anndata` on a large AnnData object that contains more than 200,000,000 cells. If I subset the anndata, the error no longer exists. 

```python
scvi.model.SCVI.setup_anndata(adata, layer='counts', batch_key="batch")
```

```pytb
[
...scvi\data\_utils.py:271, in _check_nonnegative_integers(data, n_to_check)
    269 ret = True
    270 if len(data) != 0:
--> 271     inds = np.random.choice(len(data), size=(n_to_check,))
    272     check = jax.device_put(data.flat[inds], device=jax.devices("cpu")[0])
    273     negative, non_integer = _is_not_count_val(check)...

ValueError: high is out of bounds for int32]
```

#### Versions:

> Last run with scvi-tools version: 1.1.6

**Comment by canergen** [comment]
Hi, curious to hear more about the performance of scvi-tools on this huge dataset and am happy to give more guidance on running it. It looks like you use a 32-bit python here. Can you confirm this with:
```
import platform
platform.architecture()[0]
```
If the error persists on a 64-bit python version. Can you also update to the most recent scvi-tools version from main? This code block was slightly updated for our 1.2 release and the error might be fixed there.

**Comment by Ron-bio** [comment]
Hi @canergen,

Thank you so much for your prompt response and the guidance!

I have tried the ```platform.architecture()[0]``` command, and the output is ```64bit```, so it seems the issue is not related to a 32-bit Python version.
As for the scvi-tools version, I noticed that the 1.2 version is currently in an unreleased state. The 1.1.6 version was installed through ```pip install scvi-tools```
Looking forward to your advice and suggestions!

**Comment by canergen** [comment]
In a 64-bit numpy the error is (so 200 million cells would be no issue):
```
np.random.choice(2000000000000000000000000, size=(100,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numpy/random/mtrand.pyx", line 997, in numpy.random.mtrand.RandomState.choice
  File "numpy/random/mtrand.pyx", line 781, in numpy.random.mtrand.RandomState.randint
  File "numpy/random/_bounded_integers.pyx", line 1332, in numpy.random._bounded_integers._rand_int64
ValueError: high is out of bounds for int64
```
It's pretty clearly a numpy problem that assumes 32bit on your end. This is usually a 32bit python in your container. Can you run the specific line in python and see whether you get an error (it's important to run in the same session and same interpreter).
Installing github from main makes it easier to debug.

**Comment by Ron-bio** [comment]
Thank you for your help. After checking my environment, I found that while my Python installation is 64-bit, Numpy appears to be 32-bit. I suspect this mismatch is causing the issue. I'm using Anaconda on Windows, which might be the source of the problem. I'll try running this on a Linux platform to see if that resolves it.

**Comment by Ron-bio** [comment]
Hi @canergen,

Thank you for your help. After checking my environment, I found that while my Python installation is 64-bit, Numpy appears to be 32-bit. I suspect this mismatch is causing the issue. I'm using Anaconda on Windows, which might be the source of the problem. I'll try running this on a Linux platform to see if that resolves it.

**Comment by ilan-gold** [comment]
@Ron-bio @canergen I think this is a windows issue, see: https://github.com/scverse/scanpy/issues/2969 and https://github.com/scverse/scanpy/issues/3028

**Comment by canergen** [comment]
I’m open to use np.Generator. It is one of the commented out ruff flags as it blows up the code quite a bit to change it everywhere. However, if scanpy doesn’t support it, to me it makes sense to push towards custom  in the future (still experimental), if running huge data on Windows is necessary.

**Comment by Ron-bio** [comment]
@canergen Thank you for the prompt response! I resolved the previous error by creating a new Anaconda environment on windows and installing the latest version of scvi-tools. I’m now able to proceed with the subsequent analyses without any issues. Only one warning was encountered that does not affect the analysis: 
```..\Anaconda3\envs\scvi\lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.```

```../Anaconda3/envs/scvi/lib/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:424): The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.```

**Comment by canergen** [comment]
Can you provide any differences between both environments? This might be helpful if the same issue arises for other users.
This num_worker warning is a PyTorch thing. Before the release of scVI-tools 1.2 and allowing persistent workers more workers might actually be slower as our models are quite small.

**Comment by Ron-bio** [comment]
Here are the env info that may be relevent:
The current env info:
```
name: scvi
dependencies:
  - python=3.9.19=h4de0772_0_cpython
  - pip:
      - numba==0.60.0
      - numpy==1.26.4
      - pandas==2.2.2
      - scanpy==1.10.3
      - scvi-tools==1.1.6.post2
```
The info from env pysc with int32 error:
```
name: pysc
dependencies:
  - python=3.9.17=h4de0772_0_cpython
  - pip:
      - numba==0.57.1
      - numpy==1.24.4
      - pandas==2.2.2
      - scanpy==1.9.3
      - scvi-tools==1.1.6
```

**Comment by canergen** [comment]
Thanks for reporting. Great that it's working now. Closing here.
