### ISSUE TITLE
Problems of torchmetrics

### ISSUE THREAD

**Issue by HelloWorldLTY** [scverse/scvi-tools#3031]
### Report

Hi, I notice that the default setting will lead to a problem caused by torchmetrics when importing pertpy:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11648

To fix it, we should use:  torchmetrics==0.11.4

I can create a pull request if necessary.

**Comment by canergen** [comment]
Can you expand on what the issue is with torchmetrics>0.11.4?
I think in our tests it works without the version restriction. Generally, we try to avoid version pinning and fix the underlying issue that is incompatible.

**Comment by HelloWorldLTY** [comment]
Hi, I notice that this issue can be resolved by upgrading the version of python to 3.10/3.11. The problem is mentioned here:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11648
