### ISSUE TITLE
scvi-tool 0.20.3 is using deprecated np.str type causing errors

### ISSUE THREAD

**Issue by Dennis-Bersenev** [scverse/scvi-tools#3106]
Need to modify line 81 of scvi/data/_built_in_data/_pbmc.py  because the current implementation is using a deprecated NumPy string type np.str.
Proposed solution involves replacing np.str lines with the code shown below:
barcodes_metadata = pbmc_metadata["barcodes"].index.values.ravel().astype(str)

```python
scvi.data.pbmc_dataset()
```

```pytb
python3.10/site-packages/scvi/data/_built_in_data/_pbmc.py", line 81, in loadpbmc_dataset
    barcodes_metadata = pbmc_metadata["barcodes"].index.values.ravel().astype(np.str)
  File "/home/ubuntu/SBI/rna_fm/scgpt-env/lib/python3.10/site-packages/numpy/init.py", line 324, in getattr
    raise AttributeError(former_attrs[attr])
AttributeError: module 'numpy' has no attribute 'str'.
```

#### Versions:

Name: scvi-tools
Version: 0.20.3

**Comment by canergen** [comment]
Please follow the instructions in our docs and install the most recent version 1.2.1. This version is compatible with numpy<2.0. 2.0 is not supported by dependencies. 1.3 will drop these dependencies.
