### ISSUE TITLE
Possibility of having different number of units in the hidden layers

### ISSUE THREAD

**Issue by gprashant17** [scverse/scvi-tools#696]
I would like to know if it is possible for the VAE model (in scVI) to have different number of hidden units in each hidden layer. Currently, I am assuming that there can only be one or more hidden layers with the same number of hidden units, as the argument `n_hidden` takes only one integer value rather than a list of values.

**Comment by adamgayoso** [comment]
This is not currently possible, but if you would like to make a PR implementing this, we can probably benefit from this functionality.
