### ISSUE TITLE
train() arguments not used if train() was previously called

### ISSUE THREAD

**Issue by galenxing** [scverse/scvi-tools#808]
Since we keep `self.trainer` persistent in train(), running train() again with new arguments for frequency, n_iter_kl_warmup, etc wont be reflected. 

```python
a = scvi.data.synthetic_iid()
m = scvi.model.SCVI(a)
m.train(10)
print(m.history) # empty 
m.train(10, frequency=1)
print(m.history) # also empty
```

**Comment by adamgayoso** [comment]
@galenxing -- what's the new behavior and is this what we want?
