### ISSUE TITLE
scANVI does not compute the conditioned ELBO

### ISSUE THREAD

**Issue by PierreBoyeau** [scverse/scvi-tools#841]
The current implementation of scANVI only computes the ELBO without relying on the cell states' knowledge for labeled examples (see [here](https://github.com/YosefLab/scvi-tools/blob/master/scvi/core/trainers/annotation.py#L200)). 
We should fix this behavior and treat labeled and unlabelled examples separately.

There are two options to consider to code this. The first one would use only one data loader, and compute the proper ELBO for each data-point. In the other option, in phase with the current codebase, we would compute the marginalized ELBO for a minibatch of unlabelled cells, and the conditioned ELBO for labelled cells. The overall ELBO would be weighted out based on the labelled fraction of the training data. I would opt for the second option.

However, I don't know which default behavior and training options we should provide. Should the current behavior still be an option?

#### Versions:

> VERSION

**Comment by martinkim0** [comment]
Closing this in favor of #1784
