### ISSUE TITLE
Autotune with Ray Tune

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scvi-tools#981]
It should be relatively straightforward to create a new autotune module with [Ray tune](https://docs.ray.io/en/master/tune/tutorials/tune-pytorch-lightning.html).

**Comment by adamgayoso** [comment]
@mjayasur and I discussed this on slack, but an acceptable initial API might do the following

```python
auto = Autotune(adata, scvi.model.SCVI, name=name)
# set config
auto.set_hyperparam_space(dict(lr=...))
# set callback
auto.track_metrics(metrics_dict)
auto.add_scheduler(scheduler)
auto.add_reporter(reporter)
# runs tune.run
auto()
```

which could then be wrapped with functions like

```python
# wraps code snippet above
best_model_instance = autotune_scvi(hyperparm_space: Optional[dict] = None)
```

**Comment by mjayasur** [comment]
dummy metric function:

- do something dumb

silhouette metric function:
- get latent representation from model
- scanpy neighbors
- scanpy leiden cluster
- get the leiden, then compute the silhouette with respect to the latent representation

**Comment by martinkim0** [comment]
Closing issue because of #1565.
